Documentation for using table component in Bodiless sites.
johnsonandjohnson/Bodiless-JS pull request #1049
Opened 2021-08-16 20:55 UTC by azion1995

## Changes
- Add introduction to Architecture section, explaining the reasons for
  the architectural decisions that were made, as well as the benefits
  that come with them.

## Related Issues
Fixes #1048

2021-08-18 13:17 UTC, hvanyo commented on examples/test-site/package.json
> +    "gatsby develop -p 8005 --host 0.0.0.0",
@azion1995 please remove these changes.   Site will not come up and run its test with these changes.

2021-08-18 14:33 UTC, azion1995 reviewed
Removed change made to bring Bodiless-JS up on Windows via Lando.

2021-08-18 14:33 UTC, azion1995 commented on examples/test-site/package.json
> +    "gatsby develop -p 8005 --host 0.0.0.0",
Done.

2021-08-18 15:15 UTC, azion1995 commented
Done. Sorry- --host 0.0.0.0 was necessary to bring Bodiless up and running
via Lando on a Windows system. I have now installed linux, so that kludge
is no longer necessary.

Best,
-Z

On Wed, Aug 18, 2021 at 9:17 AM hvanyo ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In examples/test-site/package.json
> <https://github.com/johnsonandjohnson/Bodiless-JS/pull/1049#discussion_r691227584>
> :
>
> > -    "dev-frontend": "gatsby develop -p 8005",
> +    "gatsby develop -p 8005 --host 0.0.0.0",
>
> @azion1995 <https://github.com/azion1995> please remove these changes.
> Site will not come up and run its test with these changes.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/johnsonandjohnson/Bodiless-JS/pull/1049#pullrequestreview-732850229>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO6EEHIKUI5RLUO3NQLF64DT5OXHLANCNFSM5CIPPFTA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-19 20:59 UTC, hvanyo commented on .gitignore
> +# Project dependencies
DId spacing change in this file, we probably want to avoid changes other files other than MD for spacing.

2021-08-19 20:59 UTC, hvanyo commented on .gitignore
> +# Project dependencies
or end of line

2021-08-19 20:59 UTC, hvanyo commented on packages/bodiless-table/bodiless.docs.json
> +  "assets": {
1) check this indenting
2) None of these images display either in http://localhost:8005/___docs/#/Components/Table

2021-08-19 21:05 UTC, hvanyo commented
@azion1995  I don't see anything wrong -- sometimes these tests fail randomly and on your next commit they work.  Please make the few changes I mentioned and commit again and it will retrigger the tests running. 

In meantime @e2thex  please review table documetnation and provide feedback

2021-08-23 14:20 UTC, e2thex requested changes

2021-08-23 14:20 UTC, e2thex commented on packages/bodiless-table/README.md
> +> Here would be instructions regarding moving a row or column, but this feature
So this is how it is supposed to work.  You can only move columns one direction.  The choice was to have few buttons.  But one can always move the column before moving it. 

- [ ] Update to reflect this is how it works

2021-08-23 14:20 UTC, e2thex commented on packages/bodiless-table/README.md
> +> I don't think this feature is fully implemented, as clicking the button to add a
The footer is implemented, it is just the default does not have different styling on the footer.  But it is adding a row to the footer section of the table.

2021-08-23 14:20 UTC, e2thex commented on packages/bodiless-table/README.md
> +Bodiless-JS allows you to insert two types of tables. One type has headers in the top
I think instead of saying it has two type say that it has two default styles.  and explaining that other styles can be created would be helpful

- [ ] Update intro to discuss that bodiless has two default styles

2021-08-23 15:57 UTC, azion1995 commented on packages/bodiless-table/README.md
> +Bodiless-JS allows you to insert two types of tables. One type has headers in the top
Changes
Update documentation for table component with description of how to use Bodiless GUI to insert Table component.

Related Issues
Fixes #1048

Comments
3

2021-08-23 19:17 UTC, azion1995 commented
Corrected missing comma in json and removed unnecessary line feed in .gitignore; should be good.

2021-08-30 18:33 UTC, azion1995 commented
resolved in [PR #1061|https://github.com/johnsonandjohnson/Bodiless-JS/pull/1061], closing.

2021-08-30 18:33 UTC, closed without merging