chore(deps): Dependency upgrade and Gatsby 3 with image plugin
johnsonandjohnson/Bodiless-JS pull request #1056
Opened 2021-08-26 14:23 UTC by dewen

## Changes

- Gatsby v3 upgrade
- Gatsby plugin image upgrade
- Bodiless dependency upgrade
- Tooltip v5 upgrade
- Webpack v5 upgrade

## Test Instructions

## Related Issues

2021-08-31 07:53 UTC, irkhodzka commented
hi @dewen,

please see issue_3:

Links to downloadable files do not accept files >1MB

**STR:**
1. Go to any page with the component which allows to upload file, e.g. /files/
2. In edit mode click any link type for uploading a file
3. Try to upload (most often reproducible using drag&drop) acceptable file type but >1MB, e.g.
[file-sample_1,11MB-converted.pdf](https://github.com/johnsonandjohnson/Bodiless-JS/files/7082141/file-sample_1.11MB-converted.pdf)
 
**Expected Result**: File is uploaded and saved
**Actual Result:** "Upload failed, please try again." error is shown
<img width="418" alt="link-to-filed" src="https://user-images.githubusercontent.com/81805756/131464628-e5288862-e27f-4da0-a581-35a52a25140c.png">

2021-09-01 11:20 UTC, irkhodzka commented
@dewen ,
please find issue_4
Cards resizing become unavailable after adding an image and performing ~5 consecutive actions with card.
**STR:**
1. Go to any page with Card component available in flow-container (e.g. /flow-container/)
2. Add any Card variation (e.g. Horizontal Card)
3. Add any image to the Card
4. Perform not less than 5 actions with the card (e.g. - try to resize it several times/or add title, body, cta etc.)
5. Observe image reloads 
6. Try to resize Card again

**Expected Result**: Card can always be resized

**Actual Result:** After performing >5 actions  with card 

-  image reloads (become blured and loads again)
- card  cannot be resized
_Please see videocast:_

https://user-images.githubusercontent.com/81805756/131658381-c5d0d765-8882-46fb-9707-f5aa5b56ced5.mp4

2021-09-02 12:55 UTC, irkhodzka commented
**issue_5**
/sitemap.xml/ leads to page not found

**STR:**
1. Go to /sitemap.xml 

**Actual Result**: Page not found

**Expected Result:** sitemap.xml is generated

2021-09-05 14:12 UTC, dewen commented
> Hi @dewen ,
> 
> please see **issue_1**:
> _New page creation: The slashes are not allowed in the URL field_
> 
> **Steps to Reproduce:**
> 
> 1. in Edit env, open any page, except Home, e.g. /accordion/
> 2. switch to Edit mode
> 3. click '+Page'
> 4. type a page name, e.g. page_1
> 5. click 'Edit' below Page Path -> URL is /accordion/page_1
> 6. click 'v' to save the new page
> 
> _Actual Results:_
> 'No special characters or spaces allowed' shows, the page is not created.
> ![Screen Shot 2021-08-26 at 2 41 48 PM](https://user-images.githubusercontent.com/3224040/131018381-a5b3dda5-3a8d-4322-9d2b-ddd8383ebb35.png)
> 
> _Expected Result:_
> the slashes are expected to be allowed. the new page is created for that case

currently, only "a-z0-9_-" allowed for new relative page path. Adding "/" could change the original requirement on nested pages.

2021-09-07 03:38 UTC, dewen commented
@irkhodzka  the sitemap is generated on production node only, so please run `npm run build` && `npm run serve` to check.

2021-09-09 13:34 UTC, VancheeZze commented on packages/bodiless-core-ui/src/LocalContextMenu.tsx
> +type Props = {
Do we want to export this type? We use it in few other places

2021-09-09 13:35 UTC, VancheeZze commented on packages/bodiless-core/src/components/LocalContextMenu.tsx
> +type Props = {
We can use `PropsWithChildren` type from react for this

2021-09-10 03:36 UTC, dewen commented on packages/bodiless-core/src/components/LocalContextMenu.tsx
> +type Props = {
PropsWithChildren has {children?: ReactNode | undefined}, which is not matching a Tooltip children prop (React.ReactElement).

Applied a different type.

2021-09-10 13:08 UTC, dewen commented on packages/bodiless-core-ui/src/LocalContextMenu.tsx
> +type Props = {
Updated,

Thanks

2021-09-10 13:29 UTC, dewen commented on packages/gatsby-theme-bodiless/src/dist/NewPageURLField.tsx
> +const getPagePathValidator = (validate?: FieldValidate) => (
Using hooks in regular JS function instead of React FC and behind a condition (isFull check) seems breaking the hooks rules.

2021-09-19 04:07 UTC, dewen commented on cypress/support/commands.js
> +const resizeObserverLoopErrRe = /^[^(ResizeObserver loop limit exceeded)]/
Adding this workaround to address "ResizeObserver loop limit exceeded". It fails the Cypress test with message:

`The following error originated from your application code, not from Cypress. >
ResizeObserver loop limit exceeded When Cypress detects uncaught errors
originating from your application it will automatically fail the current test.`

2021-09-19 04:23 UTC, dewen commented on examples/starter/.env.site
> +# To disable it - set value to '0'
gatsby-plugin-robots-txt v1.6.9 changed default sitemap path to
`${siteMetadata.siteUrl}/sitemap/sitemap-index.xml`

https://github.com/mdreizin/gatsby-plugin-robots-txt#options

2021-09-19 04:48 UTC, dewen commented on packages/headless-chrome-crawler/.eslintrc.js
> +  ignorePatterns: ['.eslintrc.js'],
Too address `0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.` issue

2021-09-19 04:50 UTC, dewen commented on tsconfig.settings.json
> +    "types": ["jest", "node"],
Address the type error on `expect` object

2021-09-19 05:03 UTC, dewen commented on examples/test-site/gatsby-node.js
> +      devtool: false,
disable the source map to address the performance issue.

2021-09-19 05:07 UTC, dewen commented on packages/bodiless-components/__tests__/Image.test.tsx
> +    let tooltips = wrapper.find(Tooltip);
'Tooltip' no longer a display name, so find by component type.

2021-09-20 12:12 UTC, VancheeZze submitted a review, later dismissed

2021-09-20 13:23 UTC, wodenx commented on examples/test-site/gatsby-node.js
> +      devtool: false,
Can we add a comment here describing how to re-enable the sourcemaps and/or do it based on an env var.

2021-09-20 13:38 UTC, wodenx commented on packages/bodiless-core/src/Types/ContextMenuTypes.tsx
> +export type TooltipProps = {
Can we avoid duplicating this type (https://github.com/johnsonandjohnson/Bodiless-JS/pull/1056/files#diff-0bcdbe3dff904ef66e8d43dc5b8db57e330b605943bfd984ec2a0a601131dfa2R52)

2021-09-20 13:46 UTC, wodenx commented on packages/gatsby-plugin-ssi/read-ssi-entities.js
> +// @todo: replace unsafe fs
Do we have a ticket for this?  afaict use of fs disables incremental builds...

2021-09-20 13:47 UTC, wodenx commented on packages/bodiless-core/src/components/LocalContextMenu.tsx
> +const LocalContextMenu: FC<{children?: ReactElement}> = ({ children }) => {
Why is this necessary?

2021-09-20 13:53 UTC, wodenx commented on packages/gatsby-theme-bodiless/src/dist/NewPageURLField.tsx
> +const getPagePathValidator = (validate?: FieldValidate) => (
True, but, these functions are only called within React FC (could be renamed to 1use...`) and can be refactored so as to remove the condition.

2021-09-20 20:14 UTC, dewen commented on examples/test-site/src/data/pages/cards/index.jsx
> +const main = props => (
This fix is to address the console warning: "Anonymous arrow functions cause Fast Refresh to not preserve local component state." after Gatsby v3 upgrade.

See https://www.gatsbyjs.com/docs/reference/local-development/fast-refresh/#limitations

2021-09-20 21:23 UTC, dewen commented on packages/bodiless-core/src/components/LocalContextMenu.tsx
> +const LocalContextMenu: FC<{children?: ReactElement}> = ({ children }) => {
New Tooltip defined children as React.ReactElement:
https://github.com/react-component/tooltip/blob/master/src/Tooltip.tsx#L37

Omit generic type for FC causing a type error: `Type 'ReactNode' is not assignable to type 'ReactElement<any, string | JSXElementConstructor<any>> | undefined'`

2021-09-20 21:39 UTC, dewen commented on packages/gatsby-plugin-ssi/read-ssi-entities.js
> +// @todo: replace unsafe fs
https://github.com/johnsonandjohnson/Bodiless-JS/issues/1101

2021-09-21 13:15 UTC, VancheeZze approved these changes

2021-09-21 17:43 UTC, TatsianaMiraniuk requested changes

2021-09-21 17:43 UTC, TatsianaMiraniuk commented on examples/test-site/.env.site
> +BODILESS_BACKEND_SAVE_ENABLED='0'
@dewen - this has to be still commented out - having BODILESS_BACKEND_SAVE_ENABLED='0'  does not save any content, e.g. edit/add anything in Edit mode, then reload a page -> as a result,  the entered data is lost. That's why Cypress test Link_toggle has failed.

2021-09-22 18:14 UTC, TatsianaMiraniuk commented
Hi @dewen ,

please see **issue_6**:
Submenu of MegaMenu doesn't close if it's not in focus anymore.

**STR:**
1. open Edit env, edit mode, any page, e.g. Home
2. add a top menu item
3. add a submenu (e.g. Card type)
4. click somewhere else outside MegaMenu
**Actual Results:**
Cards submenu is still open 
**Expected Results:**
Submenu closes once it loses a focus

Note: not reproduced in Master

2021-09-22 19:29 UTC, TatsianaMiraniuk commented
Hi @dewen ,

please see **issue_7**:
Burger Menu: Close/x button is placed at the left, Logo is at the right

**STR:**
1. open Edit env, edit mode, any page, e.g. Home
2. change a browser width to get Burger Menu
3. click Burger Menu button

**Actual Results:**
Burger Menu: Close/x button is placed at the left, Logo is at the right
![Screen Shot 2021-09-22 at 3 12 00 PM](https://user-images.githubusercontent.com/3224040/134409034-ee35cfb9-e32a-4e79-8849-f42b4bc81251.png)

**Expected Results:**
Close/x button is placed at the right, Logo is at the left

2021-09-22 21:36 UTC, TatsianaMiraniuk commented
Hi @dewen ,

please see **issue_8**:
There is a warning in a console in Preview mode on pageLoad; or when switching from Edit Mode to Preview mode)

_use case 1_

**STR:**
1. open Edit env, any page, e.g. Home
2. check a browser console

**Actual Results:**
there is a warning:
'Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?...'
![Screen Shot 2021-09-22 at 5 31 45 PM](https://user-images.githubusercontent.com/3224040/134424926-fab810d7-d7c0-4fc3-994b-66a2eb635398.png)

**Expected Results:**
no warnings


=================
_use case 2_

**STR:**
1. open Edit env, any page, e.g. Home
2. switch to Edit mode
3. load any page directly using its path
4. switch to Preview mode
5. check a browser console
 **Actual Results:**
there is a warning:
'Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?...'
![Screen Shot 2021-09-22 at 5 31 45 PM](https://user-images.githubusercontent.com/3224040/134424926-fab810d7-d7c0-4fc3-994b-66a2eb635398.png)

**Expected Results:**
no warnings

2021-09-22 21:45 UTC, TatsianaMiraniuk commented
Hi @dewen ,

please see **issue_9**:
There are 2 errors in a console in Static env on pageLoad


**STR:**
1. open Static env, any page, e.g. Home
2. check a browser console

**Actual Results:**
there are 2 errors 
'page resources for <page_path> not found. Not rendering React'
'Uncaught (in promise) TypeError: Path must be a string. Received 73391'
![Screen Shot 2021-09-22 at 5 43 30 PM](https://user-images.githubusercontent.com/3224040/134426243-9ffa012c-e29a-400d-a220-7f62018aa271.png)


**Expected Results:**
no warnings/errors

2021-09-22 22:29 UTC, TatsianaMiraniuk requested changes
there are the bugs that need an attention

2021-09-24 14:11 UTC, VancheeZze submitted a review, later dismissed

2021-09-24 20:35 UTC, TatsianaMiraniuk commented
> > Hi @dewen ,
> > please see **issue_9**[BLOCKER]:
> > There are 2 errors in a console in Static env on pageLoad. Due to that the pages/functionality are not working, e.g Search is not working, Accordion is not working, etc.
> > **STR:**
> > 
> > 1. open Static env, any page, e.g. Home
> > 2. check a browser console
> > 
> > **Actual Results:**
> > there are 2 errors
> > 'page resources for <page_path> not found. Not rendering React'
> > 'Uncaught (in promise) TypeError: Path must be a string. Received 73391'
> > ![Screen Shot 2021-09-22 at 5 43 30 PM](https://user-images.githubusercontent.com/3224040/134426243-9ffa012c-e29a-400d-a220-7f62018aa271.png)
> > **Expected Results:**
> > no warnings/errors
> 
> This issue is caused by webpack 5 upgrade, where require.resolve() return type changed to number.
> 
> Fixed by cast number to string.

issue_9 is fixed. Thanks!

2021-09-24 20:55 UTC, TatsianaMiraniuk commented
@dewen ,

please see **issue_10**:

Submenu of MegaMenu closes if a mouse cursor moves out of the submenu, even if the submenu item is still in focus

**STR:**
1. open Edit env, edit mode, any page, e.g. Home
2. hover over a top menu item that has a submenu items
3. click the submenu item so it's in focus
4. move over a mouse pointer outside of MegaMenu
**Actual Results:**
the submenu disappears, Local Context Menu is still visible
**Expected Results:**
Submenu stays open until a focus isn't changed

Note: not reproduced in Master

2021-09-27 18:41 UTC, TatsianaMiraniuk commented
@dewen ,

please see **issue_11**:

**STR:**
1. open Edit env, edit mode, /content-library/ page
2. scroll down to 'Image with library' 
3. click 'Image with library' image
4. scroll the page to Local Context Menu so that it's at the bottom of the page
5. click 'Select' on Local Context Menu
**Actual Results:**
'Upload Image' form opens below Local Context Menu and it's not fully visible (shown out of the viewport; depends on a viewport height)
**Expected Results:**
'Upload Image' form opens above Local Context Menu so it's not hidden out of the viewport

Please compare with master
![Screen Shot 2021-09-27 at 2 30 01 PM](https://user-images.githubusercontent.com/3224040/134966087-f27d0d56-ffa9-41b0-80af-39459526e3ba.png)

2021-09-27 21:56 UTC, TatsianaMiraniuk commented
> Hi @dewen ,
> 
> please see **issue_8**:
> There is a warning in a console in Preview mode on pageLoad; or when switching from Edit Mode to Preview mode)
> 
> _use case 1_
> 
> **STR:**
> 
> 1. open Edit env, any page, e.g. Home
> 2. check a browser console
> 
> **Actual Results:**
> there is a warning:
> 'Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?...'
> ![Screen Shot 2021-09-22 at 5 31 45 PM](https://user-images.githubusercontent.com/3224040/134424926-fab810d7-d7c0-4fc3-994b-66a2eb635398.png)
> 
> **Expected Results:**
> no warnings
> 
> =================
> _use case 2_
> 
> **STR:**
> 
> 1. open Edit env, any page, e.g. Home
> 2. switch to Edit mode
> 3. load any page directly using its path
> 4. switch to Preview mode
> 5. check a browser console
>    **Actual Results:**
>    there is a warning:
>    'Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?...'
>    ![Screen Shot 2021-09-22 at 5 31 45 PM](https://user-images.githubusercontent.com/3224040/134424926-fab810d7-d7c0-4fc3-994b-66a2eb635398.png)
> 
> **Expected Results:**
> no warnings

it's been found that the warning is caused by a link in a body of Card submenu and that is reproducible in Master. #1116 
SO not in the scope for the current ticket.

2021-09-28 08:12 UTC, inesa-hapeyeva commented
hi @dewen,

please see issue_12 : 

1. Go to /youtube/ page (edit/static env)
2. scroll down to 'YouTube Player API'
3. Click 'Play'/'Stop' button
4. Observe buttons border color

Actual Results:
buttons don't get bordered on focus



https://user-images.githubusercontent.com/31862315/135048887-e2c318b7-3386-4047-8dfb-4dbcf464fe1d.mp4


Expected Results:
buttons bordered on focus (Master env)



https://user-images.githubusercontent.com/31862315/135048999-02aabbe1-25b0-4c87-bcb9-1d6a35af9b82.mp4

2021-09-28 12:50 UTC, irkhodzka commented
hi @dewen,

please see issue_13:

Upload Images >5MB to Images or Cards introduces unexpected behavior.

**STR:**
1. Go to any page with possibility to add cards or images, e.g. /image/
2. Add Card/ Image component (any)
3. Try to upload a file >5MB size (either using drag&drop or file manager), e.g. 
![5MB](https://user-images.githubusercontent.com/81805756/135088871-e5bce1db-ab53-4301-8c08-5e1555e6e60b.jpg)
4. Observe uploading behavior.

**ER**: Image uploaded or an error message saying that the image size is too large is displayed.

**AR:**
_Several cases possible:_
- Image upload fails with an error "Upload failed. Please try again" 
- An error "Upload failed. Please try again" is shown for several seconds and then "Done!" is displayed. The image is not shown to user for couple minutes and then uploads.
- Image uploads with "Done!" success message, but is not shown on static.
- Image uploaded successfully and is shown on static (rarely)
Please see video attachment:

https://user-images.githubusercontent.com/81805756/135089654-d68cd996-14ac-4eb7-b9a2-b442924105f1.mp4

2021-09-28 20:10 UTC, dewen commented
> @dewen ,
> 
> please see **issue_11**:
> 
> **STR:**
> 
> 1. open Edit env, edit mode, /content-library/ page
> 2. scroll down to 'Image with library'
> 3. click 'Image with library' image
> 4. scroll the page to Local Context Menu so that it's at the bottom of the page
> 5. click 'Select' on Local Context Menu
>    **Actual Results:**
>    'Upload Image' form opens below Local Context Menu and it's not fully visible (shown out of the viewport; depends on a viewport height)
>    **Expected Results:**
>    'Upload Image' form opens above Local Context Menu so it's not hidden out of the viewport
> 
> Please compare with master ![Screen Shot 2021-09-27 at 2 30 01 PM](https://user-images.githubusercontent.com/3224040/134966087-f27d0d56-ffa9-41b0-80af-39459526e3ba.png)

This UI difference is coming from an extra space on the bottom of page. The tooltip popup fits the space so it displayed below the image button. 

We might need to address the space issue separately since it's on master as well.

2021-09-30 16:46 UTC, TatsianaMiraniuk commented
> Hi @dewen ,
> 
> please see **issue_6**: Submenu of MegaMenu doesn't close if it's not in focus anymore.
> 
> **STR:**
> 
> 1. open Edit env, edit mode, any page, e.g. Home
> 2. add a top menu item
> 3. add a submenu (e.g. Card type)
> 4. click somewhere else outside MegaMenu
>    **Actual Results:**
>    Cards submenu is still open
>    **Expected Results:**
>    Submenu closes once it loses a focus
> 
> **STR:**
> 
> 1. open Edit env, edit mode, any page, e.g. Home
> 2. click any top menu item with a submenu
> 3. click somewhere else outside of MegaMenu
>    **Actual Results:**
>    the submenu is still open
>    **Expected Results:**
>    Submenu closes once it loses a focus
> 
> Note: not reproduced in Master

moved to a separate issue - #1126

2021-09-30 16:47 UTC, TatsianaMiraniuk commented
> Hi @dewen ,
> 
> please see **issue_7**: Burger Menu: Close/x button is placed at the left, Logo is at the right
> 
> **STR:**
> 
> 1. open Edit env, edit mode, any page, e.g. Home
> 2. change a browser width to get Burger Menu
> 3. click Burger Menu button
> 
> **Actual Results:** Burger Menu: Close/x button is placed at the left, Logo is at the right ![Screen Shot 2021-09-22 at 3 12 00 PM](https://user-images.githubusercontent.com/3224040/134409034-ee35cfb9-e32a-4e79-8849-f42b4bc81251.png)
> 
> **Expected Results:** Close/x button is placed at the right, Logo is at the left

this is not reproduced anymore

2021-09-30 17:00 UTC, TatsianaMiraniuk commented
> @dewen ,
> 
> please see **issue_10**:
> 
> Submenu of MegaMenu closes if a mouse cursor moves out of the submenu, even if the submenu item is still in focus
> 
> **STR:**
> 
> 1. open Edit env, edit mode, any page, e.g. Home
> 2. hover over a top menu item that has a submenu items
> 3. click the submenu item so it's in focus
> 4. move over a mouse pointer outside of MegaMenu
>    **Actual Results:**
>    the submenu disappears, Local Context Menu is still visible
>    **Expected Results:**
>    Submenu stays open until a focus isn't changed
> 
> Note: not reproduced in Master

moved out as a separate issue - #1127

2021-09-30 18:49 UTC, VancheeZze approved these changes

2021-10-01 17:38 UTC, TatsianaMiraniuk commented
> > @dewen ,
> > please see **issue_11**:
> > **STR:**
> > 
> > 1. open Edit env, edit mode, /content-library/ page
> > 2. scroll down to 'Image with library'
> > 3. click 'Image with library' image
> > 4. scroll the page to Local Context Menu so that it's at the bottom of the page
> > 5. click 'Select' on Local Context Menu
> >    **Actual Results:**
> >    'Upload Image' form opens below Local Context Menu and it's not fully visible (shown out of the viewport; depends on a viewport height)
> >    **Expected Results:**
> >    'Upload Image' form opens above Local Context Menu so it's not hidden out of the viewport
> > 
> > Please compare with master ![Screen Shot 2021-09-27 at 2 30 01 PM](https://user-images.githubusercontent.com/3224040/134966087-f27d0d56-ffa9-41b0-80af-39459526e3ba.png)
> 
> This UI difference is coming from an extra space on the bottom of page. The tooltip popup fits the space so it displayed below the image button.
> 
> We might need to address the space issue separately since it's on master as well.

the issue #1128 has been reported.

2021-10-04 13:43 UTC, VancheeZze submitted a review, later dismissed

2021-10-04 16:57 UTC, irkhodzka commented
@dewen 
issue_14
**STR:**

1.  open Edit env, edit mode, any page, e.g. Home
2. Click on any Top Menu Item with a submenu, so that local context menu appeared
3. click somewhere else outside of MegaMenu
4. Hover over menu items with submenu

**Actual Result:** Submenu does not drop down on hover. Workaround: switch 'off' and then 'on'  edit mode

**Expected Result** submenu drops down on hover

2021-10-04 19:03 UTC, irkhodzka approved these changes

2021-10-04 19:10 UTC, hvanyo approved these changes

2021-10-05 13:40 UTC, merged