[WIP] Tailwind purge whitelist autodiscovery
johnsonandjohnson/Bodiless-JS pull request #1105
Opened 2021-09-23 08:10 UTC by allencit

## Changes

## Test Instructions

## Related Issues

2021-09-27 12:21 UTC, wodenx requested changes

2021-09-27 12:21 UTC, wodenx commented on packages/gatsby-theme-bodiless/src/dist/generate-tailwind-configs/getTailwindConfigs.ts
> +const getBodilessTailwindConfig = async (deps: string[]) => {
Seems this `deps` arg is unused?

2021-09-27 12:21 UTC, wodenx commented on packages/gatsby-theme-bodiless/src/dist/generate-tailwind-configs/getTailwindConfigs.ts
> +  filePattern: new RegExp('^tailwind.config.js$'),
I wonder if, instead of finding all `tailwind.config.js` we should require package maintainers to give a special name to those which  they want included/merged -- maybe something like `site.tailwind.config.js`?

2021-09-27 12:21 UTC, wodenx commented on packages/gatsby-theme-bodiless/src/dist/generate-tailwind-configs/index.ts
> +// This file is generated automatically, please don't change it
Ok, but what mechanism would a site-builder use to add site-level tailwind configs?

2021-09-27 12:21 UTC, wodenx commented on packages/gatsby-theme-bodiless/src/dist/generate-tailwind-configs/index.ts
> +  const deps = Object.keys(getDependenciesFromPackageJson(pkg));
Do we still need this?  Seems we are walking the node_modules to find them...

2021-09-27 12:21 UTC, wodenx commented on packages/gatsby-theme-bodiless/src/dist/generate-tailwind-configs/index.ts
> +  await writeToFile('.tailwindConfigs.js', templateWrap.replace(/#pkgs/g, cfgs));
I wonder if we should just write the `tailwind.config.js` and require site-level configs to be in `site.tailwind.config.js` or similar?

2021-09-28 07:14 UTC, allencit commented on packages/gatsby-theme-bodiless/src/dist/generate-tailwind-configs/getTailwindConfigs.ts
> +const getBodilessTailwindConfig = async (deps: string[]) => {
It's been used [here](https://github.com/johnsonandjohnson/Bodiless-JS/pull/1105/files#diff-e9bf39c138fc62510005e8dc727fd8b1161fba6db5a4a684b4b2af8bbe5ca7b4R48)

2021-09-28 07:15 UTC, allencit commented on packages/gatsby-theme-bodiless/src/dist/generate-tailwind-configs/getTailwindConfigs.ts
> +  filePattern: new RegExp('^tailwind.config.js$'),
Addressed as you suggested

2021-09-28 07:20 UTC, allencit commented on packages/gatsby-theme-bodiless/src/dist/generate-tailwind-configs/index.ts
> +  const deps = Object.keys(getDependenciesFromPackageJson(pkg));
Yes, there is two steps to generate the configs automatically.

1.Walking the node_modules to find the pacages which has the site.tailwind.config.js file
2.Make sure the package is be used in the site

That means if a package has the site.tailwind.config.js but the package is not in the site dependencies will not be included

2021-09-28 07:20 UTC, allencit commented on packages/gatsby-theme-bodiless/src/dist/generate-tailwind-configs/index.ts
> +  const deps = Object.keys(getDependenciesFromPackageJson(pkg));
Yes, there is two steps to generate the configs automatically.

1.Walking the node_modules to find the pacages which has the site.tailwind.config.js file
2.Make sure the package is be used in the site

That means if a package has the site.tailwind.config.js but the package is not in the site dependencies will not be included

2021-09-28 07:20 UTC, allencit commented on packages/gatsby-theme-bodiless/src/dist/generate-tailwind-configs/index.ts
> +  await writeToFile('.tailwindConfigs.js', templateWrap.replace(/#pkgs/g, cfgs));
Addressed as you suggested

2021-09-28 07:23 UTC, allencit commented on packages/gatsby-theme-bodiless/src/dist/generate-tailwind-configs/index.ts
> +// This file is generated automatically, please don't change it
Addressed as you suggested to use site.tailwind.config.js for the site-level one

2021-10-01 09:23 UTC, wodenx commented on packages/gatsby-theme-bodiless/src/dist/generate-tailwind-configs/index.ts
> +  const deps = Object.keys(getDependenciesFromPackageJson(pkg));
hm.... but what about transitive dependencies?  ie - if i depend on `foo` and `foo` depends on `bar` (but i don't require `bar` explicitly), i think i still need the classes uses by `bar`, no?

2021-10-01 09:49 UTC, wodenx requested changes

2021-10-01 09:49 UTC, wodenx commented on packages/gatsby-theme-bodiless/src/dist/tailwindcss/getBodilessPackages.ts
>  const getBodilessPackages = () => [
And why do we need this?  Won't we pick up the bodiless packages using he standard mechanism?

2021-10-01 09:49 UTC, wodenx commented on packages/gatsby-theme-bodiless/src/dist/generate-tailwind-configs/index.ts
> +  const deps = Object.keys(getDependenciesFromPackageJson(pkg));
Though I guess there is a problem in that in our monorepo structure, node_modules *may* contain packages which are not even transitive dependencies of the site...  Maybe the right way to resolve this is to print a warning if a "site.tailwind.config.js" file iencountered which is not in a direct dependency, and require that package to be added to package.json.  Or, we could print an error in this case, and require you either to specify the package as a dependency in package.json or to add the package to an explicit exclusion list...

2021-10-01 12:49 UTC, wodenx commented on packages/gatsby-theme-bodiless/src/dist/generate-tailwind-configs/index.ts
> +  const deps = Object.keys(getDependenciesFromPackageJson(pkg));
Actually - will the `require` fail if the package is not listed in the site level package.json?  Also - we probably will often want to run this using the dependencies of a brand package, not the site itself, so it would be good to have a way to specify one (or more) packages whose dependencies should be searched...

2021-10-14 06:09 UTC, merged