feat: Add tree shaking support to all browser packages
johnsonandjohnson/Bodiless-JS pull request #1208
Opened 2021-11-05 16:46 UTC by lucas-varela

## Changes
This PR adds tree shaking support to all packages that may be used in a browser.

The following packages are only used on Node and **won't** support tree shaking:
-  @bodiless/backend
-  @bodiless/cli
-  @bodiless/documentation
-  @bodiless/migration-tool
-  @bodiless/psh
-  @bodiless/gatsby-plugin-ssi
-  @bodiless/headless-chrome-crawler

Note on html2canvas: this package was used with a dynamic import in the past to prevent breaking SSR. The package has since been updated to support SSR, so I removed the dynamic import as it is no longer necessary.

## Related Issues
This PR closes https://github.com/johnsonandjohnson/Bodiless-JS/issues/1165

2021-11-08 10:59 UTC, marcopagliarulo requested changes
I think we are missing some required changes.

the typescript configuration is still set to transpile to commonjs
https://github.com/johnsonandjohnson/Bodiless-JS/blob/main/tsconfig.settings.json#L5-L6

target and module should be set to ES2015

I think we should use in https://github.com/johnsonandjohnson/Bodiless-JS/blob/main/babel.config.js

  "presets": [
    [
      "@babel/preset-react",
      { modules: false }
    ]
  ]

2021-11-08 10:59 UTC, marcopagliarulo commented on packages/bodiless-layouts/src/ComponentSelector/ScreenShot.tsx
> +import html2canvas from 'html2canvas';
The import of html2canvas was limited to the frontend, could this import change create issue during SSR?

2021-11-08 13:10 UTC, lucas-varela commented on packages/bodiless-layouts/src/ComponentSelector/ScreenShot.tsx
> +import html2canvas from 'html2canvas';
Not anymore, the package has since been updated to support SSR. It still doesn't work on node, the difference now is that it simply won't do anything, instead of throwing an error. Since the function that uses this package only ever runs on browsers anyway, it's safe to load it here statically.

2021-11-11 22:26 UTC, marcopagliarulo commented on babel.config.js
> +        ['@babel/plugin-transform-modules-commonjs'],
since we discovered the jest issue was due to the target set to es2015, I think we can remove this plugin as not useful anymore

2021-11-11 22:26 UTC, marcopagliarulo commented on package.json
> +    "@babel/plugin-transform-modules-commonjs": "^7.5.0",
as by comment above

2021-11-11 22:26 UTC, marcopagliarulo commented on packages/bodiless-documentation/tsconfig.json
> +    "target": "es5",
you don't need to override the target here since the value is the same of the base config

2021-11-11 22:26 UTC, marcopagliarulo commented on packages/bodiless-search/tsconfig.json
> +    "target": "es5",
you don't need to override the target here since the value is the same of the base config

2021-11-11 22:26 UTC, marcopagliarulo commented on packages/gatsby-theme-bodiless/tsconfig.json
> +    "target": "es5",
you don't need to override the target here since the value is the same of the base config

2021-11-12 13:03 UTC, lucas-varela commented on babel.config.js
> +        ['@babel/plugin-transform-modules-commonjs'],
Although our code is being compiled to es5, we're still using es2015 modules, so this plugin is necessary. I removed the other two, however, since it's redundant to add them to this list.

2021-11-12 13:04 UTC, lucas-varela commented on package.json
> +    "@babel/plugin-transform-modules-commonjs": "^7.5.0",
See above

2021-11-12 15:18 UTC, marcopagliarulo submitted a review, later dismissed

2021-11-15 11:45 UTC, marcopagliarulo approved these changes

2021-11-23 17:45 UTC, lucas-varela commented
New PR using local branch: #1251

2021-11-23 17:45 UTC, closed without merging