BodilessJS: Dependency packages usage allow tree shaking (lodash)
johnsonandjohnson/Bodiless-JS pull request #1216
Opened 2021-11-11 07:06 UTC by rageshchalil

## Changes

BodilessJS: Dependency packages usage allow tree shaking (lodash) 

## Test Instructions

## Related Issues

2021-11-15 11:35 UTC, marcopagliarulo approved these changes
The PR is approved, anyway, your brunch is out-of-date with the base branch, please merge the latest changes from main and verify that the in latest changes have not been introduced lodash import using the import from the whole library

2021-11-15 15:35 UTC, marcopagliarulo commented
There are still some imports that must be addressed:

1. https://github.com/rageshchalil/Bodiless-JS/blob/feat/treeshaking_lodash/packages/gatsby-theme-bodiless/src/dist/RemoteChanges.tsx#L16
2. https://github.com/rageshchalil/Bodiless-JS/blob/feat/treeshaking_lodash/packages/fclasses/src/Tokens.tsx#L16-L18
3. https://github.com/rageshchalil/Bodiless-JS/blob/feat/treeshaking_lodash/packages/bodiless-components/src/GTM/gtm.tsx#L18
4. https://github.com/rageshchalil/Bodiless-JS/tree/feat/treeshaking_lodash/packages/bodiless-bv/doc (this is a doc, so it doesn't affect tree shaking, anyway I'd fix it to not give a bad import example)

2021-11-15 15:36 UTC, marcopagliarulo requested changes
There are still some imports that must be addressed:

1. https://github.com/rageshchalil/Bodiless-JS/blob/feat/treeshaking_lodash/packages/gatsby-theme-bodiless/src/dist/RemoteChanges.tsx#L16
2. https://github.com/rageshchalil/Bodiless-JS/blob/feat/treeshaking_lodash/packages/fclasses/src/Tokens.tsx#L16-L18
3. https://github.com/rageshchalil/Bodiless-JS/blob/feat/treeshaking_lodash/packages/bodiless-components/src/GTM/gtm.tsx#L18
4. https://github.com/rageshchalil/Bodiless-JS/tree/feat/treeshaking_lodash/packages/bodiless-bv/doc (this is a doc, so it doesn't affect tree shaking, anyway I'd fix it to not give a bad import example)

2021-11-16 13:57 UTC, marcopagliarulo approved these changes

2021-11-17 14:08 UTC, hvanyo approved these changes

2021-11-17 16:14 UTC, merged