Clone Images for cloned page
johnsonandjohnson/Bodiless-JS pull request #1233
Opened 2021-11-16 22:30 UTC by dasdib

## Changes

- Copy images for cloned page

## Test Instructions

## Related Issues

- [Duplicating Images on Cloned paged #1177](https://github.com/johnsonandjohnson/Bodiless-JS/issues/1177)

2021-11-19 07:55 UTC, konst8 requested changes

2021-11-19 08:04 UTC, dasdib commented on packages/bodiless-backend/src/page.js
> +        ).then((dirent) => dirent.map((dirent) => dirent.name));
Actually fs.readdir() returns dirent . https://nodejs.org/api/fs.html#fsreaddirpath-options-callback

2021-11-19 11:47 UTC, dasdib commented on packages/bodiless-backend/src/backend.js
> +      await GitCmd.cmd().add('add', '--all').exec();
@konst8 I have reverted it back as changed code moved to page.js only.

2021-11-19 11:49 UTC, dasdib commented on packages/bodiless-backend/src/backend.js
> +  (process.env.BODILESS_BACKEND_EXTENDED_LOGGING_ENABLED || '0') === '1';
@konst8 I have moved the code changes to page.js only. Above section of code are untouched.

2021-11-19 11:51 UTC, dasdib commented on packages/bodiless-backend/src/page.js
> +    const originStaticPath = `${backendStaticPath}${target}${originPath}`;
@konst8  Updated with path.join() with new push.

2021-11-19 15:12 UTC, konst8 approved these changes

2021-11-22 14:05 UTC, irkhodzka approved these changes

2021-11-23 10:24 UTC, merged