[WIP] chore(performance): Mitigate page weight
johnsonandjohnson/Bodiless-JS pull request #1259
Opened 2021-12-02 15:52 UTC by konst8

## Changes
Create FC and Chameleon selectable components only when CS form is opened.

2021-12-02 19:01 UTC, wodenx requested changes

2021-12-02 19:01 UTC, wodenx commented on packages/bodiless-components/src/Chameleon/withChameleonButton.tsx
> +    const { design } = useChameleonContext();
And here - we need to omit default key in making this choice.  In all cases, you need to apply the design to get the metadata - so this is sightly problematic.  One way to resolve - check the number of keys in the design - if it's <= 2 then apply the design to get the metadata, and make the choice (between swap button and toggle button) based on whether the default key has a title.  Otherwise, defer applying the design (and filtering out the default key) to later.

2021-12-07 16:08 UTC, wodenx requested changes

2021-12-07 16:08 UTC, wodenx commented on packages/bodiless-components/src/Chameleon/withChameleonContext.tsx
> +      components: props.components,
I see - you only do it if the selector can be toggled - but I think it's confusing.  Really, all you need is to know whether the default key has a title, and the only place you need it is in `withChameleonButton` to determine what button to show -- so probably a better solution would be to check that key only there, like
```
const useShowToggleButton = () => {
  const { design } = useChameleonContext();
  if (Object.keys(design).length < 2) return true;
  if (Object.keys(desigh).length  > 2) return false;
  if (desigh[DEFAULT_KEY) === undefined) return false;
  const test = design[DEFAULT_KEY)(Fragment);
  return test.title === undefined;
}
```

2021-12-07 16:08 UTC, wodenx commented on packages/bodiless-components/src/Chameleon/withChameleonContext.tsx
> +  RootComponent: ComponentOrTag<any> = Fragment,
As discussed, either use this also when applying the chameleon or supply it as an argument to 'useChameleonSelectorForm`.  In either case, we want to be sure that `asBodilessChameleon` still gets it from the target, eg
```
asBodilessChameleon('nodeky')(ComponentX)
```
makes ComponentX the RootComponent.

2021-12-08 14:39 UTC, wodenx submitted a review, later dismissed

2021-12-09 16:57 UTC, wodenx commented on packages/bodiless-components/__tests__/asBodilessChameleon.test.tsx
> -    it('Applies a design correctly', () => {
I don't think completely disabling this test is right - instead i think you should just rewrite the assertion so that it passes regardless of the order of the keys.

2021-12-09 19:40 UTC, hvanyo commented on packages/bodiless-layouts/src/FlowContainer/index.tsx
> +import { flow, uniq, pick, omit } from 'lodash';
Q is this appropriate or do we want to four imports -- lodash/flow, lodash/uniq ?

2021-12-15 17:31 UTC, closed without merging

2021-12-15 17:32 UTC, wodenx commented
Replaced by #1308