Issue 1204
johnsonandjohnson/Bodiless-JS pull request #1265
Opened 2021-12-03 17:05 UTC by CarlosTeixeiraCIANDT

## Changes

Added a index and a role to the Burger Menu button so accessibility could use it, and added the event to open/close it with the keyboard
## Test Instructions

## Related Issues

2021-12-06 14:51 UTC, konst8 commented
@CarlosTeixeiraCIANDT Are these changes in the package-lock file expected? Should we exclude them from the PR?

2021-12-06 14:52 UTC, konst8 requested changes

2021-12-06 14:52 UTC, konst8 commented on packages/bodiless-navigation/src/BurgerMenu/BurgerMenuKeyboard.tsx
> +const BurgerMenuKeyPressHandler = (event: KeyboardEvent, isVisible: any, toggle: any) => {
@CarlosTeixeiraCIANDT  Can we add appropriate types here? The isVisible and toggle are booleans I guess?

2021-12-06 15:37 UTC, konst8 submitted a review, later dismissed

2021-12-06 15:41 UTC, dewen commented
please update the PR title that follows conventions:
https://johnsonandjohnson.github.io/Bodiless-JS/#/Development/Contributing?id=merging-pull-request

2021-12-07 18:54 UTC, lucas-varela approved these changes

2021-12-07 21:01 UTC, konst8 approved these changes

2021-12-14 15:10 UTC, merged