Fix lodash import on withMovePageButton.tsx
johnsonandjohnson/Bodiless-JS pull request #1323
Opened 2021-12-23 14:31 UTC by rageshchalil

Fix lodash import on withMovePageButton.tsx

## Changes

## Test Instructions

## Related Issues

2021-12-24 09:06 UTC, konst8 requested changes

2021-12-24 09:06 UTC, konst8 commented on packages/gatsby-theme-bodiless/src/dist/withMovePageButton.tsx
> +import flow from 'lodash/flow';
Hi @rageshchalil 
I think it makes sense to optimize the lodash imports in the examples folder as well, e.g.:
https://github.com/johnsonandjohnson/Bodiless-JS/blob/main/examples/test-site/src/components/YouTube/index.tsx#L15

2021-12-24 09:54 UTC, rageshchalil commented on packages/gatsby-theme-bodiless/src/dist/withMovePageButton.tsx
> +import flow from 'lodash/flow';
@konst8 
This is resolved now

2021-12-24 10:50 UTC, konst8 approved these changes

2021-12-28 15:25 UTC, hvanyo approved these changes

2021-12-29 10:54 UTC, merged