fix(lint): fixing ESlint detecting common syntax issue
johnsonandjohnson/Bodiless-JS pull request #1343
Opened 2022-01-20 03:11 UTC by dewen

## Changes

## Test Instructions

## Related Issues

2022-01-21 12:48 UTC, lucas-varela approved these changes

2022-01-21 12:50 UTC, lucas-varela requested changes
The changes are alright, but the lint process on GH Actions is breaking: https://github.com/johnsonandjohnson/Bodiless-JS/runs/4891952000?check_suite_focus=true

Could you please take a look?

2022-01-21 15:03 UTC, lucas-varela submitted a review, later dismissed

2022-01-21 19:04 UTC, lucas-varela approved these changes

2022-01-25 10:09 UTC, irkhodzka approved these changes

2022-01-25 12:31 UTC, lucas-varela approved these changes

2022-01-25 12:37 UTC, merged