docs(bodiless-documentation): Redirect Aliases
johnsonandjohnson/Bodiless-JS pull request #1346
Opened 2022-01-21 07:08 UTC by misterjones

## Changes

- Add "Tools" section to "Content Editor Guide."
- Add "Tools Menu" page.
- Add "Redirect Aliases" page.
- Add screenshots.

## Related Issues

**Documents:**
- #1122 

---

Resolves #1345

2022-01-21 17:22 UTC, hvanyo commented on packages/bodiless-documentation/doc/ContentEditorUserGuide/ToolsMenu/Aliases/README.md
> +01. Refresh your edit environment.
```suggestion
01. Restart your edit environment.
```
base on your note right above troubleshooting.  Refresh doesn't solve the issue.

2022-01-21 17:22 UTC, hvanyo commented on packages/bodiless-documentation/doc/ContentEditorUserGuide/ToolsMenu/Aliases/README.md
> +  - For _removed_ redirect aliases to take effect, you must first restart your edit environment.
We don't have an ability to restart edit env.  So add a note that you must call your friendly developer and restart the edit environment.

2022-01-21 17:22 UTC, hvanyo commented on packages/bodiless-documentation/doc/ContentEditorUserGuide/ToolsMenu/Aliases/README.md
> +If you should accidentally create a redirect alias with the same URL for both the _From Path_ and
I think you should mention here as well "BodilessJS does not check for circular redirects and doesn't attempt to correct or provide a warning."

2022-01-21 17:22 UTC, hvanyo commented on packages/bodiless-documentation/doc/ContentEditorUserGuide/ToolsMenu/Aliases/README.md
> +/page-3/ /page-4/
I would add another warning:
If you are adding/editing redirects via this editor and get circular or multiple redirect errors, please be aware that you site might have redirects configured elsewhere.  The developers have opportunity to put redirects at platform configuration files or within the CDN.  No matter where the redirects are placed they all must work together and not duplicate/contradict each other.

2022-01-21 17:22 UTC, hvanyo commented on packages/bodiless-documentation/doc/ContentEditorUserGuide/ToolsMenu/Aliases/README.md
> +/page-3/ /page-4/
I would add another warning as well that there is no need for redirects of urls that differ with a trailing slash.  The platform should be handle a url without a trialing slash to url with a trailing automatically.

2022-01-21 18:09 UTC, Guilherme-Almeida-Zeni commented
Should we mention somewhere in the documentation that, by adding the redirects to the form, the redirect list is saved in the src/data/site/redirect-aliases.json file?

2022-01-21 18:11 UTC, Guilherme-Almeida-Zeni commented
Should we mention that it's possible to remove all redirects by saving the form empty?

2022-01-21 18:36 UTC, misterjones commented on packages/bodiless-documentation/doc/ContentEditorUserGuide/ToolsMenu/Aliases/README.md
> +01. Refresh your edit environment.
Whoops — definitely meant to say "Restart." Good catch.

Fixed. 👍 
Added note about contacting developer.

See: [Fix](https://github.com/johnsonandjohnson/Bodiless-JS/pull/1346/commits/e57ab8fc1d3114907d9b26c584590a1be560c2d1#diff-f8448c57a79c474ad52a150c2ee5d347dd7f13b395539f67a47f28f8c05e2847R91-R92)

2022-01-21 18:37 UTC, misterjones commented on packages/bodiless-documentation/doc/ContentEditorUserGuide/ToolsMenu/Aliases/README.md
> +  - For _removed_ redirect aliases to take effect, you must first restart your edit environment.
✅  [Updated](https://github.com/johnsonandjohnson/Bodiless-JS/pull/1346/commits/e57ab8fc1d3114907d9b26c584590a1be560c2d1#diff-f8448c57a79c474ad52a150c2ee5d347dd7f13b395539f67a47f28f8c05e2847R70).

2022-01-21 18:38 UTC, misterjones commented on packages/bodiless-documentation/doc/ContentEditorUserGuide/ToolsMenu/Aliases/README.md
> +If you should accidentally create a redirect alias with the same URL for both the _From Path_ and
✅  [Updated](https://github.com/johnsonandjohnson/Bodiless-JS/pull/1346/commits/e57ab8fc1d3114907d9b26c584590a1be560c2d1#diff-f8448c57a79c474ad52a150c2ee5d347dd7f13b395539f67a47f28f8c05e2847R100-R101).

2022-01-21 18:39 UTC, misterjones commented on packages/bodiless-documentation/doc/ContentEditorUserGuide/ToolsMenu/Aliases/README.md
> +/page-3/ /page-4/
✅  Added **Note** boxes:

- [Here](https://github.com/johnsonandjohnson/Bodiless-JS/pull/1346/commits/e57ab8fc1d3114907d9b26c584590a1be560c2d1#diff-f8448c57a79c474ad52a150c2ee5d347dd7f13b395539f67a47f28f8c05e2847R105-R111); and
- [Here](https://github.com/johnsonandjohnson/Bodiless-JS/pull/1346/commits/e57ab8fc1d3114907d9b26c584590a1be560c2d1#diff-f8448c57a79c474ad52a150c2ee5d347dd7f13b395539f67a47f28f8c05e2847R138-R144)

2022-01-21 18:40 UTC, misterjones commented on packages/bodiless-documentation/doc/ContentEditorUserGuide/ToolsMenu/Aliases/README.md
> +/page-3/ /page-4/
✅  [Updated](https://github.com/johnsonandjohnson/Bodiless-JS/pull/1346/commits/e57ab8fc1d3114907d9b26c584590a1be560c2d1#diff-f8448c57a79c474ad52a150c2ee5d347dd7f13b395539f67a47f28f8c05e2847R50-R55).

2022-01-21 18:43 UTC, misterjones commented
@Guilherme-Almeida-Zeni 

> Should we mention somewhere in the documentation that, by adding the redirects to the form, the redirect list is saved in the src/data/site/redirect-aliases.json file?

✅  [Updated](https://github.com/johnsonandjohnson/Bodiless-JS/pull/1346/commits/e57ab8fc1d3114907d9b26c584590a1be560c2d1#diff-f8448c57a79c474ad52a150c2ee5d347dd7f13b395539f67a47f28f8c05e2847R14-R17).

> Should we mention that it's possible to remove all redirects by saving the form empty?

✅  [Updated](https://github.com/johnsonandjohnson/Bodiless-JS/pull/1346/commits/e57ab8fc1d3114907d9b26c584590a1be560c2d1#diff-f8448c57a79c474ad52a150c2ee5d347dd7f13b395539f67a47f28f8c05e2847R48-R49).

2022-01-21 20:13 UTC, TatsianaMiraniuk commented on packages/bodiless-documentation/doc/ContentEditorUserGuide/ToolsMenu/Aliases/README.md
> +  - Added/Modified redirect aliases will take effect immediately after saving.
The behavior is not always true for 'Modified' rules.
 It is true for the latest version of a rule, but not always true for a previous version of the rule. A couple of examples how it works:
Step 1: the rules below are added as the completely new rules.
```
/page-a/ /page-b/ 301
/cards/ /list2/ 301
```
Works as expected:
```
/page-a/ redirects to /page-b/ 301
/cards/ redirects to /list2/ 301
```

Step 2: the rules modified - /page-b/ is replaced by /page-c/ and /cards/ is replaced by /anchor/
```
/page-a/ page-c/ 301
/anchor/ /list2/ 301
```

As Results the following redirect happens
```
/page-a/ -> /page-c/
/cards/ -> /list2/
/anchor/ ->  /list2/
```
 /cards/ -> /list2/ still happens. 
So the previous versions of a modified rule in such way are considered as 'removed' and the redirects will happen until the Edit env restarts.

2022-01-21 20:39 UTC, TatsianaMiraniuk requested changes

2022-01-21 20:39 UTC, TatsianaMiraniuk commented on packages/bodiless-documentation/doc/ContentEditorUserGuide/ToolsMenu/Aliases/README.md
> +?> **Note:** Redirects can be configured elsewhere.
@misterjones seems, ?> is a typo?

2022-01-21 20:39 UTC, TatsianaMiraniuk commented on packages/bodiless-documentation/doc/ContentEditorUserGuide/ToolsMenu/Aliases/README.md
> +?> **Note:** Redirects can be configured elsewhere.
@misterjones seems, ?> is a typo?

2022-01-21 20:39 UTC, TatsianaMiraniuk commented on packages/bodiless-documentation/doc/ContentEditorUserGuide/ToolsMenu/Aliases/README.md
> +Remove or correct the redirect alias causing the circular reference.
@misterjones should we remind here to restart the env after the changes?

2022-01-21 21:56 UTC, misterjones commented on packages/bodiless-documentation/doc/ContentEditorUserGuide/ToolsMenu/Aliases/README.md
> +?> **Note:** Redirects can be configured elsewhere.
@TatsianaMiraniuk, the `?>` is an extended syntax for markdown, provided by Docsify — [General tips](https://docsify.js.org/#/helpers?id=general-tips).

You can see, on the [Redirect Aliases](https://pr-1346-ie5iwwa-jvaff4bu65vgm.us-2.platformsh.site/___docs/#/ContentEditorUserGuide/ToolsMenu/Aliases/) page, that they render as info/note blocks. 😄

2022-01-21 21:56 UTC, misterjones commented on packages/bodiless-documentation/doc/ContentEditorUserGuide/ToolsMenu/Aliases/README.md
> +?> **Note:** Redirects can be configured elsewhere.
@TatsianaMiraniuk, the `?>` is an extended syntax for markdown, provided by Docsify — [General tips](https://docsify.js.org/#/helpers?id=general-tips).

You can see, on the [Redirect Aliases](https://pr-1346-ie5iwwa-jvaff4bu65vgm.us-2.platformsh.site/___docs/#/ContentEditorUserGuide/ToolsMenu/Aliases/) page, that they render as info/note blocks. 😄

2022-01-21 21:58 UTC, misterjones commented on packages/bodiless-documentation/doc/ContentEditorUserGuide/ToolsMenu/Aliases/README.md
> +  - Added/Modified redirect aliases will take effect immediately after saving.
@TatsianaMiraniuk, ah, interesting.

Thank you for the thorough explanation! 😄 

✅  [Updated](https://github.com/johnsonandjohnson/Bodiless-JS/pull/1346/commits/8d5e043ff148543a03c6ec52c218045f3c49129b#diff-f8448c57a79c474ad52a150c2ee5d347dd7f13b395539f67a47f28f8c05e2847R71-R81).

2022-01-21 21:59 UTC, misterjones commented on packages/bodiless-documentation/doc/ContentEditorUserGuide/ToolsMenu/Aliases/README.md
> +Remove or correct the redirect alias causing the circular reference.
@TatsianaMiraniuk, good call. 👍 

✅  [Updated](https://github.com/johnsonandjohnson/Bodiless-JS/pull/1346/commits/8d5e043ff148543a03c6ec52c218045f3c49129b#diff-f8448c57a79c474ad52a150c2ee5d347dd7f13b395539f67a47f28f8c05e2847R114-R116).

2022-01-24 14:18 UTC, Guilherme-Almeida-Zeni approved these changes

2022-01-24 15:08 UTC, misterjones commented on packages/bodiless-documentation/doc/ContentEditorUserGuide/ToolsMenu/Aliases/README.md
> +        - If you don't provide one at the beginning of your path, a leading forward slash (`/`) will
Hi @Guilherme-Almeida-Zeni, 

Yeah, wording on that was a bit clunky.
✅  [Fixed!](https://github.com/johnsonandjohnson/Bodiless-JS/pull/1346/commits/bbc6a6c094948b08b51049355ee0bb47796e4a7e#diff-f8448c57a79c474ad52a150c2ee5d347dd7f13b395539f67a47f28f8c05e2847R29-R30)

2022-01-24 15:09 UTC, misterjones commented on packages/bodiless-documentation/doc/ContentEditorUserGuide/ToolsMenu/Aliases/README.md
> +- Ensure that you only have _single_ spaces delimiting your values; double-whitespaces are invalid.
@Guilherme-Almeida-Zeni, 

Good call. 👍 
✅  [Added note](https://github.com/johnsonandjohnson/Bodiless-JS/pull/1346/commits/bbc6a6c094948b08b51049355ee0bb47796e4a7e#diff-f8448c57a79c474ad52a150c2ee5d347dd7f13b395539f67a47f28f8c05e2847R61-R63).

2022-01-24 15:18 UTC, Guilherme-Almeida-Zeni approved these changes

2022-01-24 15:19 UTC, hvanyo approved these changes

2022-01-24 17:02 UTC, TatsianaMiraniuk approved these changes

2022-01-25 13:19 UTC, merged