chore(*): Upgrade Dependencies and Refactor
johnsonandjohnson/Bodiless-JS pull request #1395
Opened 2022-02-17 16:05 UTC by wodenx

## Changes
- Add tokenSpec utilities to bodiless
- Move store, backend client and git operations to core from gatsby-theme-bodiless
- reorganize code in fclasses
- use npm workspaces instead of lerna for bootstrap
- Upgrade package dependencies

BREAKING CHANGE
- Renamed 'asToken' to 'flowHoc'
- renamed and repurposed token related types
- modified the type of any Design object to accept TokenSpecs and strings (will break any code which relies on their always being HOC's)

2022-03-07 14:15 UTC, Guilherme-Almeida-Zeni approved these changes

2022-03-07 15:22 UTC, TatsianaMiraniuk requested changes

2022-03-07 15:22 UTC, TatsianaMiraniuk commented on cypress/integration/smokeTest/cards_spec.js
> +    // cy.isImageVisible(imagePlaceholderXpath);
@Guilherme-Almeida-Zeni , why that checks are excluded? They are required to make sure that an image is uploaded/available.

2022-03-07 17:08 UTC, TatsianaMiraniuk requested changes

2022-03-08 14:16 UTC, Guilherme-Almeida-Zeni commented on .github/workflows/build-test-lint-simple.yml
> +        run: npm run test:monorepo
@TatsianaMiraniuk , 

As discussed on standup, we will not invest more time to fix the setup issues on standalone site.

2022-03-08 14:16 UTC, Guilherme-Almeida-Zeni commented on cypress/support/commands.js
> +// For more comprehensive sites of custom
@TatsianaMiraniuk ,

Reverted that. Please, check it again. Thanks!

2022-03-08 14:17 UTC, Guilherme-Almeida-Zeni commented on packages/bodiless-backend/__tests__/fixtures/git/get-conflicts/hooks/prepare-commit-msg.sample
> +# This hook includes three sites. The first one removes the
@TatsianaMiraniuk ,

Reverted that. Please, check it again. Thanks!

2022-03-08 14:17 UTC, Guilherme-Almeida-Zeni commented on packages/bodiless-core-ui/src/LocalContextMenu.tsx
> +// For accessibility attributes, see https://www.w3.org/TR/wai-aria-practices/sites/toolbar/toolbar.html
@TatsianaMiraniuk ,

Reverted that. Please, check it again. Thanks!

2022-03-08 18:21 UTC, TatsianaMiraniuk approved these changes

2022-03-08 18:28 UTC, Guilherme-Almeida-Zeni approved these changes

2022-03-08 18:34 UTC, merged