chore(page-data-provider): Refactor Page Data Provider
johnsonandjohnson/Bodiless-JS pull request #1397
Opened 2022-02-17 19:19 UTC by Guilherme-Almeida-Zeni

## Changes

## Test Instructions

## Related Issues

2022-02-22 16:59 UTC, wodenx requested changes

2022-02-22 16:59 UTC, wodenx commented on packages/gatsby-theme-bodiless/src/dist/GatsbyPageProvider.tsx
> -import type { GitContextProps } from '@bodiless/core';
Why do we still need the GatsbyPageProvider?  I would get rid of it and just use thePageDataProvider, and add a pagePath (which is the same as the slug) to it.

2022-02-22 17:55 UTC, lucas-varela approved these changes

2022-02-23 04:46 UTC, Guilherme-Almeida-Zeni commented on packages/bodiless-components/src/index.ts
> -export * from './RedirectAlias';
@wodenx ,

The RedirectAlias directory has been moved to page package, so in this PR it doesn't exist anymore in bodiless component.

2022-02-23 04:47 UTC, Guilherme-Almeida-Zeni commented on packages/gatsby-theme-bodiless/src/dist/GatsbyPageProvider.tsx
> -import type { GitContextProps } from '@bodiless/core';
@wodenx ,

We actually don't. I removed it. Please, check it again. Thanks!

2022-02-23 09:13 UTC, wodenx approved these changes

2022-02-23 11:50 UTC, merged