Standard module resolution
johnsonandjohnson/Bodiless-JS pull request #1439
Opened 2022-03-09 12:21 UTC by konst8

## Changes
Change autodiscovery approach for:
- tailwind configs
- docs
- environment variables configs

## Related Issues
https://github.com/johnsonandjohnson/Bodiless-JS/issues/1277

2022-03-11 10:58 UTC, wodenx commented on packages/__cxstarter__/src/getBodilessDocConfig.ts
> +import { getPackageDocConfig } from '@bodiless/cli/lib/helpers/getPackageDocConfig';
Why can't se export this rom the package?

2022-03-11 11:00 UTC, wodenx commented on packages/__cxstarter__/src/getBodilessDocConfig.ts
> +);
We should add a getBodilessTwConfigs export to this package also.

2022-03-11 11:05 UTC, wodenx commented on packages/bodiless-accordion/src/getBodilessDocConfig.ts
> +import path from 'path';
Please make sure all files have copyright header. (npm run copyright at root should do it).

2022-03-11 11:08 UTC, wodenx commented on packages/bodiless-backend/package.json
> +    "bodiless-dev-backend": "./bin/bodiless-dev-backend"
i think we can call this just `bodiless-backend`

2022-03-11 11:13 UTC, wodenx commented on packages/bodiless-cli/bin/generate-env-vars
> +#!/usr/bin/env node
can we make this an actual oclif command rather than an additional script?

2022-03-11 11:14 UTC, wodenx commented on packages/bodiless-cli/package-lock.json
> +{
This file is extraneous, no?

2022-03-11 11:14 UTC, wodenx commented on packages/bodiless-cli/package.json
> +    "generate-env-vars": "./bin/generate-env-vars"
See above - can we make this a bodiless/cli command?

2022-03-11 11:42 UTC, wodenx commented on packages/bodiless-cli/src/helpers/getPackageDocConfig.ts
> +        const depDocsJsonPath = require(path.join(dep, 'lib/getBodilessDocConfig'))
can we require this directly from the package instead of requiring from 'lib'?

2022-03-11 15:08 UTC, wodenx commented on sites/test-site/tailwind.config.js
> +const accordionConfig = require('../../packages/bodiless-accordion/site.tailwind.config');
we should comment this out, no?

2022-03-11 15:09 UTC, wodenx commented on sites/test-site/tailwind.config.js
> +const requireEsm = require('esm')(module);
We need to add this to starter too.

2022-03-11 15:12 UTC, wodenx commented on sites/test-site/tailwind.config.js
> +const requireEsm = require('esm')(module);
probably tp packages/starter too -- that's where we should manage the preceence.  The site level one should jstart with that one.  ie - at site level we should just be able to do
```
const { getTailwindConfig } = require('@bodiless/__cxstarter__');
module.exports = getTailwindConfig();

2022-03-18 10:58 UTC, konst8 commented on packages/__cxstarter__/src/getBodilessDocConfig.ts
> +import { getPackageDocConfig } from '@bodiless/cli/lib/helpers/getPackageDocConfig';
It works for some packages, e.g. for card:
`require('@bodiless/card').twConfig`
but for others it returns error:
`require('@bodiless/accordion').twConfig`
will throw
```js
/Users/km/jj/BJS-module-resolution/packages/bodiless-components/lib/Editable.css:15
.bodiless-inline-editable[contenteditable=true]:empty:before {
```

2022-03-18 10:59 UTC, konst8 commented on packages/__cxstarter__/src/getBodilessDocConfig.ts
> +);
Done, as well as for other cx packages

2022-03-18 11:00 UTC, konst8 commented on packages/bodiless-accordion/src/getBodilessDocConfig.ts
> +import path from 'path';
Done.

2022-03-18 11:01 UTC, konst8 commented on packages/bodiless-backend/package.json
> +    "bodiless-dev-backend": "./bin/bodiless-dev-backend"
Done.

2022-03-18 11:01 UTC, konst8 commented on packages/bodiless-cli/bin/generate-env-vars
> +#!/usr/bin/env node
Done.

2022-03-18 11:01 UTC, konst8 commented on packages/bodiless-cli/package-lock.json
> +{
Removed.

2022-03-18 11:02 UTC, konst8 commented on packages/bodiless-cli/package.json
> +    "generate-env-vars": "./bin/generate-env-vars"
Done.

2022-03-18 11:04 UTC, konst8 commented on packages/__cxstarter__/src/getBodilessDocConfig.ts
> +import { getPackageDocConfig } from '@bodiless/cli/lib/helpers/getPackageDocConfig';
Discussed offline. Will need to export everything explicitly, including tarball of the docs.

2022-03-18 11:04 UTC, konst8 commented on packages/bodiless-cli/src/helpers/getPackageDocConfig.ts
> +        const depDocsJsonPath = require(path.join(dep, 'lib/getBodilessDocConfig'))
It works for some packages, e.g. for card:
`require('@bodiless/card').twConfig`
but for others it returns error:
`require('@bodiless/accordion').twConfig`
will throw
```js
/Users/km/jj/BJS-module-resolution/packages/bodiless-components/lib/Editable.css:15
.bodiless-inline-editable[contenteditable=true]:empty:before {
```

2022-03-18 11:06 UTC, konst8 commented on sites/test-site/tailwind.config.js
> +const accordionConfig = require('../../packages/bodiless-accordion/site.tailwind.config');
Done.

2022-03-18 11:07 UTC, konst8 commented on sites/test-site/tailwind.config.js
> +const requireEsm = require('esm')(module);
Done.

2022-03-21 02:53 UTC, wodenx requested changes

2022-03-21 02:53 UTC, wodenx commented on sites/__cxstarter__/tailwind.config.js
> +  options: {
This doesn't match the doc - nd i think it's better to lift these options up to mtch the doc

2022-03-21 02:53 UTC, wodenx commented on sites/__cxstarter__/tailwind.config.js
> +const getTwConfig = () => getPackageTailwindConfig({
Why do we make this a function?  why not simply

module.exports = mergeConfigs({}, getPackageTailwindConfigs({ ... }))

pr - better - is there anyreason mergeConfigs can't hve th seme signature as getPackgeTailwindConfigs, so we just do

module.exports = mergeConfigs({ ... });

(maybe rename it 'buildTailwindConfig' or something.

2022-03-21 02:53 UTC, wodenx commented on sites/__cxstarter__/tailwind.config.js
> +const getTwConfig = () => getPackageTailwindConfig({
Also - since this is a templte package, I think it would be clearer if we removed the tw config we won't have any site level), nd inlined lll the options - so something like:
```
modules.exports = buildTailwindConfig({
  pkgJson: require('./package.json'),
  resolver: pkg => require('esm')(module)(pkg),
  prefer: [...],
  exclude: [...],
});
```

2022-03-21 02:53 UTC, wodenx commented on sites/__cxstarter__/tailwind.config.js
> +const getTwConfig = () => getPackageTailwindConfig({
note - no twConfig in the above since sites won't generally have one.

2022-03-21 02:53 UTC, wodenx commented on packages/fclasses/src/tailwindcss/getPackageTailwindConfig.ts
> +      ...pkgJson.devDependencies,
I"m thinking maybe we shoudl not include devDependencies.

2022-03-21 02:53 UTC, wodenx commented on packages/fclasses/src/tailwindcss/getPackageTailwindConfig.ts
> +          const nextConfig = resolver(join(next, 'lib/getTwConfig')).getTwConfig();
Why do we import this from tht path directly rather than allowing pckages to export this function normally?  ie can we not do:
```
const nextConfig = resolver(next).getTwConfig()
```

2022-03-21 02:53 UTC, wodenx commented on packages/fclasses/src/tailwindcss/getPackageTailwindConfig.ts
> +          const nextConfig = resolver(join(next, 'lib/getTwConfig')).getTwConfig();
if that's not possible, then i think it' spreferble just to put getTwConfig.js at package root (in js) using cjs exports:

const twConfig = { ... };
module.exports.= () => getPackageTailwindConfig({
  twConfig,
  pkgJson: require('./packge.json'),
   resolver: p => require(p),
 ...
 });
```

2022-03-21 16:41 UTC, konst8 commented on packages/fclasses/src/tailwindcss/getPackageTailwindConfig.ts
> +      ...pkgJson.devDependencies,
Done.

2022-03-21 16:42 UTC, konst8 commented on packages/fclasses/src/tailwindcss/getPackageTailwindConfig.ts
> +    options?: ExtraOptions
Done.

2022-03-22 00:24 UTC, konst8 commented on sites/__cxstarter__/tailwind.config.js
> +const getTwConfig = () => getPackageTailwindConfig({
Done.

2022-03-22 11:43 UTC, wodenx commented on sites/__cxstarter__/tailwind.config.js
> +  prefer: ['@sites/__cxstarter__', '@bodiless/__cxstarter__'],
We don't need @sites/__cxstarter__ here anymore right?  There is no site level tw config...

2022-03-22 11:52 UTC, wodenx commented on sites/__cxstarter__/tailwind.config.js
> +  prefer: ['@sites/__cxstarter__', '@bodiless/__cxstarter__'],
```suggestion
  prefer: ['@bodiless/__cxstarter__'],
```

2022-03-23 11:13 UTC, wodenx submitted a review, later dismissed

2022-03-25 13:07 UTC, wodenx commented on packages/bodiless-accessibility/package.json
> -    "build": "tsc -p ./tsconfig.json",
why are we removing this?

2022-03-25 13:12 UTC, wodenx approved these changes

2022-04-04 23:16 UTC, hvanyo commented on packages/cx-editors/getTwConfig.js
> +/* eslint-disable import/no-dynamic-require, global-require */
@konst8  @wodenx 

If I was dev familiar with tailwind I would be looking for tailwind.config.js -- and not find it and find a new file called X.tailwind.config.js and logically conclude without reading docs -- and think Oh i bet this is some custom version..   Using name: getTwConfig.js -- abbreviates Tw to something that may or may not be obviously tailwind.

i.e. https://tailwindcss.com/docs/installation -> tailwind.config.js

@wodenx  mentions that In fact we can just make it tailwind.config.js.

Could you make this change @konst8

2022-04-04 23:19 UTC, hvanyo commented on packages/bodiless-ui/package.json
> +    "@bodiless/cli": "^1.0.0-beta.1",
@konst8  why didn't this tailwind get renamed?
https://github.com/johnsonandjohnson/Bodiless-JS/blob/main/packages/bodiless-ui/bodiless.tailwind.config.js

2022-04-05 07:28 UTC, konst8 commented on packages/cx-editors/getTwConfig.js
> +/* eslint-disable import/no-dynamic-require, global-require */
Ok, sure

2022-04-06 10:32 UTC, konst8 commented on packages/bodiless-ui/package.json
> +    "@bodiless/cli": "^1.0.0-beta.1",
I think this package is specific and its tw config is used only by edit ui.
https://github.com/johnsonandjohnson/Bodiless-JS/blob/main/packages/bodiless-ui/postcss.config.js#L18
We probably don't wan't to merge it into the site config.

2022-04-06 11:57 UTC, wodenx commented on packages/bodiless-ui/package.json
> +    "@bodiless/cli": "^1.0.0-beta.1",
agree with @konst8  - that is used for admin css and should not be changed.

2022-04-06 13:35 UTC, wodenx submitted a review, later dismissed

2022-04-08 14:47 UTC, ValeryRudko approved these changes

2022-04-08 14:49 UTC, ValeryRudko approved these changes
Checked from testing view. It is fine.

2022-04-08 16:55 UTC, hvanyo approved these changes

2022-04-08 17:09 UTC, merged