Migration from cypress to playwright
johnsonandjohnson/Bodiless-JS pull request #1487
Opened 2022-03-25 14:42 UTC by pomi

## Changes
Cypress test cases were migrated to playwright

2022-03-30 04:01 UTC, TatsianaMiraniuk requested changes
@pomi,  Maxim, please revisit the changes and make the corrections before I continue the review. Global issues to fix:
1) inconsistency in initializing/setting the variables - some of them inside of the page object files, some of them inside the test files, some of them duplicated in one file, the same element selector is initialized/set twice in different files(e.g. editIcon is set in base-page.ts, however the same is done in file-submenu-page.ts ); some the same variables are set by different names (e.g. pageIconXpath, pageIcon)
2) as discussed before, you **have to copy** all variables/their values from the existing Cypress tests. If a new element locator is needed by some reason, please use the same format, e.g. see that issue in singleAccordion.spec.ts
_const titleFirstXpath = '#accordion-4 div[data-accordion-element="accordion-title"] div[data-slate-editor="true"]';_
vs.
_const plusIconFirstXpath = '//*[@id="accordion-4"]//*[@data-accordion-icon="expand"]';_
3) please delete the repeated/not needed comments like // eslint-disable-next-line jest/expect-expect and others similar
4) set the viewport sizes on global level as it's done in Cypress - https://github.com/johnsonandjohnson/Bodiless-JS/blob/main/cypress.json. Right now, it's on test level
5) please reconfirm that _the consequence of steps and tests_ made in Cypress are reflected in Playwright, e.g. see in singleAccordion.spec.ts. The expectation is that all tests are 1-1 identical in that sense. 
6) page object model is not used for Cards, Single Accordion tests 
7) see other comments inside the files

2022-04-11 18:43 UTC, TatsianaMiraniuk commented
> 3\. eslint-disable-next-line

@pomi, please make sure you review all comments and reply to each as a confirmation of a fix for easy tracking.  Most comments are still valid...
1. still an issue
2. still an issue
3. still an issue
4. still an issue (e.d linkToggle test)
5. still an issue. Additionally there are 4 files(?) for Cards- the tests should be reflecting the existing tests. Please confirm that all tests do the same steps.
6. --
7. --
8. still an issue.

2022-04-11 18:45 UTC, TatsianaMiraniuk requested changes

2022-04-11 18:45 UTC, TatsianaMiraniuk commented on playwright/pages/accordion-page.ts
> +    this.titleFirstXpath = '#accordion-4 div[data-accordion-element="accordion-title"] div[data-slate-editor="true"]';
@pomi xpaths are still in different format

2022-04-11 18:45 UTC, TatsianaMiraniuk commented on playwright/pages/editor-menu-page.ts
> +    this.menuBarLeft = '//*[@aria-label="Global Context Menu Left"]';
@pomi , please see ^^

2022-04-11 18:45 UTC, TatsianaMiraniuk commented on playwright/tests/smoke/linkToggle.spec.ts
> +    page = await browser.newPage({ viewport: { width: 1200, height: 850 } });
@pomi  ^^

2022-04-11 18:45 UTC, TatsianaMiraniuk commented on playwright/tests/smoke/singleAccordion.spec.ts
> +    await typeText(page, accordionPage.bodyFirstXpath, accordionPage.body, accordionPage.accordionBodyRequest);
@pomi please keep the same consequence of steps as it's done in Cypress tests.

2022-04-14 13:29 UTC, pomi commented on playwright/tests/smoke/linkToggle.spec.ts
> +    page = await browser.newPage({ viewport: { width: 1200, height: 850 } });
Fixed

2022-04-14 13:29 UTC, pomi commented on playwright/pages/link-toggle-page.ts
> +  readonly label = 'AT - Label -';
Fixed

2022-04-14 13:29 UTC, pomi commented on playwright/tests/smoke/pdp.spec.ts
> +const editIcon = '//*[@aria-label="Edit"]';
Fixed

2022-04-20 10:07 UTC, pomi commented on playwright/tests/smoke/singleAccordion.spec.ts
> +    await typeText(page, accordionPage.bodyFirstXpath, accordionPage.body, accordionPage.accordionBodyRequest);
Done

2022-04-20 10:08 UTC, pomi commented on playwright/pages/accordion-page.ts
> +    this.titleFirstXpath = '#accordion-4 div[data-accordion-element="accordion-title"] div[data-slate-editor="true"]';
Done

2022-04-20 10:08 UTC, pomi commented on playwright/pages/flow-container-page.ts
> +/**
done

2022-04-20 10:08 UTC, pomi commented on playwright/tests/smoke/cards3.spec.ts
> +/**
done

2022-04-20 10:44 UTC, pomi commented on playwright/tests/smoke/singleAccordion.spec.ts
> +const title = 'AT-Title1';
Done

2022-04-20 10:45 UTC, pomi commented on playwright/tests/smoke/singleAccordion.spec.ts
> +const titleFirstXpath = '#accordion-4 div[data-accordion-element="accordion-title"] div[data-slate-editor="true"]';
Done

2022-04-20 10:45 UTC, pomi commented on playwright/tests/smoke/pdp.spec.ts
> +    page = await browser.newPage({ viewport: { width: 1200, height: 850 } });
Done

2022-04-20 10:45 UTC, pomi commented on playwright/tests/smoke/pdp.spec.ts
> +async function typeText(page:Page, locator:string, text:string, request:string, confirmButton?:string) {
Done

2022-04-20 10:45 UTC, pomi commented on playwright/tests/smoke/singleAccordion.spec.ts
> +async function typeText(page: Page, locator:string, text:string, request:string) {
Done

2022-04-20 10:45 UTC, pomi commented on playwright/pages/file-submenu-page.ts
> +    // eslint-disable-next-line jest/no-standalone-expect
Done

2022-04-20 10:45 UTC, pomi commented on playwright/tests/smoke/editorMenu.spec.ts
> +  test('editorMenu: 4 - checking Switcher button in Edit Mode (left and right)', async () => {
Done

2022-04-20 10:45 UTC, pomi commented on playwright/pages/editor-menu-page.ts
> +  async checkEditorMenuButtonsPreviewMode() {
Done

2022-04-20 12:11 UTC, konst8 commented on playwright/pages/editor-menu-page.ts
> +    this.menuBarLeft = '//*[@aria-label="Global Context Menu Left"]';
Looks done.

2022-04-20 12:16 UTC, konst8 approved these changes

2022-04-20 12:59 UTC, konst8 submitted a review, later dismissed

2022-04-22 14:04 UTC, TatsianaMiraniuk requested changes

2022-04-22 21:28 UTC, TatsianaMiraniuk requested changes

2022-04-22 21:28 UTC, TatsianaMiraniuk commented on playwright/tests/smoke/editorMenu.spec.ts
> +    const editorMenuPage = new EditorMenuPage(page);
@pomi  is this needed? available at line 51

2022-04-22 21:28 UTC, TatsianaMiraniuk commented on playwright/tests/smoke/editorMenu.spec.ts
> +    expect(newPage.url()).toEqual('http://localhost:8005/___docs/');
@pomi , 
1) shouldn't be hardcoded. please use baseURL instead http://localhost:8005
2) does this step pass? when we manually click Docs, we land on  /___docs/#/

2022-04-22 21:28 UTC, TatsianaMiraniuk commented on playwright/tests/smoke/editorMenu.spec.ts
> +  });
@pomi one check is missed here - https://github.com/johnsonandjohnson/Bodiless-JS/blob/030068ae0cb3bf8f8e2049f025720f29f0c999c9/cypress/integration/smokeTest/editorMenu_spec.js#L99

2022-04-22 21:28 UTC, TatsianaMiraniuk commented on playwright/tests/smoke/editorMenu.spec.ts
> +async function checkSwitcherAndMenuIcons(page: Page, editorMenuPage: EditorMenuPage) {
@pomi , looks like it's not used anywhere..

2022-04-22 21:28 UTC, TatsianaMiraniuk commented on playwright/tests/smoke/linkToggle.spec.ts
> +    page = await browser.newPage({ viewport: { width: 1200, height: 850 } });
@pomi still here ^^

2022-04-25 21:41 UTC, TatsianaMiraniuk requested changes

2022-04-25 21:41 UTC, TatsianaMiraniuk commented on playwright/tests/smoke/fileSubmenu.spec.ts
> +    page.waitForSelector('#global-tooltip-container > div > div > div > div > div.rc-tooltip-inner'),
@pomi 
1) shouldn't a step below be enough? (await until Latest Commits is visible)?
2) if this step is really necessary, please update the locator

2022-04-25 21:41 UTC, TatsianaMiraniuk commented on playwright/pages/cards-page.ts
> +    this.imagesFolderPath = './playwright/images/';
@pomi , that and two vars below are available in Base PO. please reuse accordingly

2022-04-25 21:41 UTC, TatsianaMiraniuk commented on playwright/tests/smoke/cards.spec.ts
> +    await page.goto('/cards');
@pomi , please add a trailing slash

2022-04-25 21:41 UTC, TatsianaMiraniuk commented on playwright/tests/smoke/cards.spec.ts
> +import card from '../../../sites/test-site/src/components/Card';
@pomi looks like it's redundant

2022-04-26 12:02 UTC, pomi commented on playwright/tests/smoke/singleAccordion.spec.ts
> +    await page.goto('/accordion');
Done

2022-04-26 12:05 UTC, pomi commented on playwright/pages/pdp-page.ts
> +    this.title = 'AT - PDD title';
Done

2022-04-26 12:06 UTC, pomi commented on playwright/pages/pdp-page.ts
> +  readonly imageName: string;
Done

2022-04-26 12:06 UTC, pomi commented on playwright/pages/pdp-page.ts
> +  readonly productRegexp: string;
Done

2022-04-26 12:08 UTC, pomi commented on playwright/tests/smoke/editorMenu.spec.ts
> +    // { viewport: { width: 1200, height: 850 } }
Done

2022-04-26 12:10 UTC, pomi commented on playwright/tests/smoke/fileSubmenu.spec.ts
> +test.describe('Editor Menu (left and right)', () => {
<img width="677" alt="image" src="https://user-images.githubusercontent.com/1829809/165296913-e3860d5c-31dc-4e24-9424-eaeda1f1c2cc.png">
Done

2022-04-26 12:13 UTC, pomi commented on playwright/pages/base-page.ts
> +    this.checkmarkIconAddPageForm = '//*[@aria-label="Context Submenu Form"]//*[@aria-label="Submit"]';
According to comments:
   // 'Cypress does not and may never have multi-tab support' - a quote from Cypress documentation
   //  Docs icon that opens Docs app in a new tab cannot be fully tested within the current implementation
   //  Adding a test that directly checks Docs app Home page, without clicking on Docs icon

But if you want, I will add it

2022-04-26 12:13 UTC, pomi commented on playwright/pages/base-page.ts
> +    this.checkmarkIconAddPageForm = '//*[@aria-label="Context Submenu Form"]//*[@aria-label="Submit"]';
Test is using playwright multi-tab support functionality, btw

2022-04-26 12:19 UTC, pomi commented on playwright/pages/base-page.ts
> +  readonly submitButton: string;
Done

2022-04-26 12:19 UTC, pomi commented on playwright/pages/base-page.ts
> +    this.submitButton = 'button[aria-label="Submit"]';
Done

2022-04-26 12:57 UTC, pomi commented on playwright/tests/smoke/editorMenu.spec.ts
> +    expect(newPage.url()).toEqual('http://localhost:8005/___docs/');
Yes, it will pass

2022-04-26 12:57 UTC, pomi commented on playwright/tests/smoke/editorMenu.spec.ts
> +async function checkSwitcherAndMenuIcons(page: Page, editorMenuPage: EditorMenuPage) {
Done

2022-04-26 12:58 UTC, pomi commented on playwright/tests/smoke/cards.spec.ts
> +import card from '../../../sites/test-site/src/components/Card';
Done

2022-04-26 12:58 UTC, pomi commented on playwright/tests/smoke/cards.spec.ts
> +    await page.goto('/cards');
Done

2022-04-26 13:10 UTC, pomi commented on playwright/tests/smoke/fileSubmenu.spec.ts
> +    page.waitForSelector('#global-tooltip-container > div > div > div > div > div.rc-tooltip-inner'),
Done

2022-04-26 13:52 UTC, pomi commented on playwright/pages/pdp-page.ts
> +    this.imagesFolderPath = './cypress/fixtures/images/';
done

2022-04-26 13:52 UTC, pomi commented on playwright/tests/smoke/editorMenu.spec.ts
> +    await checkEditorMenuButtons(page, editorMenuPage);
done

2022-04-26 13:52 UTC, pomi commented on playwright/pages/cards-page.ts
> +    this.imagesFolderPath = './playwright/images/';
done

2022-04-26 13:53 UTC, pomi commented on playwright/tests/smoke/editorMenu.spec.ts
> +  });
it's not missed, its rewritten

2022-04-26 13:53 UTC, pomi commented on playwright/pages/pdp-page.ts
> +  readonly productBase: string;
done

2022-04-26 13:54 UTC, pomi commented on playwright/pages/pdp-page.ts
> +  readonly imageOneName: string;
done

2022-04-26 13:54 UTC, pomi commented on playwright/pages/accordion-page.ts
> +    this.body = 'AT-Description1';
Done

2022-04-29 17:30 UTC, TatsianaMiraniuk requested changes

2022-04-29 17:30 UTC, TatsianaMiraniuk commented on playwright.config.ts
> +      name: 'firefox',
@pomi please add 'viewport: { width: 1200, height: 850 }' to firefox and webkit

2022-04-29 17:30 UTC, TatsianaMiraniuk commented on playwright.config.ts
> +    viewport: { width: 1200, height: 850 },
@pomi if it's not working globally, please remove - otherwise it's confusing

2022-04-29 17:33 UTC, TatsianaMiraniuk commented
@pomi ,

please do a correction in Accordion test files and playwright.config.ts, and then they can be separated (including other config files) in a different PR as discussed.  Add me as a reviewer to that new PR.


cc: @wodenx @hvanyo

2022-04-29 22:20 UTC, TatsianaMiraniuk requested changes

2022-04-29 22:20 UTC, TatsianaMiraniuk commented on playwright/tests/smoke/fileSubmenu.spec.ts
> +  expect(historyItems.length).toBeGreaterThan(3);
@pomi I ran that test 5 times and each time it fails here but randomly on different tests - on test 3; on test 3 and 8, on 2 and 5, on test 8.  please recheck
![Screen Shot 2022-04-29 at 6 19 06 PM](https://user-images.githubusercontent.com/3224040/166075935-93945f26-166c-404f-88a9-12f6fa77e92c.png)
![Screen Shot 2022-04-29 at 6 18 05 PM](https://user-images.githubusercontent.com/3224040/166075938-1a6007a9-0196-45a5-8f3f-454fe38789cb.png)
![Screen Shot 2022-04-29 at 6 01 43 PM](https://user-images.githubusercontent.com/3224040/166075940-032f6c66-05bf-415a-94df-32d3f0da6957.png)
![Screen Shot 2022-04-29 at 6 01 12 PM](https://user-images.githubusercontent.com/3224040/166075945-b427a837-17f1-4082-a749-b9d2dcb8f609.png)

2022-05-03 15:06 UTC, TatsianaMiraniuk requested changes

2022-05-10 12:53 UTC, pomi commented on playwright/tests/smoke/pdp.spec.ts
> +    expect.soft(await page.locator(pdpPage.accordionOverviewBodyXpath).innerText()).toEqual(pdpPage.accordionBody);
Line 45

2022-05-11 12:22 UTC, pomi commented on playwright/tests/smoke/editorMenu.spec.ts
> +test.describe('File Submenu Smoke Tests', () => {
Fixed

2022-05-11 12:23 UTC, pomi commented on playwright/tests/smoke/fileSubmenu.spec.ts
> +  });
Fixed

2022-05-11 12:23 UTC, pomi commented on playwright/tests/smoke/fileSubmenu.spec.ts
> +    await fileSubmenuPage.toggleEditMode();
Fixed

2022-05-11 12:24 UTC, pomi commented on playwright.config.ts
> +    viewport: { width: 1200, height: 850 },
Fixed

2022-05-11 12:24 UTC, pomi commented on playwright/pages/link-toggle-page.ts
> +  readonly editButton: string;
Fixed

2022-05-11 12:24 UTC, pomi commented on playwright/tests/smoke/fileSubmenu.spec.ts
> +  expect(historyItems.length).toBeGreaterThan(3);
Works stable

2022-05-11 12:24 UTC, pomi commented on playwright/tests/smoke/pdp.spec.ts
> +    // Test is failed here
fixed

2022-05-11 12:25 UTC, pomi commented on playwright/tests/smoke/pdp.spec.ts
> +    expect.soft(await page.locator(pdpPage.accordionOverviewBodyXpath).innerText()).toEqual(pdpPage.accordionBody);
Fixed

2022-05-11 12:25 UTC, pomi commented on playwright/tests/smoke/cards.spec.ts
> +    expect(page.url()).toContain(cardsPage.normalizedUrl + cardsPage.editedPostfix);
Fixed

2022-05-11 12:25 UTC, pomi commented on playwright/tests/smoke/pdp.spec.ts
> +    expect.soft(page.url()).toContain(pdpPage.pdpPagePath);
Fixed

2022-05-11 12:25 UTC, pomi commented on playwright/tests/smoke/pdp.spec.ts
> +test.describe('PDP smoke tests', () => {
Fixed

2022-05-11 12:25 UTC, pomi commented on playwright/pages/cards-page.ts
> +    this.imageNameOriginal = 'img_615x500.jpg';
Fixed

2022-05-11 12:26 UTC, pomi commented on playwright.config.ts
> +      name: 'firefox',
Fixed

2022-05-11 12:26 UTC, pomi commented on playwright/pages/accordion-page.ts
> +    this.title = 'AT - Title 1';
Fixed

2022-05-11 12:26 UTC, pomi commented on playwright/tests/smoke/fileSubmenu.spec.ts
> +    await fileSubmenuPage.toggleEditMode();
Fixed

2022-05-11 12:26 UTC, pomi commented on playwright/tests/smoke/editorMenu.spec.ts
> +    expect(newPage.url()).toEqual('http://localhost:8005/___docs/');
Fixed

2022-05-11 12:27 UTC, pomi commented on playwright/tests/smoke/fileSubmenu.spec.ts
> +test.describe('Editor Menu (left and right)', () => {
Fixed

2022-05-11 12:27 UTC, pomi commented on playwright/pages/base-page.ts
> +    this.checkmarkIconAddPageForm = '//*[@aria-label="Context Submenu Form"]//*[@aria-label="Submit"]';
Fixed

2022-05-11 12:27 UTC, pomi commented on playwright/pages/pdp-page.ts
> +  readonly imageName: string;
Fixed

2022-05-11 12:27 UTC, pomi commented on playwright/tests/smoke/editorMenu.spec.ts
> +  });
fixed

2022-05-11 12:28 UTC, pomi commented on playwright/tests/smoke/fileSubmenu.spec.ts
> +    await page.click(fileSubmenuPage.fileFormCloseButton);
fixed

2022-05-11 12:28 UTC, pomi commented on playwright/tests/smoke/fileSubmenu.spec.ts
> +    await page.click(fileSubmenuPage.fileFormButton);
Fixed

2022-05-11 12:28 UTC, pomi commented on playwright/tests/smoke/fileSubmenu.spec.ts
> +    await fileSubmenuPage.toggleEditMode();
fixed

2022-05-11 12:28 UTC, pomi commented on playwright/tests/smoke/fileSubmenu.spec.ts
> +    await page.click(fileSubmenuPage.fileFormCloseButton);
Fixed

2022-05-11 12:28 UTC, pomi commented on playwright/tests/smoke/fileSubmenu.spec.ts
> +    await fileSubmenuPage.toggleEditMode();
Fixed

2022-05-11 12:28 UTC, pomi commented on playwright/tests/smoke/fileSubmenu.spec.ts
> +    await page.click(fileSubmenuPage.fileFormButton);
Fixed

2022-05-11 12:28 UTC, pomi commented on playwright/tests/smoke/fileSubmenu.spec.ts
> +    await fileSubmenuPage.toggleMenuRight();
Fixed

2022-05-11 12:28 UTC, pomi commented on playwright/tests/smoke/cards.spec.ts
> +    expect(await page.locator(cardsPage.imageLinkXpath).getAttribute('href')).toContain(cardsPage.normalizedUrl + cardsPage.editedPostfix);
Fixed

2022-05-11 12:29 UTC, pomi commented on playwright/tests/smoke/cards.spec.ts
> +    // expect(await page.locator(cardsPage.imagePlaceholderXpath).getAttribute('alt')).toEqual(cardsPage.imageAltText);
Fixed

2022-05-11 12:29 UTC, pomi commented on playwright/tests/smoke/cards.spec.ts
> +    const imageDimensions = await page.locator(cardsPage.imagePlaceholderXpath).boundingBox();
fixed

2022-05-11 12:29 UTC, pomi commented on playwright/tests/smoke/linkToggle.spec.ts
> +    page = await browser.newPage({ viewport: { width: 1200, height: 850 } });
Fixed

2022-05-11 19:37 UTC, TatsianaMiraniuk requested changes

2022-05-11 19:37 UTC, TatsianaMiraniuk commented on playwright/tests/smoke/cards.spec.ts
> +    await page.setInputFiles('input[type=file]', cardsPage.pathToImages + cardsPage.imageNameOriginal);
@pomi ,

the vars need to be updated accordingly - Test Fails

2022-05-11 19:37 UTC, TatsianaMiraniuk commented on playwright/tests/smoke/singleAccordion.spec.ts
> +    await page.locator(accordionPage.plusIconFirstXpath).click();
@pomi ,

that workaround has to be deleted since the spaces were deleted - Test Fails

2022-05-17 11:44 UTC, pomi commented on playwright/pages/base-page.ts
> +    this.commitHistoryPanel = 'div[class="rc-tooltip-inner"]';
There is no distinctive way to separate these two panels

2022-05-17 13:01 UTC, pomi commented on playwright/tests/smoke/cards.spec.ts
> +    expect(await page.locator(cardsPage.imageLinkXpath).getAttribute('href')).toContain(cardsPage.normalizedUrl + cardsPage.editedPostfix);
Resolved

2022-05-17 13:01 UTC, pomi commented on playwright/tests/smoke/cards.spec.ts
> +    expect(await page.locator(cardsPage.imagePlaceholderXpath).getAttribute('alt')).toEqual(cardsPage.imageAltText);
Resolved

2022-05-17 13:02 UTC, pomi commented on playwright/tests/smoke/cards.spec.ts
>        page.click(cardsPage.ctaButtonXpath),
Resolved

2022-05-17 13:02 UTC, pomi commented on playwright/tests/smoke/pdp.spec.ts
> +    expect.soft(await page.locator(pdpPage.accordionDirectionsBodyPlaceholderXpath));
Resolved

2022-05-17 13:02 UTC, pomi commented on playwright/tests/smoke/singleAccordion.spec.ts
> +    await page.locator(accordionPage.plusIconFirstXpath).click();
Resolved

2022-05-17 14:20 UTC, konst8 submitted a review, later dismissed

2022-05-17 15:52 UTC, hvanyo submitted a review, later dismissed

2022-05-20 13:34 UTC, hvanyo submitted a review, later dismissed

2022-05-20 13:58 UTC, konst8 approved these changes

2022-05-20 14:04 UTC, hvanyo commented
@pomi   PR failed check -- looks like it was with history/timeout.  Please review

2022-05-23 13:22 UTC, hvanyo approved these changes

2022-05-23 14:31 UTC, merged