feat(cx-image): Add Hero component
johnsonandjohnson/Bodiless-JS pull request #1500
Opened 2022-03-30 21:03 UTC by lucas-varela

## Changes

Add a Hero component to cx-image. Work in progress.

## Test Instructions

## Related Issues

2022-04-14 13:17 UTC, wodenx commented on packages/vital-hero/package.json
> +    "build": "tsc -p ./tsconfig.json && npm run build:api-doc",
let's follow scripts pattern from here: https://github.com/johnsonandjohnson/Bodiless-JS/blob/chore/upgrade-to-gatsby-4-and-tw-3/packages/vital-flowcontainer/package.json#L24-L30

2022-04-16 18:35 UTC, wodenx requested changes

2022-04-16 18:35 UTC, wodenx commented on packages/vital-hero/src/components/Hero/HeroClean.tsx
> +  <C.Wrapper>
I don't think we need the Hero component at all.  There's already a wrapper on the slot in the template,  Instead, let's create `vitalImage.Hero` and `vitalYouTube.Hero` tokens and apply these directly to a chameleon on the `TopContent` slot in the generic template, using `on`.

2022-04-16 18:35 UTC, wodenx commented on packages/vital-hero/src/components/Hero/tokens/vitalHero.ts
> +const Image = asHeroToken({
so this becomes `vitalImage.Hero` -- but we might not even need that - is it any different from `vitalImage.Landscape"?

2022-04-18 19:12 UTC, lucas-varela commented on packages/vital-hero/src/components/Hero/HeroClean.tsx
> +  <C.Wrapper>
The `vital-hero` package was created because we needed to place `HeroClean` and `asHeroToken` somewhere, and placing them inside `vital-elements`, for instance, would create a circular dependency between that package and `vital-image`.

Anyway, I also believe we don't need the whole Hero component just for a wrapper since `GenericTemplate` already provides one, so I removed the `vital-hero` package completely and moved the tokens to the image and youtube packages, like you suggested.

2022-04-18 19:18 UTC, lucas-varela commented on packages/vital-hero/src/components/Hero/tokens/vitalHero.ts
> +const Image = asHeroToken({
Yeah, it's pretty much a combination of the `Default` and `WithLandscapePlaceholder` image tokens, but I believe creating a pattern where token collections can export a `Hero` token makes it easy to understand where that token might be used. 

That being said, I've moved the Image Hero token to the `vitalImage` token collection after removing the hero package, see: https://github.com/johnsonandjohnson/Bodiless-JS/pull/1500/files#diff-d327313a148c1e0a4a8e140a36565c2baf68ce60b13d486311bf6a99e8da3d51R191

2022-04-19 09:19 UTC, wodenx commented on packages/__vital__/src/components/Hero/tokens/__vital__Hero.ts
> +import { vitalImage } from '@bodiless/vital-image';
Seems we no longer need this __vital__ Hero component, right?

2022-04-19 09:20 UTC, wodenx commented on packages/__vital__/src/styleguide/Page/StyleGuideTemplate/Hero.tsx
> +const HeroVariations = (props: any) => (
I think maybe instead of having a separate "Hero" page in the styleguide, we should just add these variatios to the Img and YouTube pages.

2022-04-19 09:35 UTC, wodenx commented on packages/vital-youtube/src/components/YouTube/tokens/vitalYouTube.ts
> +const WithDefaultPlayerSettings = asYouTubeToken({
if these are really the default settings, why aren't we including them in the Default token?  And do we really need a separate token for this?

2022-04-19 09:35 UTC, wodenx commented on packages/vital-youtube/src/components/YouTube/tokens/vitalYouTube.ts
> +  Components: {
This should probably be Core

2022-04-19 09:39 UTC, wodenx commented on packages/vital-youtube/src/components/YouTube/tokens/vitalYouTube.ts
> +      asBodilessResponsive16By9Embed,
I'd put this into 'Compose'

2022-04-19 12:46 UTC, lucas-varela commented on packages/__vital__/src/components/Hero/tokens/__vital__Hero.ts
> +import { vitalImage } from '@bodiless/vital-image';
Including a Hero component in the starter package is part of AC4. @hvanyo how should we proceed here?

2022-04-19 12:47 UTC, lucas-varela commented on packages/__vital__/src/styleguide/Page/StyleGuideTemplate/Hero.tsx
> +const HeroVariations = (props: any) => (
This is also part of AC5. @hvanyo any thoughts?

2022-04-19 12:49 UTC, lucas-varela commented on packages/vital-youtube/src/components/YouTube/tokens/vitalYouTube.ts
> +const WithDefaultPlayerSettings = asYouTubeToken({
cc-ing @Guilherme-Almeida-Zeni since he was in charge of the YouTube package.

2022-04-19 12:50 UTC, lucas-varela commented on packages/vital-youtube/src/components/FlowContainer/index.ts
> +  Components: varyDesigns(
cc-ing @Guilherme-Almeida-Zeni since he was in charge of the YouTube package.

2022-04-19 12:50 UTC, lucas-varela commented on packages/vital-youtube/src/components/YouTube/tokens/vitalYouTube.ts
> +  Components: {
cc-ing @Guilherme-Almeida-Zeni since he was in charge of the YouTube package.

2022-04-19 12:50 UTC, lucas-varela commented on packages/vital-youtube/src/components/YouTube/tokens/vitalYouTube.ts
> +      asBodilessResponsive16By9Embed,
cc-ing @Guilherme-Almeida-Zeni since he was in charge of the YouTube package.

2022-04-19 12:53 UTC, hvanyo commented on packages/__vital__/src/components/Hero/tokens/__vital__Hero.ts
> +import { vitalImage } from '@bodiless/vital-image';
I don't see any harm having this cmponent available to select from in starter.  we except vital hero card to come in here as well.   There is potentially this hero image/youtube is optimized for full width and has some features that the generic image/youtube don't have.

2022-04-19 12:56 UTC, hvanyo commented on packages/__vital__/src/styleguide/Page/StyleGuideTemplate/Hero.tsx
> +const HeroVariations = (props: any) => (
Main goal is activation/demonstrable/test.. 

@lucas-varela  and i did write 'pages' but left it to him to decide how.  

I guess keeping images / videos separated is ok.   How about move ImageHero to Images page (which already exists) and  rename this page Video

2022-04-19 13:02 UTC, hvanyo commented on packages/vital-youtube/src/components/FlowContainer/index.ts
> +  Components: varyDesigns(
I think we only need to provide one player:
DefaultSettings  (default settings & full screen)
SEO schema
Reponsive16x9

If sitebuilder wants something else -- they can build their own variation.  in 95% of cases content editor should choose the above ^

2022-04-20 10:20 UTC, wodenx requested changes

2022-04-20 10:20 UTC, wodenx commented on packages/vital-youtube/src/components/FlowContainer/index.ts
> +      vitalYouTube.Default,
Le's compose all these tokens into default and just apply Default here. (so in 'vitalYouTube.tsx' add these to the 'Default' token).

2022-04-20 10:20 UTC, wodenx commented on packages/vital-structuredata/package.json
> +  "name": "@bodiless/vital-structuredata",
Consider renaming this @bodiless/structure-data -- I'm not sure there is anything 'vital' specific here, and it could be used with other design systems.  cc @lucas-varela  @hvanyo

2022-04-20 10:20 UTC, wodenx commented on packages/vital-youtube/src/components/YouTube/tokens/vitalYouTube.ts
> +  },
Add compose key with all the tokens which are currently added when creating the flow container variation

2022-04-20 10:20 UTC, wodenx commented on packages/vital-structuredata/package.json
> +  "name": "@bodiless/vital-structuredata",
Or maybe even @bodiless/schema-org

2022-04-20 16:21 UTC, wodenx submitted a review, later dismissed

2022-04-28 17:20 UTC, Guilherme-Almeida-Zeni approved these changes

2022-04-30 11:16 UTC, wodenx commented on packages/vital-image/src/components/Img/tokens/vitalImage.ts
> +    _: withDesign({
Hm...  where is this 'Image' design key defined?  Is it part of 'asGatsbyImage? '  If so, then I think we should consider defining asImageToken which allows you to apply these withoout using 'withDesign'.  It's confusing that we are applying a design in an element token...

2022-04-30 11:19 UTC, wodenx commented on packages/vital-image/src/components/Img/tokens/vitalImage.ts
> +  Schema: {
Need to check whether this conflicts with work @marcopagliarulo  is doing - see https://github.com/johnsonandjohnson/Bodiless-JS/pull/1581/files#diff-b6a631087f3162c62a6696bed4f400f461b910442b6e5877b81367bd0cc51e41R22-R27.  Originally, @marcopagliarulo  had added this node key to the base token and i asked him to move it - but I believe I was mistaken -- it seems we need this node key pretty much anywhere the image is used.

2022-05-02 12:34 UTC, Guilherme-Almeida-Zeni approved these changes

2022-05-03 21:42 UTC, dewen approved these changes

2022-05-16 12:55 UTC, solutionsbyheidi approved these changes

2022-05-16 13:51 UTC, dewen approved these changes

2022-05-16 13:53 UTC, hvanyo approved these changes

2022-05-16 13:54 UTC, merged