feat(): Vital card
johnsonandjohnson/Bodiless-JS pull request #1570
Opened 2022-04-14 12:51 UTC by dewen

## Changes

## Test Instructions

## Related Issues

fixes: #1478

2022-04-18 14:35 UTC, wodenx commented on packages/vital-card/src/components/Card/tokens/vitalCard.ts
> +    Description: on(RichTextClean)(vitalRichText.Default),
I think we were going to make a version of the editor which does not allow links.

2022-04-18 14:35 UTC, wodenx commented on packages/vital-card/src/components/Card/tokens/vitalCard.ts
> +    // @todo: when do we need RichTextClean?
Just on the description, i believe.

2022-04-18 14:36 UTC, wodenx commented on packages/vital-card/src/components/Card/tokens/vitalCard.ts
> +  },
Don't we also need an editor for the eybrow?

2022-04-18 14:36 UTC, wodenx commented on packages/vital-card/src/components/Card/tokens/vitalCard.ts
> +    Wrapper: withNodeKey('card'),
no i don't think we want a wrapper level node key.

2022-04-18 14:37 UTC, wodenx commented on packages/vital-card/src/components/Card/tokens/vitalCard.ts
> +    ImageLink: asBodilessLink({ nodeKey: 'image-link' }),
i think we are removing image link as well - but we want to add asBoeilessLink to the wrapper.

2022-04-18 14:37 UTC, wodenx commented on packages/vital-card/src/components/Card/tokens/vitalCard.ts
> +    Wrapper: asBodilessLink(),
This should be in "editors" domain.

2022-04-18 14:39 UTC, wodenx commented on packages/vital-card/src/components/Card/tokens/vitalCard.ts
> +    ImageLink: vitalLink.Default,
remove image link.  Also - we wojldn't apply a vitalLink token to anhything but a LinkClean.  Probably in future it would be good to enforce this somehow.

2022-04-18 14:45 UTC, wodenx commented on packages/vital-card/src/components/Card/tokens/vitalCard.ts
> +const WithVerticalOrientationCard = asCardToken({
just call this 'WithVerticalOrientation'

2022-04-18 14:46 UTC, wodenx commented on packages/vital-card/src/components/Card/tokens/vitalCard.ts
> +const WithNoTitleCard = asCardToken({
yeah - remove the ...Card from all these token names.  they will all be referenced as, eg, `vitalCard.WithNoTitle`

2022-04-18 14:47 UTC, wodenx commented on packages/vital-card/src/components/Card/tokens/vitalCard.ts
> +  Editors: {
Why are we overriding the editors and schema?

2022-04-18 14:48 UTC, wodenx requested changes
See comments.

2022-04-18 16:26 UTC, hvanyo commented on packages/vital-card/doc/Card.md
> +Vital card component displays information for a single object through an
Vital Card is a group of content which typically features a less than full size image alongside supporting content or a call to action (CTA). Cards are commonly used on websites to call out or offer something to the site visitor.

2022-04-18 16:26 UTC, hvanyo commented on packages/vital-card/package.json
> +    "site.tailwind.config.js"
@dewen isn't this suppose to be tailwind.config.js

2022-04-18 16:26 UTC, hvanyo commented on packages/vital-card/package.json
> +    "@bodiless/vital-link": "^1.0.0-beta.7",
@dewen  pretty sure you will need to use tailwind if you added any classes to component

2022-04-18 16:26 UTC, hvanyo commented on packages/vital-card/src/components/Card/CardClean.tsx
> +        <CTAWrapper>
@wodenx  I thought we discussed streaming line this CTA Wrapper and CTAText?? cc; @dewen

2022-04-18 16:26 UTC, hvanyo commented on packages/vital-card/src/components/Card/CardClean.tsx
> +      <ImageLink>
@dewen  This should have been ImageWrapper & Image

2022-04-18 16:26 UTC, hvanyo commented on packages/vital-card/src/components/Card/tokens/vitalCard.ts
> +    Title: withNodeKey('title'),
for all these nodekeys prefer we setup enum and use that -> i.e.
https://github.com/johnsonandjohnson/Bodiless-JS/blob/main/packages/cx-templates/src/components/GenericTemplate/constants.ts#L15

2022-04-18 16:26 UTC, hvanyo commented on packages/vital-card/src/index.ts
> + * Copyright © 2021 Johnson & Johnson
```suggestion
 * Copyright © 2022 Johnson & Johnson
```

2022-04-18 18:54 UTC, dewen commented on packages/vital-card/src/components/Card/tokens/vitalCard.ts
> +    Title: withNodeKey('title'),
@hvanyo thanks

What if I have multiple Cards in the same example section on Card page? I need to define separate node Keys on vital site level component, right?

2022-04-18 19:23 UTC, hvanyo commented on packages/vital-card/src/components/Card/tokens/vitalCard.ts
> +    Title: withNodeKey('title'),
@dewen  yes and you did that in packages/__vital__  where a card can have a different nodekey,  but the nodekeys assigned to the slots they shouldn't ever change and by using enum it kind of enforcing that.   Otherwise we have hard time swapping out card variations. (ie.if one got "title" and the other got "cardtitle" these two cards titles woudn't be interchangeable.)

2022-04-18 19:31 UTC, dewen commented on packages/vital-card/package.json
> +    "site.tailwind.config.js"
Thanks

2022-04-18 19:34 UTC, dewen commented on packages/vital-card/doc/Card.md
> +Vital card component displays information for a single object through an
updated

2022-04-18 19:34 UTC, dewen commented on packages/vital-card/src/components/Card/tokens/vitalCard.ts
> +  Editors: {
updated

2022-04-19 11:48 UTC, dewen commented on packages/vital-card/src/components/Card/tokens/vitalCard.ts
> +    Title: withNodeKey('title'),
@hvanyo updated, please check
Thanks

2022-04-19 19:39 UTC, hvanyo commented on packages/vital-card/src/components/Card/CardClean.tsx
> +        <CTAWrapper>
@wodenx ??

2022-04-19 19:41 UTC, hvanyo commented on packages/vital-card/src/components/Card/tokens/vitalCard.ts
> +    Description: on(RichTextClean)(vitalRichText.Default),
@wodenx -- we are but you descoped this in favor of another..
its ready -- @dewen  would you bring this over: https://github.com/johnsonandjohnson/Bodiless-JS/pull/1498/files and include in your PR.  Then switch tousing BasicNoLink

2022-04-19 19:45 UTC, hvanyo commented on packages/vital-templates/src/components/StyleGuideTemplate/tokens/vitalStyleGuideTemplate.ts
> +    Examples: withNodeKey('examples'),
@dewen doesn't this change break all other styleguide pages if you don't rename the *.json files?

2022-04-19 19:48 UTC, hvanyo commented on packages/vital-card/src/components/Card/tokens/vitalCard.ts
> +  Components: {
@dewen  we don't want any ...Base.Compnents?

2022-04-19 19:49 UTC, hvanyo commented on packages/vital-card/src/components/Card/tokens/vitalCard.ts
> +  Layout: {
@dewen  we don't want any ...Base.Layout?

2022-04-19 19:49 UTC, hvanyo commented on packages/vital-card/src/components/Card/tokens/vitalCard.ts
> +  Spacing: {
@dewen  we don't want any ...Base.Spacing?

2022-04-19 19:49 UTC, hvanyo commented on packages/vital-card/src/components/Card/tokens/vitalCard.ts
> +    TitleWrapper: vitalTypography.H2,
@dewen  we don't want any ...Base.Theme?

2022-04-19 19:50 UTC, hvanyo commented on packages/vital-card/src/components/Card/tokens/vitalCard.ts
> +  Editors: {
asked if we need ...Base.Domain on the 4 cases Spacing, Theme, Layout Components.

2022-04-19 19:58 UTC, hvanyo commented
@dewen  I didn't see us adding these the cards to base vital flowcontainer...  I guess we didn't call it out in ACS.  Do you know how to do that? 

1) add FlowContainer component and add card varations.
https://github.com/johnsonandjohnson/Bodiless-JS/pull/1554/files#diff-96b0646f3316ae3516ac8fe611c0170cf673fea0cc70fa2f16c3e4dd0312dc23
2) add vitalCardFlowContainer to vitalFlowClontainer
i.e. https://github.com/johnsonandjohnson/Bodiless-JS/pull/1554/files#diff-79aead9c186a27090cf398250f3c82f5b2555b042f9940a31c56bc15fa2e1a9c 
3) add vital-card to pacakge.json in vital-flowcontianer

Variations:
vary   
  WithHorizontalOrientation,
  WithVerticalOrientation,
over 
  WithNoDescription,
  WithNoTitle,

should produce Horizont with no description & title, horizonta; with description & no title, horizontal with description & title, repeat for vertical.    Hero needs to go into hero chameleon only but that is in Lucas's PR...

2022-04-20 01:18 UTC, dewen commented on packages/vital-templates/src/components/StyleGuideTemplate/tokens/vitalStyleGuideTemplate.ts
> +    Examples: withNodeKey('examples'),
I searched on upgrade branch and didn't find any files or folders under `exmples` name

2022-04-20 02:47 UTC, dewen commented on packages/vital-card/src/components/Card/tokens/vitalCard.ts
> +  Components: {
Updated

2022-04-20 03:02 UTC, dewen commented on packages/vital-card/src/components/Card/tokens/vitalCard.ts
> +  Layout: {
Updated

2022-04-20 03:03 UTC, dewen commented on packages/vital-card/src/components/Card/tokens/vitalCard.ts
> +  Spacing: {
Updated

2022-04-20 03:04 UTC, dewen commented on packages/vital-card/src/components/Card/tokens/vitalCard.ts
> +    TitleWrapper: vitalTypography.H2,
Updated

2022-04-21 12:47 UTC, dewen commented on packages/vital-card/package.json
> +    "@bodiless/vital-link": "^1.0.0-beta.7",
added

2022-04-21 13:09 UTC, hvanyo approved these changes

2022-04-21 13:09 UTC, hvanyo commented on packages/vital-card/src/components/Card/tokens/vitalCard.ts
> +  Meta: flowHoc.meta.term('Title')('No Description'),
```suggestion
  Meta: flowHoc.meta.term('Description')('No Description'),
```

2022-04-21 13:09 UTC, hvanyo commented on packages/vital-card/src/components/FlowContainer/index.ts
> +  Title: on(CardClean)(vitalCard.Base),
There is a few ways to do this..
make @wodenx  can say best way:


  Title: asCardToken({
    Meta: flowHoc.meta.term('Title')('With Title'),
  }),

2022-04-21 14:32 UTC, dewen commented on packages/vital-card/src/components/Card/tokens/vitalCard.ts
> +    Description: on(RichTextClean)(vitalRichText.Default),
Updates in https://github.com/johnsonandjohnson/Bodiless-JS/pull/1570/commits/011549af1cdc5e3034afd26ba4bb96b7b9f776e0

- Copy over `BasicNoLink` updates from original draft PR
- Update Cx => Vital
- Applied to `Description: on(RichTextClean)(vitalRichText. BasicNoLink`

2022-04-21 18:13 UTC, dewen commented on packages/vital-card/src/components/FlowContainer/index.ts
> +  Title: on(CardClean)(vitalCard.Base),
updated

2022-04-21 18:16 UTC, dewen commented on packages/vital-card/src/components/Card/tokens/vitalCard.ts
> +  Meta: flowHoc.meta.term('Title')('No Description'),
@hvanyo Not sure why we set category to `Description` here, thought it's the token meta Title.

2022-04-21 18:17 UTC, dewen commented on packages/vital-card/src/components/FlowContainer/index.ts
> +    VerticalCard: on(CardStatic)(vitalCardStatic.Base, vitalCardStatic.WithVerticalOrientation),
Trying to use vertical as default one since we are not exposing Base token.

2022-04-22 11:07 UTC, dewen commented on packages/vital-card/src/components/Card/tokens/vitalCard.ts
> +  Meta: flowHoc.meta.term('Title')('No Description'),
updated

2022-04-22 11:11 UTC, dewen commented on packages/vital-card/src/components/FlowContainer/index.ts
> +  Vertical: on(CardClean)(vitalCard.WithVerticalOrientation),
Updated, thanks

2022-04-22 11:17 UTC, dewen commented
> @dewen I didn't see us adding these the cards to base vital flowcontainer... I guess we didn't call it out in ACS. Do you know how to do that?
> 
> 1. add FlowContainer component and add card varations.
>    https://github.com/johnsonandjohnson/Bodiless-JS/pull/1554/files#diff-96b0646f3316ae3516ac8fe611c0170cf673fea0cc70fa2f16c3e4dd0312dc23
> 2. add vitalCardFlowContainer to vitalFlowClontainer
>    i.e. https://github.com/johnsonandjohnson/Bodiless-JS/pull/1554/files#diff-79aead9c186a27090cf398250f3c82f5b2555b042f9940a31c56bc15fa2e1a9c
> 3. add vital-card to pacakge.json in vital-flowcontianer
> 
> Variations: vary WithHorizontalOrientation, WithVerticalOrientation, over WithNoDescription, WithNoTitle,
> 
> should produce Horizont with no description & title, horizonta; with description & no title, horizontal with description & title, repeat for vertical. Hero needs to go into hero chameleon only but that is in Lucas's PR...

updated

2022-04-22 12:08 UTC, hvanyo commented on packages/vital-card/src/components/FlowContainer/index.ts
> +    ...varyDesigns(
@dewen  
aren't the vertical & horitontal already part of the varied group?  It maybe in Content variations you didn't add WithTitle WithDescription if you are missing those variations -- they were in there yesterday.
we said to put in hero as well here.

2022-04-26 15:48 UTC, hvanyo commented
@dewen  we can close this PR right??? Its merged to Lucas's branch?

2022-04-29 13:02 UTC, hvanyo commented
closing as this is not relevant I don't think. if it is please reopen.

2022-04-29 13:02 UTC, closed without merging