Feat/cx image is static
johnsonandjohnson/Bodiless-JS pull request #1581
Opened 2022-04-15 08:58 UTC by marcopagliarulo

## Changes
Image is Static.
Create an observer for not hydrated gatsby images that hide the placeholder and shows the gatsby image on browser not supporting lazy loading.
Set the gatsby image default nodeKey to allow gatsby image working inside a flow container

## Test Instructions
  ### Gatsby Image in safari
  - use Safari < 15.4
  - open any page containing a static gatsby image
  - check the image is loaded

  ### Gatsby Image in flow container
  - create a new page from Home or open an existing page of General Template on Edit env
  - in any Flow Container, add an Image component
  - upload any image file
  - reload the page (or check in Static)
  - check the image element in html markup

## Related Issues
  Fixes #1452

2022-04-18 11:01 UTC, wodenx commented on packages/bodiless-hydration/src/withoutHydration/withoutHydration.tsx
> +const fullSelector = (element: HTMLElement | null) => {
```suggestion
/**
 * Gets the full selector for a dom element.
  * Used to create a unique identifier for the element which can be used as a key
  * to stash the rendered, non-hydrated element so it can be restored after a
  * component remounts.
  */
const fullSelector = (element: HTMLElement | null) => {
```

2022-04-18 11:03 UTC, wodenx commented on packages/gatsby-theme-bodiless/gatsby-ssr.js
> +  const lazyLoadingFallbackScript = oneLine`const e = "undefined" != typeof HTMLImageElement && "loading" in HTMLImageElement.prototype;
Please add a commnet describing why we are doing this rather than just allowing gatsby-image to do it.

2022-04-18 11:08 UTC, wodenx commented on packages/vital-image/src/components/FlowContainer/index.ts
>    Image: on(Img)(withDesign({
This doesn't make sense to me - why are we applying this via withDesign?  I dn't tink 'Img' takes a design...

2022-04-18 13:59 UTC, wodenx requested changes
See comments.

2022-04-19 14:10 UTC, marcopagliarulo commented on packages/bodiless-hydration/src/withoutHydration/withoutHydration.tsx
> +const fullSelector = (element: HTMLElement | null) => {
Comment applied, thanks

2022-04-19 14:10 UTC, marcopagliarulo commented on packages/gatsby-theme-bodiless/gatsby-ssr.js
> +  const lazyLoadingFallbackScript = oneLine`const e = "undefined" != typeof HTMLImageElement && "loading" in HTMLImageElement.prototype;
Commend added

2022-04-19 14:18 UTC, marcopagliarulo commented on packages/vital-image/src/components/FlowContainer/index.ts
>    Image: on(Img)(withDesign({
You right, it was a legacy from the previous draft implementation. Additionally Img is likely not used since it is the fallback tag used when gatsby image data is not provided.

2022-04-19 14:30 UTC, wodenx approved these changes

2022-04-22 20:28 UTC, wodenx approved these changes

2022-04-30 11:19 UTC, wodenx commented on packages/vital-image/src/components/FlowContainer/index.ts
> +const ImageWithNodeKey = asElementToken({
See https://github.com/johnsonandjohnson/Bodiless-JS/pull/1500/files#r862344688

2022-05-02 14:16 UTC, lucas-varela commented
Closing, as these changes have been manually merged into #1500.

2022-05-02 14:16 UTC, closed without merging