feat(vital-table): add vital table
johnsonandjohnson/Bodiless-JS pull request #1598
Opened 2022-04-19 00:19 UTC by hvanyo

* Add vital-table

2022-04-19 08:32 UTC, wodenx commented on packages/vital-table/src/components/Table/TableClean.tsx
> +const TableStatic = withoutHydrationInline()(TableClean);
I think this should just be withouthydration() - we want it wrapped in a block.

2022-04-19 08:36 UTC, wodenx commented on packages/vital-table/src/components/Table/TableClean.tsx
> +  <C.Wrapper {...rest}>
Do we need this wrapper?  I'd say we should just re-export the bodiless table (which already has a [TableComponents](https://github.com/johnsonandjohnson/Bodiless-JS/blob/main/packages/bodiless-table/src/types.ts#L23) type.

2022-04-19 08:38 UTC, wodenx commented on packages/vital-table/src/components/Table/index.bl-edit.ts
> +export { default as vitalLinkTable } from './tokens';
```suggestion
export { default as vitalTable } from './tokens';
```

2022-04-19 08:39 UTC, wodenx commented on packages/vital-table/src/components/Table/index.static.ts
> +  // todo ?? StaticTable as TableStatic,
```suggestion
  // todo ?? StaticTable as TableStatic,
  StaticBlock as TableStatic,
```

2022-04-19 08:43 UTC, wodenx commented on packages/vital-table/src/components/Table/index.bl-edit.ts
> +export { default as vitalLinkTable } from './tokens';
Actually -we only want to do the static component and tokens here:
``` 
import { TableStatic } from './TableClean';
import vitalTableStatic from './tokens';

export { TableStatic, vitalTableStatic };
`

2022-04-19 08:46 UTC, wodenx commented on packages/vital-table/src/components/Table/index.ts
> +export { default as vitalTable } from './tokens';
and an export of vitalTableBase. - and it's better  for docs to be be more verbose, like
``
import vitalTable from './tokens';
import vitalTableBase from './tokens/vitalTable';
import TableClean, { asTableToken } from './TableClean';

export {
  vitalTable, vitalTableBase, TableClean, asTableToken.
}
```

2022-04-19 08:50 UTC, wodenx commented on packages/vital-table/src/components/Table/tokens/vitalTable.ts
> +      withDesign({
Should be 'Editors' and  if we skip the extra wrapper, you can do without the 'withDesign' here.  Also, let's add a `CellContent` to the bodiless table design, and use that here rather than using withEditor...
```
Editors: {
  CellContent: on(RichTextClean)(vitalRichText.Default),
  },
``

2022-04-19 08:51 UTC, wodenx commented on packages/vital-table/src/components/Table/tokens/vitalTable.ts
> +const StripedTable = asTableToken({
I think make this 'WithStripes' and omit the composition of Base

2022-04-19 08:52 UTC, wodenx commented on packages/vital-table/src/components/Table/tokens/vitalTable.ts
> +const StripedTable = asTableToken({
we can compose it into default if you want

2022-04-19 08:53 UTC, wodenx commented on packages/vital-table/src/components/Table/types.ts
> +export type TableComponents = {
See above - just use the TableComponents already defined on the basic bodiless table - it already has a warapper.

2022-04-19 08:54 UTC, wodenx commented on packages/vital-table/src/components/Table/tokens/vitalTable.ts
> +      withDesign({
i'm not sure we actually need the nodeKey.  For the placeholder, maybe we can just use the defautl placeholder, but if you want a unique one, add it via 'addProps', maybe in the 'Content' domain.

2022-04-19 20:38 UTC, hvanyo commented on packages/vital-table/src/components/Table/TableClean.tsx
> +  <C.Wrapper {...rest}>
took note to see if I use when I get to styling..  Looks like I can probably remove it if I don't use it.

2022-04-19 20:40 UTC, hvanyo commented on packages/vital-table/src/components/Table/index.bl-edit.ts
> +export { default as vitalLinkTable } from './tokens';
Addresed

2022-04-19 20:40 UTC, hvanyo commented on packages/vital-table/src/components/Table/index.static.ts
> +  // todo ?? StaticTable as TableStatic,
Addressed

2022-04-19 20:43 UTC, hvanyo commented on packages/vital-table/src/components/Table/index.ts
> +export { default as vitalTable } from './tokens';
Addressed

2022-04-20 09:59 UTC, wodenx requested changes

2022-04-20 09:59 UTC, wodenx commented on packages/bodiless-table/src/Table.tsx
> +  TableWrapper: Div,
Let's call this 'Wrapper' and the current wraper 'Table'

2022-04-20 09:59 UTC, wodenx commented on packages/vital-table/src/components/Table/TableClean.tsx
> +const tableComponents: TableComponents = {
So you hve the xtra level of indirection bc you are still creating a component here - I suggest just re-exporting the table from bodiless, as we do for the flow container and the listing filters:
```
import { CleanTable } from '@bodiless/table';
import type { TableComponents } from '@bodiless/table';

const tableClean = CleanTable;
cosnt tableStatic = withoutHydration()(CleanTable);
const asTableToken = asVitalTokenSpec<TableComponents>();

export default tableClean;
export { TableStatic, asTableTOken };
export {

2022-04-20 09:59 UTC, wodenx commented on packages/vital-table/src/components/Table/index.ts
> +export type { TableComponents, TableBaseProps } from './types';
i don't think we need toe xport TableBaseProps

2022-04-20 09:59 UTC, wodenx commented on packages/vital-table/src/components/Table/tokens/vitalTable.ts
> +const Base = asTableToken({
Once you fix tableClean as suggested you won't have this indirection.

2022-04-20 09:59 UTC, wodenx commented on packages/vital-table/src/components/Table/tokens/vitalTable.ts
> +      CellContent: withEditorRich('cell', ''),
```suggestion
      CellContent: on(EditorRichClean)(vitalEditorRich.Default),
```

2022-04-20 09:59 UTC, wodenx commented on packages/vital-table/src/components/Table/tokens/vitalTable.ts
> +      Cell: 'px-6 text-left',
padding in spacing domain.

2022-04-20 09:59 UTC, wodenx commented on packages/vital-table/src/components/Table/tokens/vitalTable.ts
> +const withHoverable = asTableToken({
```suggestion
const WithHoverable = asTableToken({
```

2022-04-20 09:59 UTC, wodenx commented on packages/vital-table/src/components/Table/tokens/vitalTable.ts
> +const withStripes = asTableToken({
```suggestion
const WithStripes = asTableToken({
```

2022-04-20 11:56 UTC, hvanyo commented on packages/vital-table/src/components/Table/TableClean.tsx
> +const TableStatic = withoutHydrationInline()(TableClean);
adddressed

2022-04-20 12:17 UTC, hvanyo commented on packages/vital-table/src/components/Table/tokens/vitalTable.ts
> +const withStripes = asTableToken({
addressed

2022-04-20 12:17 UTC, hvanyo commented on packages/vital-table/src/components/Table/tokens/vitalTable.ts
> +const withHoverable = asTableToken({
addressed

2022-04-20 12:18 UTC, hvanyo commented on packages/vital-table/src/components/Table/tokens/vitalTable.ts
> +      Cell: 'px-6 text-left',
addressed

2022-04-20 12:30 UTC, hvanyo commented on packages/vital-table/src/components/Table/index.ts
> +export type { TableComponents, TableBaseProps } from './types';
addressed

2022-04-20 12:36 UTC, hvanyo commented on packages/vital-table/src/components/Table/types.ts
> +export type TableComponents = {
addressed

2022-04-20 20:03 UTC, hvanyo commented on packages/vital-table/src/components/Table/TableClean.tsx
> +  <C.Wrapper {...rest}>
addressed

2022-04-20 20:03 UTC, hvanyo commented on packages/vital-table/src/components/Table/tokens/vitalTable.ts
> +      withDesign({
addressed

2022-04-20 20:03 UTC, hvanyo commented on packages/vital-table/src/components/Table/tokens/vitalTable.ts
> +const StripedTable = asTableToken({
addressed

2022-04-20 20:04 UTC, hvanyo commented on packages/bodiless-table/src/Table.tsx
> +  TableWrapper: Div,
addressed

2022-04-20 20:04 UTC, hvanyo commented on packages/vital-table/src/components/Table/tokens/vitalTable.ts
> +const Base = asTableToken({
addressed

2022-04-20 20:04 UTC, hvanyo commented on packages/vital-table/src/components/Table/tokens/vitalTable.ts
> +      CellContent: withEditorRich('cell', ''),
addreseed

2022-04-29 13:52 UTC, wodenx approved these changes

2022-04-29 14:00 UTC, merged