Feature/bodiless i18n
johnsonandjohnson/Bodiless-JS pull request #1621
Opened 2022-04-22 12:40 UTC by konst8

## Changes
Implement i18n.

2022-04-25 11:36 UTC, wodenx requested changes

2022-04-25 11:36 UTC, wodenx commented on packages/bodiless-i18n/package.json
> +    "/bodiless.docs.json"
need to add getDocs

2022-04-25 11:36 UTC, wodenx commented on packages/bodiless-i18n/src/LanguageNode/withLanguageNode.tsx
> +
Please add jsdoc blocks for all exports, including usage examples where appicable.

2022-04-25 11:36 UTC, wodenx commented on packages/vital-layout/src/components/LanguageSelector/LanguageSelectorClean.tsx
> +const LanguageSelectorBase: FC<LanguageSelectorProps> = ({ components: C }) => (
Do we need this component at all if it is just a link with a wrapper?  Perhaps we can simply create a vitalLink token to implement language selection.

2022-04-25 11:36 UTC, wodenx commented on packages/vital-layout/src/components/LanguageSelector/tokens/index.ts
> +  Behavior: {
I tink this should be in the  "Content" domain,  Also - let's discuss at standup where these shoudl be specified -- maybe at the __vital__ level?

2022-04-25 11:36 UTC, wodenx commented on packages/vital-layout/src/components/LanguageSelector/tokens/index.ts
> +  Spacing: {
If we get rid of the 'LahguageSelector' component, then we could add a LanguageButtonWrapper in HeaderClean and put these classes there.  Again, something to discuss at standup.  cc @hvanyo

2022-04-25 11:36 UTC, wodenx commented on packages/vital-layout/src/components/LanguageSelector/tokens/index.ts
> +  Content: {
I think this should be in Core domain.  Also, I believe you can now just use `addProps`  -- it will now take a function.

2022-04-25 11:36 UTC, wodenx commented on packages/vital-layout/src/components/Header/HeaderClean.tsx
> +  LanguageButton: LanguageSelectorClean,
let's rename this key to 'LanguageSelector' (not `LanguageButton`)

2022-04-25 11:36 UTC, wodenx commented on sites/__vital__/src/data/pages/es/index.json
> +{
Let's be sure to add this also to vital-demo.

2022-04-25 11:36 UTC, wodenx commented on packages/vital-layout/src/components/LanguageSelector/tokens/index.ts
> +  Behavior: {
I think the right way to do this is at site level (in the __vital__ starter (and also in the vital-demo).  So probbly in the default Header there is no language selector, just a token which can be used to add one, and at site level the header is shadowed to add that token, along with the specific language choices (fine to use es/en for starter -- for demo we need to discuss what 2nd language to support).

2022-04-25 11:36 UTC, wodenx commented on packages/vital-layout/src/components/LanguageSelector/tokens/index.ts
> +  Behavior: {
[7:33 AM] Oden, Christopher [CPCUS]
    so probably the pattern should be:

	wrap whole page in language context
	wrap secitnos of page (hader/footer) in language nodes which allow per-langauge content.

does that make sense?
​[7:34 AM] Mishur, Konstantin [JJCRU Non-J&J]
    yes, absolutely
​[7:34 AM] Oden, Christopher [CPCUS]
    if so then i think we need 3 tokens

	page level token which adds the provider
	header/footer tokens which add the langauge nodes

And i think these should not be applied by default in the vital- packagds -- but applied at site level (through shadowing) on starter and/or demo -- but that is to be discussed at stanup
<https://teams.microsoft.com/l/message/19:a13da064505048bdbb55feb0428ac740@thread.tacv2/1650886421202?tenantId=3ac94b33-9135-4821-9502-eafda6592a35&amp;groupId=e0707489-d17d-44c8-9066-df88931a96a7&amp;parentMessageId=1650884152314&amp;teamName=CanvasX Core Platform Team&amp;channelName=CanvasX Dev&amp;createdTime=1650886421202>

2022-05-05 12:11 UTC, konst8 commented on packages/bodiless-i18n/package.json
> +    "/bodiless.docs.json"
Added.

2022-05-05 12:12 UTC, konst8 commented on packages/bodiless-i18n/src/LanguageNode/withLanguageNode.tsx
> +
Added. May be needs to be extended in the docs.

2022-05-05 12:13 UTC, konst8 commented on packages/vital-layout/src/components/LanguageSelector/LanguageSelectorClean.tsx
> +const LanguageSelectorBase: FC<LanguageSelectorProps> = ({ components: C }) => (
Done.

2022-05-05 12:14 UTC, konst8 commented on packages/vital-layout/src/components/LanguageSelector/tokens/index.ts
> +  Behavior: {
Done.

2022-05-05 12:14 UTC, konst8 commented on packages/vital-layout/src/components/LanguageSelector/tokens/index.ts
> +  Spacing: {
Done.

2022-05-05 12:15 UTC, konst8 commented on packages/vital-layout/src/components/LanguageSelector/tokens/index.ts
> +  Content: {
Done.

2022-05-05 12:15 UTC, konst8 commented on packages/vital-layout/src/components/Header/HeaderClean.tsx
> +  LanguageButton: LanguageSelectorClean,
Done.

2022-05-05 12:15 UTC, konst8 commented on sites/__vital__/src/data/pages/es/index.json
> +{
Done.

2022-05-06 08:04 UTC, wodenx commented on packages/__vital__/src/components/Page/tokens/__vital__Page.ts
> +const DefaultTemplate = asGenericTemplateToken({
Rather than putting ths in page, it should be in __vital__GenericTemplate.  Also why not sjadow that?

2022-05-06 08:20 UTC, wodenx commented on packages/__vital__/src/components/Page/tokens/__vital__Page.ts
> +    PageWrapper: withLanguages([
To be safe we should repeat vitalGenericTemplateBase.Default.Core.PageWrapper here or just use extension, as
```
asGenericTemplateToken(vitalGenericTemplateBase.Default, {
  Core: {
    PageWrapper: ...
```

2022-05-06 08:21 UTC, wodenx commented on packages/__vital__/src/components/Page/tokens/__vital__Page.ts
> +  ...vitalGenericTemplate.Default,
Should always extend the ...Base version of the token collection, ie
```
...vitalGenericTemplateBase.Default
```
That version is not shadowed.  Otherwise, if you use this to shadow vitalGenericTemplate, there will be a circular import problem.

2022-05-06 08:27 UTC, wodenx commented on packages/__vital__/src/components/Page/tokens/__vital__Page.ts
>  const NoBreadcrumbsGeneric = asGenericTemplateToken({
While we're in here - i think we should create a 'vitalGenericTemplate.WithNoBreadcrumbsOnHomePage' token with the condition in the 'Flow' domain, like:
```
const WithNoBreadcrumbsOnHomePage = asGenericTemplateToken({
  Flow: flowIf(isHomePage),
  Components: {
    BreadcrumbWrapper: replaceWith(() => null),
   Breadcrumb: replaceWith(() => null).
  },
});
```
and compose it into the Base token"
```
const Base = asGenericTemplateToken({
  ...,
  Compose: {
    WithNoBreadcrumbsOnHomePage,
   }.
   });
   
    
Compose it into vitalGenericTemplate.Base, and put the condition into the 'Flow' domain. like
const WithNoBrad

2022-05-06 08:29 UTC, wodenx commented on packages/__vital__/src/shadow/@bodiless/vital-layout/Footer.ts
> +const Default = asFluidToken({
Shouldn't this be asFooterToken, not asFluid Token?  Also, I think i'd use extension here since we're not overriding anything, just adding -- so
asFooterToken(vitalFooterBase.Default, {
  Core: {
     _: addProps(...),
   },
  ...
});

2022-05-06 08:50 UTC, wodenx commented on packages/bodiless-i18n/src/LanguageSelector/index.ts
> +export const asLanguageSelector = on(LinkClean)(
This doesn't belong in @bodiless/i18n - LinkClean is a vital component so you are introducing a dependency we don't want.  I think you can probably create a 
/src/components/LanguageSelectorLink in vital-layouts and create a vitalLanguageSelectorLink token collection which imports useLanguageSelectorProps from @bodiless/i18n (or maybe jsut export `asLanguageSelector` from i18n as
```
export const asLanguageSelector = addProps(useLanguageSelectorProps)
```

2022-05-06 08:54 UTC, wodenx commented on packages/vital-layout/src/components/Header/HeaderClean.tsx
> +          <C.LanguageSelectorWrapper />
Sorr if i misled, i think we should have both `LanguageSelectorWrapper` and `LanguageSelector`:
```
<LangauageSelectorWrapper />
  <LanguageSelector />
</LanguageSelectorWrapper>
```
Not sure if we need to make the wrapper a Div and put the classes on it, or if it's ok to put the classes directy on the LanguageSelector.  Thoughs @hvanyo  ?  In the latter case, the wrapper would jut be a fragment.

2022-05-06 08:55 UTC, wodenx commented on packages/vital-layout/src/components/Header/tokens/vitalHeader.ts
> +    LanguageSelectorWrapper: 'lg:border-vital-primary-divider lg:border-r-2',
I would create a composable `WithLanguageSelector` token which can be removed or added at site level.

2022-05-06 08:55 UTC, wodenx requested changes
See comments.

2022-05-06 08:57 UTC, wodenx commented on packages/__vital__/src/shadow/@bodiless/vital-layout/Header.ts
> +const Default = asFluidToken({
Shouldn't this be asHeaderToken?

2022-05-06 08:58 UTC, wodenx commented on packages/__vital__/src/shadow/@bodiless/vital-layout/Header.ts
> +const Default = asFluidToken({
Again, I think you can use extension here.  And probably we can just use the new `WithLanguageSelector` token exported from vitalHeader.

2022-05-09 11:38 UTC, wodenx commented on packages/__vital__/src/shadow/@bodiless/vital-layout/Header.ts
> +const WithLanguageSelector = asHeaderToken({
Sorry - I mean't that this token should be exported form vitalHeader, and *appied* at site level...

2022-05-09 11:39 UTC, wodenx requested changes
Just move the WithLanguageSelector token into vitalHeader

2022-05-10 17:25 UTC, hvanyo reviewed
Can you shadow __vital__Page instead of doing this:

https://github.com/lucas-varela/Bodiless-JS/pull/29
should closely align with your PR for shadowing..

grab my vital-templates/Page.ts & change in the sites/template/__default file.

2022-05-11 19:08 UTC, wodenx requested changes

2022-05-11 19:08 UTC, wodenx commented on packages/__vital__/src/shadow/@bodiless/vital-layout/Footer.ts
> +      withNodeKey({ nodeKey: 'Footer', nodeCollection: 'site' }),
Usual pattern is to apply the node key in the enclosing component - so in this case it would be in vitalLayout.

2022-05-11 19:08 UTC, wodenx commented on packages/__vital__/src/shadow/@bodiless/vital-layout/Footer.ts
> +      withNodeKey({ nodeKey: 'Footer', nodeCollection: 'site' }),
but leave the `withNode` here.

2022-05-11 19:08 UTC, wodenx commented on packages/__vital__/src/shadow/@bodiless/vital-layout/Footer.ts
> +      withNodeKey({ nodeKey: 'Footer', nodeCollection: 'site' }),
actually i'm a bit confused by this... should't the withNode be inside (*before* when using `as`) the withNodeKey?

2022-05-11 19:08 UTC, wodenx commented on packages/__vital__/src/shadow/@bodiless/vital-layout/Header.ts
> +        withNodeKey({ nodeKey: 'Header', nodeCollection: 'site' }),
Agin, node key should probably go in vitalLayout - and I"m not sure the withNode is necessary.  Maybe this is taken care of by withLanguageNode...

2022-05-12 11:20 UTC, konst8 commented on packages/__vital__/src/shadow/@bodiless/vital-layout/Header.ts
> +        withNodeKey({ nodeKey: 'Header', nodeCollection: 'site' }),
withLanguageNode does nothing if there is no language prefix in the path, so we still need withNode for default case.

2022-05-12 12:44 UTC, wodenx commented on packages/vital-layout/src/components/Layout/tokens/vitalLayout.ts
> +    Header: withNodeKey({ nodeKey: 'Header', nodeCollection: 'site' }),
```suggestion
    Header: withNodeKey({ nodeKey: 'header', nodeCollection: 'site' }),
```

2022-05-12 12:45 UTC, wodenx commented on packages/vital-layout/src/components/Layout/tokens/vitalLayout.ts
> +    Footer: withNodeKey({ nodeKey: 'Footer', nodeCollection: 'site' }),
```suggestion
    Footer: withNodeKey({ nodeKey: 'footer', nodeCollection: 'site' }),
```

2022-05-12 13:04 UTC, wodenx submitted a review, later dismissed

2022-05-12 13:56 UTC, hvanyo commented on packages/__vital__/src/components/Page/tokens/__vital__Page.ts
>   * See the License for the specific language governing permissions and
@konst8  Page was suppose to move shadowing..   I have in my shadow PR.   I don't know what will merge first but ideally we want nothing in components.    If we don't change, it only concern if this gets caught in testing and shadow merges first we undo shadowing.

2022-05-12 13:59 UTC, hvanyo approved these changes

2022-05-27 13:22 UTC, hvanyo approved these changes

2022-05-27 13:24 UTC, hvanyo commented on packages/__vital__/src/shadow/@bodiless/vital-layout/Footer.ts
> +/**
@konst8  Can you move these to vital_test?

2022-05-27 13:27 UTC, hvanyo commented on packages/__vital__/src/shadow/@bodiless/vital-layout/Footer.ts
> +/**
oh never mind all these have i18n in ithem..  they should all stay here.

2022-05-30 11:27 UTC, wodenx approved these changes

2022-05-30 11:28 UTC, merged