doc: Provide API docs pattern, docs for fclasses and vital-flowcontainer
johnsonandjohnson/Bodiless-JS pull request #1683
Opened 2022-05-04 22:58 UTC by wodenx

## Chnges
Implement typedoc patterns for fclasses and vital-fowcontainer
document best practices.

2022-05-06 20:39 UTC, lucas-varela requested changes
I got some comments, please take a look.

2022-05-09 13:07 UTC, wodenx commented on sites/__vital__/package.json
> +    "search-index": "create-search-index",
i replaced it with "build:search-index"

2022-05-09 13:08 UTC, wodenx commented on packages/bodiless-ui/package.json
> +    "build": "npm run build:lib && npm run build:css && npm run copy",
well ... we should standardize, i guess, but is there any advantage to run-s vs this pattern?

2022-05-09 13:10 UTC, wodenx commented on packages/bodiless-documentation/doc/Development/ApiDocumentationStandards.md
> +   * Designable components fpr FooClean.
fixed.

2022-05-09 13:21 UTC, wodenx commented on packages/vital-flowcontainer/src/components/FlowContainer/index.ts
> + * teeth
shrug.  removed.

2022-05-09 14:06 UTC, wodenx commented on typedoc.js
> +  // categorizeByGroup: true,
i just removed it - turns out we don't need any global options atm.

2022-05-09 14:20 UTC, lucas-varela commented on packages/bodiless-ui/package.json
> +    "build": "npm run build:lib && npm run build:css && npm run copy",
Using `run-s` wouldn't change the current behavior, just make it look more like the other files. Either way works great.

2022-05-10 21:08 UTC, wodenx commented on packages/fclasses/src/addClasses.tsx
> + * > the resulting component has the correct prop types.
fixed.

2022-05-10 21:08 UTC, wodenx commented on packages/fclasses/src/addClasses.tsx
> + * A HOC factory function wit the same signature as [[addClasses]].
fixed.

2022-05-10 21:09 UTC, wodenx commented on packages/bodiless-layouts/src/FlowContainer/types.ts
> +}
no semi needed for interface - this is changed bc before it was a tuype alias.

2022-05-10 21:10 UTC, wodenx commented on packages/bodiless-layouts/src/FlowContainer/index.tsx
> + * Aaaaagh
again (shrug). fixed.

2022-05-10 21:10 UTC, wodenx commented on packages/bodiless-ui/package.json
> +    "build": "npm run build:lib && npm run build:css && npm run copy",
leaving as is for now

2022-05-10 21:11 UTC, wodenx commented on packages/fclasses/src/Design.tsx
> + * name the name of the displayName.
fixed.

2022-05-10 21:11 UTC, wodenx commented on packages/fclasses/src/flowIf.tsx
> + * A [[Condition]] which evaluates to true of all of the
fixed.

2022-05-10 21:12 UTC, wodenx commented on packages/fclasses/src/flowIf.tsx
> + * A [[Condition]] which evaluates to rue of any of the
fixed.

2022-05-10 21:12 UTC, wodenx commented on packages/fclasses/src/flowIf.tsx
> + * A [[Condition]] which evaluates to rue if all the
fixed.

2022-05-11 12:31 UTC, lucas-varela approved these changes

2022-05-11 12:51 UTC, lucas-varela approved these changes

2022-05-19 15:48 UTC, hvanyo approved these changes

2022-05-19 17:36 UTC, hvanyo approved these changes

2022-05-20 13:33 UTC, lucas-varela approved these changes

2022-05-20 20:11 UTC, merged