Fix/shadowingv2
johnsonandjohnson/Bodiless-JS pull request #1787
Opened 2022-05-16 21:08 UTC by hvanyo

## Changes

## Test Instructions

## Related Issues

2022-05-19 08:26 UTC, wodenx commented on packages/__vital__/src/shadow/@bodiless/vital-templates/Page.ts
> +    _default: on(GenericTemplateClean)(vitalGenericTemplate.Default),
It seems you are not  actually adding anything with this shadow, is that intentional?  I would maybe at least add a comment here like
```
Components: {
  ...vitalPageBase.Default.Components,
   // Add or override page template options here, eg
   // _default: on(MyCustomTemplateClean)(myCustomTemplate.Default),
   // or
   // MyNewVariation: on(GenericTemplateClean)(myGenericTemplate.New),
   ```

2022-05-19 08:28 UTC, wodenx commented on packages/bodiless-hydration/src/withoutHydration/withoutHydration.tsx
> +   && window.document
Are these changes intentional?

2022-05-19 08:38 UTC, wodenx commented on packages/vital-elements/src/components/Spacing/tokens/index.ts
> +export { SpacingMeta };
Do we need to export this meta?

2022-05-19 08:41 UTC, wodenx commented on packages/vital-meta/src/components/MetaHelmet/index.ts
> +export * from './tokens/vitalMetaHelmet';
what are we exporting here?  Isn't it enough to export the default?

2022-05-19 08:44 UTC, wodenx commented on packages/vital-meta/src/components/MetaHelmet/tokens/vitalMetaHelmet.ts
> +  asSimpleMetaFieldToken,
I would not export this as part of the token collection - it's not a token.  I think probably best is just to move `asSimpleToken` to vital-elements helpers (wehre `asFluidToken` is) and export it from there.

2022-05-19 08:46 UTC, wodenx commented on packages/vital-templates/src/components/GenericTemplate/GenericTemplateClean.tsx
> +  TemplateWrapper: Fragment,
can you add a note abou why we need 2 wrappers so that when we come back to document this package we'll know what it's for?

2022-05-19 08:59 UTC, wodenx commented on packages/vital-test/src/shadow/@bodiless/vital-card/Card.ts
> +const Default = asFluidToken({
shouldn't this be asCardToken not asFluidToken?

2022-05-19 09:10 UTC, wodenx commented on packages/vital-test/src/shadow/@bodiless/vital-elements/FontSize.ts
> +const OverrideFontSize = asTokenGroup(FontSizeMeta)({
Let's talk about using asTokenGroup here.  I don't like exporting and reusing all that meta.

2022-05-19 09:27 UTC, wodenx commented on packages/vital-test/src/shadow/@bodiless/vital-image/Img.ts
> +    _: addProps({ 'data-shadowed-by': '__vital__:Image' }),
We are overridign the Behavior domain entirely here - not sure that's a good idea.  In general, if you are just adding (not replacing) then it's better to do 
```
const Default = asImageToken(vitalImageBase.Default, {
  ...
  })
  ```
then you won't lose anything if it gets added underneath.

2022-05-19 09:28 UTC, wodenx commented on packages/vital-test/src/shadow/@bodiless/vital-layout/Footer.ts
> +    Wrapper: addProps({ 'data-shadowed-by': '__vital__:Footer' }),
We're overriding the wrapper entirely here. See above.

2022-05-19 09:28 UTC, wodenx commented on packages/vital-test/src/shadow/@bodiless/vital-layout/Header.ts
> +    Wrapper: addProps({ 'data-shadowed-by': '__vital__:Header' }),
Probably extend ratehr than overriding.

2022-05-19 09:30 UTC, wodenx commented on packages/vital-test/src/shadow/@bodiless/vital-layout/Layout.ts
> +    OuterContainer: addProps({ 'data-shadowed-by': '__vital__:Layout' }),
extend don't override and don't use Components domain.

2022-05-19 09:30 UTC, wodenx commented on packages/vital-test/src/shadow/@bodiless/vital-layout/Logo.ts
> +    Wrapper: addProps({ 'data-shadowed-by': '__vital__:Logo' }),
extend don't override and don't use Components domain.

2022-05-19 09:31 UTC, wodenx commented on packages/vital-test/src/shadow/@bodiless/vital-link/Link.ts
> +    Wrapper: addProps({ 'data-shadowed-by': '__vital__:Link' }),
extend don't override and don't use Components domain.

2022-05-19 09:31 UTC, wodenx commented on packages/vital-test/src/shadow/@bodiless/vital-list/List.ts
> +const Default = asFluidToken({
asListToken

2022-05-19 09:31 UTC, wodenx commented on packages/vital-test/src/shadow/@bodiless/vital-link/Link.ts
> +const Default = asFluidToken({
asLinkToken

2022-05-19 09:31 UTC, wodenx commented on packages/vital-test/src/shadow/@bodiless/vital-layout/Logo.ts
> +const Default = asFluidToken({
asLogoToken

2022-05-19 09:32 UTC, wodenx commented on packages/vital-test/src/shadow/@bodiless/vital-layout/Layout.ts
> +const Default = asFluidToken({
asLayoutToken

2022-05-19 09:32 UTC, wodenx commented on packages/vital-test/src/shadow/@bodiless/vital-list/List.ts
> +    _: addProps({ 'data-shadowed-by': '__vital__:List' }),
extend don't override and don't use Components domain.

2022-05-19 09:32 UTC, wodenx commented on packages/vital-test/src/shadow/@bodiless/vital-list/TitleInfographic.ts
> +    Wrapper: addProps({ 'data-shadowed-by': '__vital__:TitleInfographic' }),
extend don't override and don't use Components domain.

2022-05-19 09:32 UTC, wodenx commented on packages/vital-test/src/shadow/@bodiless/vital-list/TitleInfographic.ts
> +const Default = asFluidToken({
asTitleInfographicToken

2022-05-19 09:34 UTC, wodenx commented on packages/vital-test/src/shadow/@bodiless/vital-navigation/BurgerMenu.ts
> +const Default = asFluidToken({
asBurgerMenuToken

2022-05-19 09:34 UTC, wodenx commented on packages/vital-test/src/shadow/@bodiless/vital-navigation/BurgerMenu.ts
> +    Wrapper: addProps({ 'data-shadowed-by': '__vital__:BurgerMenu' }),
extend don't override and don't use Components domain.

2022-05-19 09:35 UTC, wodenx commented on packages/vital-test/src/shadow/@bodiless/vital-navigation/Menu.ts
> +  Core: {
Good example of extending

2022-05-19 09:36 UTC, wodenx commented on packages/vital-test/src/shadow/@bodiless/vital-navigation/Menu.ts
> +  Core: {
Another pattern, i fyou like it better, is composing:
```
const TopNav = asMenuTOken({
  ...vitalMenuBase,
   Compose: {
     ...vitalMenuBase.Compose,
      WithShadow: ...
     }
     ```
     or even combine them
```
     const TopNav = asMenuToken(vitalMenuBase.TopNav, {
       Compose: {
         WithShadow: ...
       ```

2022-05-19 09:39 UTC, wodenx commented on packages/vital-test/src/shadow/@bodiless/vital-navigation/MenuTitle.ts
> +const Default = asFluidToken({
asMenuTitleTOken

2022-05-19 09:39 UTC, wodenx commented on packages/vital-test/src/shadow/@bodiless/vital-navigation/MenuTitle.ts
> +    _: addProps({ 'data-shadowed-by': '__vital__:MenuTitle' }),
extend don't override and don't use Components domain.

2022-05-19 09:39 UTC, wodenx commented on packages/vital-test/src/shadow/@bodiless/vital-navigation/Separator.ts
> +const FooterMenu = asFluidToken({
asFooterToken

2022-05-19 09:39 UTC, wodenx commented on packages/vital-test/src/shadow/@bodiless/vital-navigation/Separator.ts
> +    _: addProps({ 'data-shadowed-by': '__vital__:FooterMenuSeparator' }),
extend don't override

2022-05-19 09:41 UTC, wodenx commented on packages/vital-test/src/shadow/@bodiless/vital-navigation/SubMenu.ts
> +    _: addProps({ 'data-shadowed-by-2': '__vital__:FooterSubMenu' }),
This is incorrect - `Compose` domain doesn't take design keys, it takes token names, so this should be
```
Compose: {
  WithShadow: addProps(...). // or use whatever name you want, but not _
 
```

2022-05-19 09:42 UTC, wodenx commented on packages/vital-test/src/shadow/@bodiless/vital-templates/GenericTemplate.ts
> +    TemplateWrapper: flowHoc(
extend don't override?

2022-05-19 09:44 UTC, wodenx commented
There are a lot of places where you override domains where I think you should be extending, and where you use asFluidToken instead of the component specific helper.  I flagged a bunch of them, but probably missed some.

2022-05-19 09:44 UTC, wodenx requested changes
See comments.

2022-05-19 14:52 UTC, hvanyo commented on packages/vital-test/src/shadow/@bodiless/vital-image/Img.ts
> +const Default = asFluidToken({
Resolved

2022-05-19 14:54 UTC, hvanyo commented on packages/vital-test/src/shadow/@bodiless/vital-layout/Footer.ts
> +    Wrapper: addProps({ 'data-shadowed-by': '__vital__:Footer' }),
Resolved

2022-05-19 14:58 UTC, hvanyo commented on packages/vital-test/src/shadow/@bodiless/vital-list/List.ts
> +const Default = asFluidToken({
Resolved

2022-05-19 14:59 UTC, hvanyo commented on packages/vital-test/src/shadow/@bodiless/vital-link/Link.ts
> +const Default = asFluidToken({
resolved

2022-05-19 14:59 UTC, hvanyo commented on packages/vital-test/src/shadow/@bodiless/vital-layout/Logo.ts
> +const Default = asFluidToken({
Resolved

2022-05-19 14:59 UTC, hvanyo commented on packages/vital-test/src/shadow/@bodiless/vital-layout/Layout.ts
> +const Default = asFluidToken({
Resolved

2022-05-19 15:00 UTC, hvanyo commented on packages/vital-test/src/shadow/@bodiless/vital-list/TitleInfographic.ts
> +const Default = asFluidToken({
Resolved

2022-05-19 15:01 UTC, hvanyo commented on packages/vital-test/src/shadow/@bodiless/vital-navigation/BurgerMenu.ts
> +const Default = asFluidToken({
resolved

2022-05-19 15:02 UTC, hvanyo commented on packages/vital-test/src/shadow/@bodiless/vital-navigation/MenuTitle.ts
> +const Default = asFluidToken({
resolved

2022-05-19 15:04 UTC, hvanyo commented on packages/vital-test/src/shadow/@bodiless/vital-navigation/Separator.ts
> +const FooterMenu = asFluidToken({
actually I think it should ahve been asElementToken...

2022-05-19 22:25 UTC, hvanyo commented on packages/__vital__/src/shadow/@bodiless/vital-templates/Page.ts
> +    _default: on(GenericTemplateClean)(vitalGenericTemplate.Default),
@wodenx  I was just cleaning this up and matching what will becoming in i18n/search pr..  It seemed easier than fighting with merge conflicts with deleted file..

2022-05-19 22:48 UTC, hvanyo commented on packages/vital-meta/src/components/MetaHelmet/index.ts
> +export * from './tokens/vitalMetaHelmet';
I had a whole list of meta fields to export.  Commented in code why its needed.

2022-05-20 14:43 UTC, hvanyo commented on packages/vital-test/src/shadow/@bodiless/vital-image/Img.ts
> +const Default = asFluidToken({
Addressed

2022-05-20 14:44 UTC, hvanyo commented on packages/vital-elements/src/components/Spacing/tokens/index.ts
> +export { SpacingMeta };
Discussed to leave 'as-is' for now on standup

2022-05-20 14:44 UTC, hvanyo commented on packages/vital-test/src/shadow/@bodiless/vital-elements/FontSize.ts
> +const OverrideFontSize = asTokenGroup(FontSizeMeta)({
Discussed to leave 'as-is' for now on standup

2022-05-20 19:29 UTC, wodenx commented on packages/vital-elements/src/util/tokenSpec.ts
> +const asSimpleMetaFieldToken = (...tokens: Token[]) => asElementToken({
Sorry if I misled - I think this should just be called `asSimpleToken` -- it doesn't have anything to do with meta

2022-05-20 22:48 UTC, wodenx submitted a review, later dismissed

2022-05-22 11:15 UTC, wodenx approved these changes

2022-05-24 20:11 UTC, wodenx approved these changes

2022-05-26 18:08 UTC, wodenx approved these changes

2022-05-26 18:26 UTC, misterjones approved these changes

2022-05-26 18:28 UTC, merged