feat: add knapsack renderer
johnsonandjohnson/Bodiless-JS pull request #1993
Opened 2023-03-03 20:07 UTC by EvanLovely

Recreates #1605 

## Changes

- Includes this PR and likely makes that PR not needed as some requested changes have been made on this branch: https://github.com/johnsonandjohnson/Bodiless-JS/pull/1605
- Adds Knapsack site to `sites/knapsack`
- Adds the `cardSpec` export to `packages/card` - however there have been type changes to `TokenCollection` which is used in `KnapsackBodilessSpec` (which is what `cardSpec` is) that are failing. I'll need Chris Oden to make any updates to this as we had it working when we were using `@bodiless/fclasses@ks-canary`
- The package `@bodiless/knapsack-renderer` version has been changed from `3.33.4` to `1.0.0-beta.7` in order to line up with rest of repo's package versions.

## Test Instructions

```bash
cd sites/knapsack
npm start
```

## Related Issues

2023-03-15 17:06 UTC, VancheeZze requested changes
Awesome work! Looks good! Just a few minor commennts

2023-03-15 17:06 UTC, VancheeZze commented on packages/knapsack-renderer/src/renderer-bodiless.ts
> +      path: '@canvasx/elements',
Wonder if any of the Bodiless packages should refer to any of the `@canvasx` packages. cc @wodenx

2023-03-17 18:19 UTC, EvanLovely commented on packages/knapsack-renderer/package.json
> +  "version": "3.33.4",
Version has been updated to be in-line

2023-03-17 18:19 UTC, EvanLovely commented on packages/knapsack-renderer/package.json
> +  "license": "GPL-2.0-or-later",
Changed the license

2023-03-17 18:20 UTC, EvanLovely commented on packages/knapsack-renderer/readme.md
I am not sure how the `bodiless.docs.json` work - feel free to add it to the package to get your docs site building like you'd like. I did rename `readme.md` to `README.md` and added the basic info you asked for though.

2023-03-17 18:24 UTC, EvanLovely commented
- Since the work is now in @wodenx's [fork](https://github.com/wodenx/Bodiless-JS) there has been a new PR made: #2008

2023-04-06 17:33 UTC, EvanLovely commented
- Superseded by #2008

2023-04-06 17:33 UTC, closed without merging