docs(bodiless-documentation): Add Shadowing Tutorial
johnsonandjohnson/Bodiless-JS pull request #2062
Opened 2023-05-04 13:37 UTC by misterjones

## Changes

- Add "Shadowing Tokens" page.
  - Update ToC with page.

## Related Issues

Fixes #2061

2023-05-04 13:59 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +**File `./lib/components/Foo/tokens/yourFoo.js`:**
For these examples, I've replaced "vital" with "your" to make the files/components more general (e.g., `vitalFoo` -> `yourFoo`).

Do we think that replacing it with "brand" would be better? (E.g., `brandFoo`)

2023-05-04 14:44 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +  **File [`vital-layout/src/components/Footer/tokens/vitalFooter.ts`][]:**
I've provided these examples of the Vital Footer from the codebase to provide some "real world" cases to compare against the generalized examples above.

The import/export structure in these snippets differs from that used in the general examples.

- Are the patterns used in the general examples out of date, or are they just alternate patterns?
- Should the general examples be updated to match the patterns used in Vital Footer?

2023-05-04 16:32 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +    import { yourFooBase } from 'base-package';
Should this line include importing `asFooToken`?

I.e.:
```js
import { yourFooBase, asFooToken } from 'base-package';
```

2023-05-04 16:38 UTC, misterjones commented
Hi, @hvanyo and @wodenx:

I've pushed this draft to get things rolling.

- I've taken the "Shadowing Vital Tokens" page and am using it as a baseline for a generalized page on shadowing.
  - I'm filling it with details from our tech talk and other sources.
- It's littered with TODOs that I'm filling in.
- I've added some questions for you via comments.

More is coming...

2023-05-12 16:43 UTC, marcopagliarulo commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +[`vital-test`](https://github.com/johnsonandjohnson/Bodiless-JS/tree/main/packages/vital-test/src/shadow/%40bodiless)
Please note that vital-test is being renamed to vital-demo in scope of feat/upgrade.

2023-05-12 16:43 UTC, marcopagliarulo commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +consumers to extend it. You may do this by exporting the tokens from their original location,
This sentence must be refactored, because every Base token from a package must be exported from the same file named 'Base.ts'

You can find a description here 
https://github.com/johnsonandjohnson/Bodiless-JS/blob/upgrade/next/packages/vital-elements/doc/Shadow.md, 

> The "base" version must be exported from a file which is never reexported by the package main or any other file, in order to prevent cycle dependency. As convention, Bodiless exports the base tokens as a named export from a file named base.ts

2023-05-12 16:43 UTC, marcopagliarulo commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +  import vitalFooterBaseOrig, { VitalFooter } from './tokens/vitalFooter';
Please refer to https://github.com/johnsonandjohnson/Bodiless-JS/blob/upgrade/next/packages/vital-elements/doc/Shadow.md for the new way to export base token.

2023-05-12 16:43 UTC, marcopagliarulo commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +  // Use this version of the Vital Footer tokens when extending or shadowing.
you can override existing bits of the token, or even extends it.

2023-05-15 17:38 UTC, VancheeZze approved these changes
Such a great detailed documentation! Great job! Aside from the Marco's comments looks good to me. Approving for now!

2023-05-15 19:10 UTC, hvanyo commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +    !> **IMPORTANT:** When defining your shadowed token collection, **always use the base token
This one is going to turn more into convention than a requirement..    
import { yourFooBase } from 'base-package/lib/base';   and we recommend using "yourFooBase" for otken to designate this specifcally is special import for shadowing and by doing  'base-package/lib/base' we avoid the rescursive blah....

2023-05-15 19:12 UTC, hvanyo commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +    - You can provide more than one resolver because you can have multiple packages doing shadowing.
@misterjones  @marcopagliarulo 
 This will need to be broken into 2 sections
1) how to do gatsby site
2) how to do nextjs site -- do we have instructions how to do this for nextjs site yet @marcopagliarulo

2023-05-15 19:18 UTC, hvanyo commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +There may be instances where there are components within a token collection that you don't wish to
```suggestion
There may be instances where there are domains within a token collection that you don't wish to
```

2023-05-15 19:18 UTC, hvanyo commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +utilize. Via shadowing, you can use the `omit` function to remove components from a token
```suggestion
utilize. Via shadowing, you can use the `omit` function to remove domains from a token
```

2023-05-15 21:59 UTC, hvanyo commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +There may be instances where there are components within a token collection that you don't wish to
@misterjones  I have never used omit to remove Components, does this work?  :)

2023-05-15 22:13 UTC, hvanyo commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +There may be instances where there are components within a token collection that you don't wish to
@marcopagliarulo @VancheeZze  does this work?  I thought omit was used primarily for domains.
and in the example below is "Bar" the slot?  If so then we should call it slot rather than component.  or what is Bar?

2023-05-15 22:13 UTC, hvanyo commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +- If, in a Vital token, we have `TokenX = asFooterToken(Default, {})`, and your site shadows
Add tip:

ensure you are shadowing the correct token.    Ie..  Header & Footer use specific tokens -> https://github.com/johnsonandjohnson/Bodiless-JS/blob/main/packages/vital-navigation/src/components/Menu/tokens/vitalMenu.ts#L216-L218 and not just the Default.  A Default is a simple unlstyled menu with sublist (ul/li) and no styling.

2023-05-16 16:51 UTC, samlynndavis submitted a review, later dismissed

2023-05-16 17:16 UTC, dewen commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +A site [created with `new-vds`](../SiteCreation) meets these requirements.
=> `BuildingSites/SiteCreation` ?

2023-05-16 18:33 UTC, dewen commented on packages/vital-elements/doc/Shadow.md
> +**File `./lib/index.ts`:**
should this be from `./src/index.ts`?

2023-05-16 18:59 UTC, dewen commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +[`vital-demo/src/shadow/@bodiless/vital-editors`](https://github.com/johnsonandjohnson/Bodiless-JS/tree/main/packages/vital-demo/src/shadow/%40bodiless/vital-editors),
`/package/vital-demo/src/shadow/@bodiless/vital-editors`
to differentiate from `/sites/vital-demo/src/...`

2023-05-16 19:23 UTC, dewen commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +located within a package at `./lib/components/{ComponentName}/tokens`, and this module must itself
`./src/components/{ComponentName}/tokens`

2023-05-16 19:26 UTC, dewen commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +export { default as yourFooBase } from './components/Foo/tokens/yourFoo';
Can have multiple component exports?
```
...
export { default as yourFooBase } from './components/Foo/tokens/yourFoo';

export { default as yourBarBase } from './components/Bar/tokens/yourBar';
...

```

2023-05-16 19:32 UTC, dewen commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +
`yourFoo.ts` might export all Base and {Variant} tokens, i.e.

```
import { Base } from `./Base`;
import { Variant1 } from `./Variant1`;
import { Variant2 } from `./Variant2`;

...

export default {
  Base,
  Varian1,
  Variant2,
  ...
}

2023-05-17 06:51 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +
✅ Note added.

2023-05-17 06:52 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +
✅ Updated code snippet.

2023-05-17 06:52 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +export { default as yourFooBase } from './components/Foo/tokens/yourFoo';
Good call.

✅ Updated code snippet.

2023-05-17 06:58 UTC, misterjones commented on packages/vital-elements/doc/Shadow.md
> +**File `./lib/index.ts`:**
All the examples in this section of this page use `./lib/...`, so I left it.
I changed the examples in the new page to use `./src/...`, as I found it less confusing.

The new page (`Shadowing.md`) covers everything discussed in this page, so I think we may just remove this page anyway.

2023-05-17 07:15 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +There may be instances where there are components within a token collection that you don't wish to
@hvanyo I can't confirm whether it works or not, but I took the pattern from ["Removing Components from Vital Rich Text Editor by Shadowing"](https://johnsonandjohnson.github.io/Bodiless-JS/#/VitalDesignSystem/Components/VitalEditors/RichTextCustomizing?id=removing-components-from-vital-rich-text-editor-by-shadowing).
So, I just assumed that it worked, haha. 😄

2023-05-17 15:23 UTC, marcopagliarulo commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +!> **IMPORTANT: The `base.ts` file should _only_ export a token collection.** As shadowing replaces
is not base.ts which should only export a token collection, is the index.ts inside tokens which should only export a token collection

2023-05-17 15:23 UTC, marcopagliarulo commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +?> **Note:** This _double export_ (e.g., `yourFoo` and `yourFooBase`) is required to avoid
I think this note could create some confusion, it looks like referencing the previous approach which performed the double export from the tokens themselves. I think we must make always clear these two exports happen from different files.

2023-05-17 15:23 UTC, marcopagliarulo commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +    - You can provide more than one resolver because you can have multiple packages doing shadowing.
for next site 
In your site's next.config.js 
`    const NextWebpackConfig = require('@bodiless/next/lib/cjs/Webpack/Config').default;
    const bodilessNextConfig = require('@bodiless/next/lib/cjs/NextConfig/nextConfig');
    const { addTokenShadowPlugin } = require('@bodiless/webpack');
    const shadow = require('shadowing-package/shadow');
    const shadow2 = require('lower-priority-shadowing-package/shadow');
    
    module.exports = {
      ...bodilessNextConfig,
      webpack: (config, options) => {
        let nextConfig = NextWebpackConfig(config, {
          nextWebpack: options
        });
        nextConfig = addTokenShadowPlugin(nextConfig, { resolvers: [shadow, shadow2] });

        return nextConfig;
      }
    }
`

2023-05-17 15:23 UTC, marcopagliarulo commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +    - An example `gatsby-node.js` file using the token shadow plugin can be found in the Vital site
you can reference `/sites/__vital_next__/next.config.js` for nextjs example

2023-05-17 16:12 UTC, marcopagliarulo commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +There may be instances where there are components within a token collection that you don't wish to
Technically it should work, I agree we should use the proper name.

2023-05-17 16:12 UTC, marcopagliarulo commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +  01. Restart Gatsby Dev via `npm run start`;
I'd change to _Restart your site in Dev mode_ since now we supports gatsby and nextjs

2023-05-17 16:12 UTC, marcopagliarulo commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +- A good way to confirm that your shadowed component is working is to shadow a behavior and add a
This is a repetition of Testing Shadowed Tokens, do we need it?

2023-05-17 20:24 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +    !> **IMPORTANT:** When defining your shadowed token collection, **always use the base token
✅ Turned "Important" block into a "Note" block, and rewrote language from a _requiring_ tone to a _recommending_ one.

2023-05-17 20:25 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +- If, in a Vital token, we have `TokenX = asFooterToken(Default, {})`, and your site shadows
✅ Tip added.

2023-05-17 20:28 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +[`vital-demo/src/shadow/@bodiless/vital-editors`](https://github.com/johnsonandjohnson/Bodiless-JS/tree/main/packages/vital-demo/src/shadow/%40bodiless/vital-editors),
Good call.

✅ Updated, and double-checked rest of doc for similar instances.

2023-05-17 20:29 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +located within a package at `./lib/components/{ComponentName}/tokens`, and this module must itself
✅ Fixed.

2023-05-17 20:32 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +?> **Note:** This _double export_ (e.g., `yourFoo` and `yourFooBase`) is required to avoid
Yes, good call — this _was_ from the previous approach.

✅ Removed Note block — contained misleading and duplicate information.

2023-05-17 20:33 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +    - An example `gatsby-node.js` file using the token shadow plugin can be found in the Vital site
✅ Added code sample for Next.js `next.config.js` file.
✅ Added link to `next.config.js` example.

2023-05-17 20:47 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +  01. Restart Gatsby Dev via `npm run start`;
✅ Updated.

2023-05-17 20:49 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +- A good way to confirm that your shadowed component is working is to shadow a behavior and add a
I added it, because I imagined someone coming to skim the "Tips" section and not necessarily reading the "Testing" section.
But, I agree: it's overly repetitive.

✅ Updated: gives basic tip and links to "Testing" section.

2023-05-18 17:02 UTC, wodenx requested changes

2023-05-23 05:38 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +of shadowing is: providing a token that replaces the existing design token. Whether you extend or
✅ Updated.

2023-05-23 05:39 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +Bodiless provides a mechanism to extend or override the tokens provided by a package, changing their
✅ Updated.

2023-05-23 05:41 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +override the token by shadowing is a choice made by the Site Builder. This method is similar to
✅ Updated.

2023-05-23 05:42 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +we're technically talking about is shadowing the token collections _of_ those components or
✅ Updated.

2023-05-23 05:42 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +Let's say you make changes to an H3 element token, shadowing the typography. For our example, we'll
✅ Updated.

2023-05-23 05:45 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +typography in one place and it gets automatically applied to everything.
I think it would be, yes.

I've added a TODO, and will get assistance on adding code snippets showcasing shadowing vs. a chain of imports.

2023-05-23 05:57 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +The [Vital Design System](/VitalDesignSystem/) provides many shadowable components, each of which
✅ Updated.

I chose to simply say "many," because I wanted to avoid implying that _all_ the token collections in Vital were shadowable, as I wasn't certain about the absolute extent of shadowability across the Vital system.

2023-05-23 05:59 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +via the [`new-vds` command](./BuildingSites/SiteCreation).
I'm not sure. I'll investigate when I get a chance. 👍

2023-05-23 06:10 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +    **File `./src/shadow/base-package/Foo.ts`:**
✅ Updated `yourFoo.ts` example to be simpler.

❓ Regarding `src/shadow/base-package/Foo.ts` — From previous feedback, I'd updated this snippet because we were moving _to_ the pattern of importing `yourFooBase` from `base-package/lib/base`. Is that incorrect?
Or is that not the pattern to which you're referring?

❓ If we are moving to the simpler version you described, will the overridden/extended tokens still be defined in this file, or will they be defined elsewhere?

2023-05-23 06:10 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +    files into your package root, and it will work.
✅ Updated.

2023-05-23 06:11 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +
✅ Updated.

2023-05-23 06:11 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +you wish to remove or rewrite them. _Overriding_ a token collection allows you to completely
✅ Updated.

2023-05-23 06:11 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +Shadowing](/VitalDesignSystem/Components/VitalEditors/RichTextCustomizing#removing-components-from-vital-rich-text-editor-by-shadowing).
✅ Updated.

2023-05-23 06:19 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +  Behavior: {
I documented this pattern because it's what's used in `vital-demo` (e.g., [`vital-demo/src/shadow/@bodiless/vital-card/Card.ts`](https://github.com/johnsonandjohnson/Bodiless-JS/blob/upgrade/next/packages/vital-demo/src/shadow/%40bodiless/vital-card/Card.ts)).

I can document the pattern you've described if it's preferred.
If so, would the examples in `vital-demo` need to be updated as well?

cc: @hvanyo

2023-05-23 06:21 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +- Many of the code examples above show snippets of TypeScript files under a package's `src`
✅ Updated — linked to the "Component Template" page.

2023-05-23 06:21 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +- Above, we show the contents of the compiled JavaScript files containing the shadowed token
✅ Removed — that was a vestigial bullet point from a previous version of this page.

2023-05-23 06:22 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +  "exports": {
✅ Removed.

2023-05-23 06:22 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +- If you shadow an element that is a fragment by default, it won't appear.
✅ Updated.

2023-05-23 06:23 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +  `TokenX`.
✅ Updated.

2023-05-24 21:19 UTC, hvanyo approved these changes

2023-05-24 21:19 UTC, hvanyo approved these changes

2023-05-24 21:19 UTC, hvanyo approved these changes

2023-05-31 13:02 UTC, wodenx commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +typography in one place and it gets automatically applied to everything.
Can you add the todo?

2023-05-31 13:03 UTC, wodenx commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +via the [`new-vds` command](./BuildingSites/SiteCreation).
Did you investigate?  I think i'd prefer to play it safe and just say "use the @bodielss/cli new` command.

2023-05-31 13:08 UTC, wodenx commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +    **File `./src/shadow/base-package/Foo.ts`:**
What I mean is - we should implement the actual token extension in, eg 'src/components/Foo' and structure that like any other componeent directory, and then in the 'src/shadow/{your-package}/Foo.ts just have:
```
import { yourFoo } from '../../../components/Foo';
import { shadow } from '@bodiless/vital-elements';
export default shadow(yourFoo, 'YourPackage');
```

2023-05-31 13:10 UTC, wodenx commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +## Extending and Overriding Token Collections via Shadowing
I think we should remove this whole section - it's not really about shadowing, it's about extending -- we should add any relevannt content to the "extending and composing" guide (https://github.com/johnsonandjohnson/Bodiless-JS/blob/e0b032a47d17ac85bb1da2f11fc023c1e2cf6344/packages/vital-elements/doc/ExtendingAndComposing.md) and link to it from here.

2023-05-31 13:23 UTC, wodenx commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +  Behavior: {
We now (or shortly will) have a `shadow` utility which can be used for this purpose -- it's in one of Sam's PR's I think.   So let's document using that.

2023-05-31 13:25 UTC, wodenx commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +- Many of the code examples above show snippets of TypeScript files under a package's `src`
We should update the component template page in scope of Dewens scaffolding PR - some things have changed.  ccc @hvanyo @dewen

2023-05-31 13:47 UTC, wodenx commented on packages/bodiless-documentation/doc/Development/Guides/Shadowing.md
> +  - This issue is temporary, and we are removing instances of this pattern from the Vital packages.
I dont' think this is "temporary" -- the point is that if you shadow any token (token A) in a collection, and that token is used by another token in the same collection (token B), then the shadowed version will not automatically be applied in token B.  You have to recompose token B to use the new version of Token A.  eg
original:
```
const A = asFooToken({ /**/ });
const B = asFooToken({
  /* . */,
  Compose: {
    A,
   },
 }); 
  ```

shadow
```
const A = asFooToken({ vitalFooBase.A, /* extend A */ });
export default {
  ...vitalFooBase,
   A,
 };
 ```
 Then the shadowed version of vitalFoo.B will*not* apply the shadowed vitalFoo.A -- instead you have to do
```
const A = asFooToken({ vitalFooBase.A, /* extend A */ });
const B = asFooToken({
  ...vitalFooBase.B, 
   Compose: {
     ...vitalFooBase.B.Compose,
     // Apply our shadowed version of A to override the default.
     A,
  },
});
export default {
  ...vitalFooBase,
   A,
   B,
 };
 ```

2023-06-05 15:43 UTC, closed without merging