[WIP] docs(bodiless-documentation): JEPZ-314 - Shadwoing design elements
johnsonandjohnson/Bodiless-JS pull request #2085
Opened 2023-05-17 18:26 UTC by sdetarsojnj

2023-05-18 00:04 UTC, wodenx commented on packages/vital-examples/src/elements/styleguide/Examples/StyleguideExamples.tsx
> +/*
I dont think this should be part of the vital-examples package - we should put it in the same place as vitalStyleGuideTemplate - probably best ot create a new @bodiless/vital-styleguide package whcih has both StyleGuideTemplate and StyleGuideExamples.

2023-05-18 00:05 UTC, wodenx commented on packages/vital-examples/src/elements/styleguide/Examples/StyleguideExamples.tsx
> +/*
Or if that feels like too much work, we could put it in vital-elements, but i think there might be a dependency cycle.

2023-05-18 00:14 UTC, wodenx commented on packages/vital-examples/src/elements/styleguide/Page/StyleGuideTemplate/Typography.tsx
> +const vitalTypographyFlowContainer = asFluidToken({
I think it would be great to generate this automaticallly from the token collection much as we do for knapsack and for the snapshot tests.  cc @VancheeZze

2023-05-18 00:16 UTC, wodenx commented on packages/vital-examples/tailwind.config.js
> +      colors: {
Do we really want to extend the colors?   I thought we were replacing them.  Also - let's try to do the same thing here that we do with the shadowing - that is, put the custom tailwind config in the /src/{lesson-name} directory and use an env. var to determine which tailwind config to include.

2023-05-18 00:16 UTC, wodenx commented on sites/vital-examples/package.json
> +    "gatsby": "^4.11.2"
why are we adding gatsby?

2023-05-18 00:28 UTC, wodenx commented on sites/vital-examples/src/templates/template.jsx
> +import { graphql } from 'gatsby';
vital examples is now a nextjs site so we should not be including anything from gatsby,,,

2023-05-18 00:32 UTC, wodenx commented on packages/vital-examples/src/elements/README.md
> +# Learn how to Shadow Design Tokens
Actually - I don't see shadowing enabled anywhere in this example.  We should follow the pattern established in the 'shadowing' example: https://github.com/johnsonandjohnson/Bodiless-JS/tree/upgrade/next/packages/vital-examples/src/intro/shadowing (but of course shadow the bodiless packages)

2023-05-18 01:35 UTC, hvanyo commented on packages/vital-examples/src/elements/components/TextDecoration.ts
> +import { asTokenGroup, TextDecorationMeta } from '@bodiless/vital-elements';
example

2023-05-18 01:40 UTC, hvanyo commented on packages/vital-examples/src/elements/styleguide/Page/StyleGuideTemplate/Typography.tsx
> +const vitalTypographyFlowContainer = asFluidToken({
this is what vital does.  its not quite auto generated but little cleaner also makes them editable.  https://github.com/johnsonandjohnson/Bodiless-JS/blob/main/packages/vital-test/src/styleguide/Page/StyleGuideTemplate/Typography.tsx

2023-05-19 21:26 UTC, sdetarsojnj commented on packages/vital-examples/src/elements/styleguide/Examples/StyleguideExamples.tsx
> +/*
I added to vital-elements and it worked fine

2023-05-19 21:34 UTC, sdetarsojnj commented on packages/vital-examples/tailwind.config.js
> +      colors: {
i created the new file, however, don't really know how to setup the .env

2023-05-19 21:36 UTC, sdetarsojnj commented on sites/vital-examples/package.json
> +    "gatsby": "^4.11.2"
This was a leftover from the code i copied from lactaid package. I removed already.

2023-05-19 21:41 UTC, sdetarsojnj commented on packages/vital-examples/src/elements/README.md
> +# Learn how to Shadow Design Tokens
I updated the files to follow the mentioned pattern, but I have a question, why should we follow this pattern instead of just creating a file inside the shadow folder and extending it?

cc @VancheeZze

2023-05-21 11:13 UTC, wodenx commented on packages/vital-examples/src/elements/README.md
> +# Learn how to Shadow Design Tokens
It maintains consistency in how token collections are organized.  It also makes it easier for your shadowing tokens to be shadowed themselves (eg for a market to shadow brand tokens which themselves shadow core tokens).

2023-05-21 11:19 UTC, wodenx commented on packages/vital-examples/src/elements/styleguide/Page/StyleGuideTemplate/Typography.tsx
> +const vitalTypographyFlowContainer = asFluidToken({
@hvanyo  ok I was thinking something more automatic, like
```
const withTypographyVariations = generateStyleguideVariations(Span, vitalTypography)
```
which would just iterarte over all the tokens in the collection and generate a variation by applying each to the Span (which could be editable, or could just have some text).

2023-05-21 11:31 UTC, wodenx commented on packages/vital-examples/tailwind.config.js
> +      colors: {
We would have to change the tailwind config at the package root so that it re-exported the appropriate tw config from the lesson, something lke:
```
import lesson1config from './src.lesson1/tailwind.config';
import lesson2config from './src/lesson2/tailwind.config';
...

const twconfigs = {
  lesson1: lesson1config,
  lesson2: lesson2config,
   ...,
};

modules.exports = twconfigs[process.env.BODILESS_ACTIVE_EXAMPLE];
```
but better to find a way to use just wone env var for both shadowing and tailwind config...

   
if

2023-05-21 11:34 UTC, wodenx commented on packages/vital-examples/src/elements/styleguide/Examples/StyleguideExamples.tsx
> +/*
i meant that there could be. dependency cycle if we move the styleguide template there - but it's fine, we can create a separate ticket for that.

2023-05-22 12:16 UTC, wodenx commented on packages/vital-examples/src/customizing-design-tokens/components/Typography/tokens/exampleTypography.ts
> +const H1 = asElementToken(vitalTypographyBase.H1, {
I"m confused by this - why are we merging with vitalTypographyBase here?  Shouldn't we be overriding the core domain?  Also why are we changing th ecolor from `TextPrimaryHeaderCopy` to `TextPrimaryBrand`?

2023-05-22 12:21 UTC, wodenx commented on packages/vital-examples/src/customizing-design-tokens/components/Typography/tokens/exampleTypography.ts
> +export interface LessonTypographyComponents
Also this should not be called `LessongTypogrpahyComponents` - since it is not a set of components, i tis a set of tokens, and we agreed on `Example` not `Lesson`.  So probalby just `ExampleTypography` (if it is needed at all).

2023-05-22 12:21 UTC, wodenx commented on packages/vital-examples/src/customizing-design-tokens/components/Typography/tokens/exampleTypography.ts
> +  extends TokenCollection<{}, DefaultDomains> {
Not sure it should extend TokenCollection - cc @VancheeZze

2023-05-22 12:23 UTC, wodenx commented on packages/vital-examples/tailwind.config.js
> -  content: [
What's the reason for htis change?

2023-05-22 19:57 UTC, hvanyo commented on packages/vital-examples/src/customizing-design-tokens/README.md
> +```ts
This code example doesn't match your code..  I don't think you have to place the whole file..

I think you can give an excerpt:

`
const H2 = asElementToken({
  ...vitalTypographyBase.H2,
  Core: {
    _: as(vitalTextDecoration.ExtraBold, vitalFontSize.XXXL),
  },
});
`

You create a new H2 token that is composed of existing vital H2 by spreading and then replace the core domain with the new fontsize and text decoration.

2023-05-22 19:57 UTC, hvanyo commented on packages/vital-examples/src/customizing-design-tokens/components/Typography/tokens/exampleTypography.ts
> +    _: as(vitalTextDecoration.Normal, 'text-m-5xl lg:text-5xl'),
While this is correct, I think we would encourage them to shadow a new : vitalFontSize and add XXXXXL
So you can either do that (more work longer example) 
or just change H1 to vitalFontSize.XXXL  & H2 vitalFontSize.XXL
Your choice.

2023-05-22 22:02 UTC, hvanyo commented on packages/vital-examples/src/elements/styleguide/Examples/StyleguideExamples.tsx
> +/*
@sdetarsojnj  thought just having them vital-elements was working but it was not.
to continue moving forward, lets leave styleguide code within the vital-examples for now and will separate this out in a different ticket.  cc; @wodenx

2023-05-23 20:45 UTC, VancheeZze requested changes

2023-05-23 20:45 UTC, VancheeZze commented on packages/vital-elements/package.json
> +    "@bodiless/data": "^1.0.0-rc.37",
I don't see much changes in `vital-elements`. Do we need these changes in `package.json`? I'd prefer not to add extra packages to elements.

2023-05-23 20:45 UTC, VancheeZze commented on packages/vital-examples/src/customizing-design-tokens/components/TextDecoration/tokens/exampleTextDecoration.ts
> +export default asTokenGroup(TextDecorationMeta)({
Do you think it'd be beneficial to add a comment explaining why we do `asTokenGroup` and what does it mean?

2023-05-23 20:45 UTC, VancheeZze commented on packages/vital-examples/src/customizing-design-tokens/components/Typography/tokens/exampleTypography.ts
> +export default {
Also, I see that there is no `asTokenGroup` here as in the `exampleTextDecoration`. Is there a diff between these two exports or should we make them all be either just default or `asTokenGroup`?

2023-05-23 20:45 UTC, VancheeZze commented on packages/vital-examples/src/customizing-design-tokens/shadow/@bodiless/vital-elements/FontSize.ts
> +import { exampleTextDecoration } from '../../../components/TextDecoration';
I think this may be a typo — the filename is `FontSize`, but it exports `exampleTextDecoration`

2023-05-23 20:45 UTC, VancheeZze commented on packages/vital-examples/src/styleguide/Page/StyleGuideTemplate/index.ts
> +export const VitalDemoStyleGuideTemplate = {
Should not be Capitalized I think: `vitalDemoStyleGuideTemplate`. Also `_default` in token collection looks non-standard, we usually do `Default`.

2023-05-23 20:45 UTC, VancheeZze commented on packages/vital-examples/src/styleguide/Page/index.tsx
> +    _default,
Is this a styleguide specific pattern of adding components? Maybe we should use the `Compose` key here instead? cc: @wodenx

2023-05-24 20:42 UTC, hvanyo commented
@sdetarsojnj  can you edit this PR and change target branch to main.

2023-05-24 21:17 UTC, hvanyo approved these changes

2023-05-27 11:24 UTC, wodenx commented on packages/vital-examples/src/customizing-design-tokens/components/TextDecoration/__tests__/TextDecoration.test.tsx
> +import TextDecoration from '../tokens';
can we make this 
```
import { exampleTextDecoration } from '..';

2023-05-27 11:28 UTC, wodenx commented on packages/vital-examples/src/customizing-design-tokens/components/TextDecoration/__tests__/TextDecoration.test.tsx
> +const tokenCollection = TextDecoration as any as TokenCollection<any, DefaultDomains>;
Can you add a @TODO here to fix so that this cast is not necessary?

2023-05-27 11:30 UTC, wodenx commented on packages/vital-examples/src/customizing-design-tokens/components/Typography/__tests__/Typography.test.tsx
> +import Typography from '../tokens';
see above - i think it's better to import from `..`

2023-05-27 11:32 UTC, wodenx commented on packages/vital-examples/src/customizing-design-tokens/components/Typography/tokens/exampleTypography.ts
> +const TypographyMeta = {
We can't import this from vital-elements?

2023-05-27 11:33 UTC, wodenx commented on packages/vital-examples/src/customizing-design-tokens/components/Typography/tokens/exampleTypography.ts
> +const TypographyMeta = {
I see - it' snot exported, but it should be.  Can we fix this in vital-elements?

2023-05-27 11:34 UTC, wodenx commented on packages/vital-examples/src/customizing-design-tokens/shadow/@bodiless/vital-elements/TextDecoration.ts
> +export default exampleTextDecoration;
add `shadow` utility from Sam's pr. Maybe need to merge that first?

2023-05-27 11:35 UTC, wodenx commented on packages/vital-examples/src/customizing-design-tokens/shadow/@bodiless/vital-elements/Typography.ts
> +import { exampleTypography } from '../../../components/Typography';
add `shadow` utility from sam's pr.

2023-05-27 11:36 UTC, wodenx commented on packages/vital-examples/src/styleguide/Examples/StyleguideExamples.tsx
> +/**
Weren't we goign to move this to `vital-elements` rather than repeating it in every example?

2023-05-29 19:38 UTC, sdetarsojnj commented on packages/vital-examples/src/customizing-design-tokens/shadow/@bodiless/vital-elements/TextDecoration.ts
> +export default exampleTextDecoration;
i couldn't find the commit to cherry-pick this shadow function, but i used it anyway.
So the build will fail until i merge the code.

2023-05-29 19:39 UTC, sdetarsojnj commented on packages/vital-examples/src/customizing-design-tokens/components/Typography/tokens/exampleTypography.ts
> +const TypographyMeta = {
Ok, wasn't sure if i should change anything on the vital-elements packages, but already fixed.

2023-05-30 09:45 UTC, wodenx submitted a review, later dismissed

2023-05-30 13:39 UTC, hvanyo approved these changes

2023-05-30 13:39 UTC, hvanyo submitted a review, later dismissed

2023-05-30 15:27 UTC, VancheeZze approved these changes

2023-05-30 16:44 UTC, samlynndavis submitted a review, later dismissed

2023-05-31 00:51 UTC, VancheeZze submitted a review, later dismissed

2023-05-31 09:03 UTC, wodenx commented on packages/vital-examples/src/styleguide/Examples/StyleguideExamples.tsx
> +/**
NVM I created a separate ticket for this.

2023-05-31 09:04 UTC, wodenx commented on packages/vital-examples/src/customizing-design-tokens/shadow/@bodiless/vital-elements/TextDecoration.ts
> +export default exampleTextDecoration;
Let's get the PR with the shadow merged first then.

2023-05-31 09:08 UTC, wodenx approved these changes

2023-05-31 15:45 UTC, VancheeZze approved these changes

2023-05-31 15:53 UTC, dewen approved these changes

2023-05-31 16:02 UTC, merged