feat(core): Remove submit button from non-interactive forms.
johnsonandjohnson/Bodiless-JS pull request #564
Opened 2020-09-21 16:38 UTC by awm086

## Changes
- Remove submit button from non-interactive forms.

## Test Instructions
- see https://github.com/johnsonandjohnson/Bodiless-JS/issues/411

## Related Issues
- Fixes https://github.com/johnsonandjohnson/Bodiless-JS/issues/411

2020-09-22 13:49 UTC, hvanyo submitted a review, later dismissed
Pseudo approver for Ivan -- reviewed cypress changes.

2020-09-22 20:54 UTC, TatsianaMiraniuk requested changes

2020-09-22 20:54 UTC, TatsianaMiraniuk commented on cypress/integration/smokeTest/fileSubmenu_spec.js
> -    cy.xpath(historyFormSubmitButton)
@awm086 ,

I would suggest to check that the submit button doesn't exist anymore (won't appear in future as a result of  regression), so instead of removing that line, let's change it to
cy.xpath(historyFormSubmitButton)
   .should('not.exist')

2020-09-22 20:54 UTC, TatsianaMiraniuk commented on cypress/integration/smokeTest/fileSubmenu_spec.js
> -    cy.xpath(revertFormSubmitButton)
@awm086 ,

same as above. let's check that it doesn't exist:
.should('not.exist')

2020-09-22 20:54 UTC, TatsianaMiraniuk commented on cypress/integration/smokeTest/fileSubmenu_spec.js
> -  const historyFormSubmitButton = '//*[@aria-label="Context Submenu Form"]//*[@aria-label="Submit"]'
should be kept for the check described below

2020-09-22 20:54 UTC, TatsianaMiraniuk commented on cypress/integration/smokeTest/fileSubmenu_spec.js
> -  const revertFormSubmitButton = '//*[@aria-label="Context Submenu Form"]//*[@aria-label="Submit"]'
should be kept for the check described below

2020-09-24 15:29 UTC, TatsianaMiraniuk approved these changes

2020-09-25 13:32 UTC, VancheeZze approved these changes

2020-09-25 13:33 UTC, merged