feat(components): menu breadcrumbs
johnsonandjohnson/Bodiless-JS pull request #631
Opened 2020-10-27 06:31 UTC by beliayeu

## Changes

## Test Instructions

## Related Issues

2020-10-27 11:18 UTC, wodenx requested changes

2020-10-27 11:18 UTC, wodenx commented on packages/bodiless-organisms/src/components/Menu/MegaMenu.tsx
> +    Item: replaceWith(withOnlyProps('key', 'children')(React.Fragment)),
We use this pattern enough that maybe we should export a version of Fragment from fclasses that includes this withOnlyProps

2020-10-27 11:18 UTC, wodenx commented on packages/bodiless-organisms/src/components/Menu/MegaMenu.tsx
> +const withEmptyMenuMarkup = flow(
Again, can we create a generic version of this that works for all lists?

2020-10-27 14:42 UTC, wodenx commented
One thing I forgot - please add jsdoc for all exported functions.

2020-10-28 07:04 UTC, beliayeu commented on packages/bodiless-components/src/Breadcrumb/asBreadcrumb.tsx
> +        data: linkNode.data.href,
I had to choose what to couple to bodiless link schema. Decided to couple asBreadcrumb since it knows about link node keys and reads link nodes. Then the store knows nothing about link schema and bodiless nodes.

2020-10-28 09:09 UTC, beliayeu commented on packages/bodiless-organisms/src/components/Menu/SimpleMenu.tsx
> +const withEmptyMenuMarkup = flow(
I believe we can extract a hoc responsible for rendering cham-sublist as no markup
here is poc https://github.com/beliayeu/Bodiless-JS/compare/feat/breadcrumb-new...beliayeu:spike/chamsublist-clean-markup?expand=1

not sure there is opportunity to make
```
  withMenuDesign({
    Wrapper: replaceWith(Fragment),
  }),
```
generic

2020-10-28 09:12 UTC, beliayeu commented on packages/bodiless-components/src/Breadcrumb/asBreadcrumb.tsx
> +type LinkData = {
fixed in 1fdc900eb574feef3f00c53fc059d7ebe4986b94

2020-10-28 09:12 UTC, beliayeu commented on packages/bodiless-components/src/Breadcrumb/Breadcrumb.tsx
> +const Breadcrumb = flowRight(
fixed in 1fdc900eb574feef3f00c53fc059d7ebe4986b94

2020-10-28 09:27 UTC, beliayeu commented on packages/bodiless-components/src/Breadcrumb/Breadcrumb.tsx
> +        <BreadcrumbItem key={item.uuid}>
fixed in be98f03151a70c270de37371b74dde9b4d8c1078

2020-10-28 09:28 UTC, beliayeu commented on packages/bodiless-components/src/Breadcrumb/BreadcrumbStore.ts
> +      : `${window.location.protocol}//${window.location.host}`;
fixed in 1fdc900eb574feef3f00c53fc059d7ebe4986b94

2020-10-28 09:28 UTC, beliayeu commented on packages/bodiless-components/src/Breadcrumb/withBreadcrumb.tsx
> +export default withBreadcrumb;
fixed 1fdc900eb574feef3f00c53fc059d7ebe4986b94

2020-10-28 09:28 UTC, beliayeu commented on examples/test-site/src/components/Breadcrumbs/MenuBreadcrumbs.ts
> +    withRichtextPlainSerializer,
fixed in 1fdc900eb574feef3f00c53fc059d7ebe4986b94

2020-10-28 09:28 UTC, beliayeu commented on examples/test-site/src/components/Breadcrumbs/MenuBreadcrumbs.ts
> +  Separator: replaceWith(Span),
fixed in 1fdc900eb574feef3f00c53fc059d7ebe4986b94

2020-10-28 09:29 UTC, beliayeu commented on examples/test-site/src/components/Breadcrumbs/MenuBreadcrumbs.ts
> +const MenuBreadcrumbs = flow(
fixed in 1fdc900eb574feef3f00c53fc059d7ebe4986b94

2020-10-28 09:29 UTC, beliayeu commented on packages/bodiless-organisms/src/components/Menu/MegaMenu.tsx
> +    Item: replaceWith(withOnlyProps('key', 'children')(React.Fragment)),
fixed in 1fdc900eb574feef3f00c53fc059d7ebe4986b94

2020-10-28 10:32 UTC, beliayeu commented on packages/bodiless-components/src/Breadcrumb/Breadcrumb.tsx
> +const withFinalTrail = addProps({
the use case is to disable/enable a functionality for composed component

2020-10-28 12:06 UTC, beliayeu commented on packages/bodiless-organisms/src/components/Menu/MegaMenu.tsx
> +const withEmptyMenuMarkup = flow(
fixed in 66d61e966779d65c0ea82d0ace8af0516ff39397

2020-10-29 18:16 UTC, wodenx commented
Reissued with burger https://github.com/johnsonandjohnson/Bodiless-JS/pull/637

2020-10-29 18:16 UTC, closed without merging