Feat/comp selector clear
johnsonandjohnson/Bodiless-JS pull request #669
Opened 2020-11-06 20:55 UTC by awm086

## Changes

## Test Instructions

## Related Issues

2020-11-10 18:48 UTC, VancheeZze requested changes

2020-11-10 18:48 UTC, VancheeZze commented on packages/bodiless-layouts/src/ComponentSelector/types.tsx
> +  ComponentLinkWrapper: ComponentType<HTMLProps<HTMLAnchorElement> & LinkVariantProps> | string;
I think `HTMLAnchorElement ` already has `disabled` prop. We may be able to leverage that and get rid of `LinkVariantProps` here.

2020-11-10 18:48 UTC, VancheeZze commented on packages/bodiless-core/src/Types/ContextMenuTypes.tsx
> +  ComponentFormLink?: ComponentType<HTMLProps<HTMLAnchorElement> & LinkVariantProps> | string;
Since we use `ComponentFormLink` only as an `HTMLAnchorElement` we can get rid of `LinkVariantProps` and use `disabled` prop that `HTMLAnchorElement` provides by default.

2020-11-10 18:48 UTC, VancheeZze commented on packages/bodiless-layouts-ui/src/ComponentSelector.tsx
> + * Used instead of informed Checkbox for more concise handling.
What was the issue with the informed Checkbox? Was it something with resetting checked state?

2020-11-10 18:48 UTC, VancheeZze commented on packages/bodiless-ui/src/elements.tsx
> +  withoutProps<LinkVariantProps>(['isActive', 'isDisabled']),
We can remove this line too. No need to remove `disabled` prop from `ComponentType<HTMLProps<HTMLAnchorElement>>` and I don't see there is an `isActive` prop used anywhere.

2020-11-10 18:48 UTC, VancheeZze commented on packages/bodiless-layouts/src/ComponentSelector/index.tsx
> +              isDisabled={activeFilters.length === 0}
Since `ComponentLinkWrapper` is a link it has a `disabled` prop that we could use to simplify the code.

```js
<finalUI.ComponentLinkWrapper
  disabled={activeFilters.length === 0}
  onClick={...}
>
  Clear
</finalUI.ComponentLinkWrapper>
```

2020-11-10 18:50 UTC, awm086 commented on packages/bodiless-layouts-ui/src/ComponentSelector.tsx
> + * Used instead of informed Checkbox for more concise handling.
Yes. Chris suggested we rid of informed checkbox

2020-11-11 19:47 UTC, VancheeZze approved these changes

2020-11-13 19:10 UTC, TatsianaMiraniuk commented
@awm086 ,

please see **issue_1:**

**Steps to reproduce:**

1. open Component Picker
2. in Filter Section, click on any checkbox label, e.g  'image'

**Actual Result:**
image checkbox is not checked

**Expected Results:**
image checkbox is  checked

2020-11-13 19:27 UTC, VancheeZze submitted a review, later dismissed

2020-11-16 15:46 UTC, VancheeZze approved these changes

2020-11-17 18:11 UTC, wodenx approved these changes

2020-11-17 18:11 UTC, wodenx commented
Testing has passed.

2020-11-17 18:51 UTC, merged