fix(richtext): [GAP] 2 clicks are needed on a newly created menu item to open Local context menu #671
johnsonandjohnson/Bodiless-JS pull request #675
Opened 2020-11-10 13:52 UTC by marcopagliarulo

## Changes
Prevent the on change state handler to save the data when it is the initial value and it has not been changed.
Preventing the unnecessary write data resolved the double clicks required to focus a newly created menu item.
The default Value provided to the richtext editor is converted to a new object to prevent focus issues on multi instance slate when the default value is identical between instances.

## Test Instructions
//=== for a clean page===

1. Open /megamenu/ in Edit mode
2. Click a top menu item
**Expected Results:**
Local Context Menu is open.
 
//=== for a page that has content in Menu===
1. Open /megamenu/ in Edit mode
2. Click a top menu item
3. Click "+Add"
4. Click on the newly created item
**Expected Results:**
Local Context Menu is open.

## Related Issues
Fixes #671

2020-11-10 17:22 UTC, VancheeZze requested changes

2020-11-10 17:22 UTC, VancheeZze commented on packages/bodiless-richtext/src/useNodeStateHandlers.ts
> +      || !isEqual(document, jsonValue.document)))
This part works great, maybe we can simplify it. No need to reverse `newValueNotInitial` twice, it becomes harder to read. Instead, we could do something like this:
```js
// If Document has changed
const isDocumentChanged = !isEqual(document, jsonValue.document);

// If the value is initial value
const isNewValueInitial = isEqual(initialValue.document, jsonValue.document);

// If New Value is Empty
const isNewValueEmpty = isNewValueInitial && document && isDocumentChanged;

// If New Value Has Changes
const isNewValueChanged = !isNewValueInitial && (!document || isDocumentChanged);

if (isNewValueEmpty || isNewValueChanged) {
  node.setData({ document: jsonValue.document! });
}
```

2020-11-10 20:20 UTC, marcopagliarulo commented on packages/bodiless-richtext/src/useNodeStateHandlers.ts
> +      || !isEqual(document, jsonValue.document)))
Thanks @VancheeZze, your suggestion is definitely much better. Implemented and tested.

2020-11-11 14:02 UTC, VancheeZze approved these changes

2020-11-12 20:10 UTC, TatsianaMiraniuk approved these changes

2020-11-13 10:45 UTC, merged