feat(components, organisms): Menu Trails
johnsonandjohnson/Bodiless-JS pull request #697
Opened 2020-11-18 00:11 UTC by wodenx

## Changes
- Provide api to style active menu links
- Share breadcrumb provider across menu and breadcrumbs

## Changes

## Test Instructions

## Related Issues

2020-11-18 10:58 UTC, beliayeu approved these changes

2020-11-18 10:58 UTC, beliayeu commented on examples/test-site/src/components/Layout/index.tsx
> +      <BreadcrumbProvider>
a little bit concerning that in case a site decides to not render breadcrumbs, the menu should still be wrapped with breadcrumb provider in order to have active menu trail feature
but I guess that is ok

2020-11-18 10:58 UTC, beliayeu commented on examples/test-site/src/components/Layout/index.tsx
> -import React from 'react';
do we want to activate the same for starter? or is the plan to do it after the first round of review/testing?

2020-11-18 11:02 UTC, beliayeu commented on examples/test-site/src/components/Layout/index.tsx
> +      <BreadcrumbProvider>
does it work in ssr?

2020-11-18 11:11 UTC, wodenx commented on examples/test-site/src/components/Layout/index.tsx
> +      <BreadcrumbProvider>
Maybe we should rename it to MenuContextProvider or similar?

2020-11-18 17:02 UTC, beliayeu submitted a review, later dismissed

2020-11-18 18:43 UTC, wodenx commented on packages/bodiless-organisms/src/components/Menu/MenuTitles.tsx
> +  const store = useBreadcrumbStore();
fixed

2020-11-18 18:43 UTC, wodenx commented on examples/test-site/src/components/Layout/index.tsx
> +      <BreadcrumbProvider>
leaving as is - it's  site level thing, and on a site without breadcrumbs they can do the renaming themselves.

2020-11-18 18:43 UTC, wodenx commented on examples/test-site/src/components/Layout/index.tsx
> +      <BreadcrumbProvider>
fixed

2020-11-23 10:39 UTC, beliayeu requested changes
consider moving useLayoutEffect to the component top level in asBreadcrumb

2020-11-23 10:50 UTC, beliayeu submitted a review, later dismissed

2020-11-23 11:17 UTC, beliayeu approved these changes

2020-11-24 11:27 UTC, beliayeu submitted a review, later dismissed

2020-11-26 06:51 UTC, beliayeu requested changes
consider having 'Navigation Menu' aria-label only in nav element

2020-11-26 06:51 UTC, beliayeu commented on packages/bodiless-organisms/src/components/Menu/SimpleMenu.token.tsx
> +    <nav aria-label="Navigation Menu">
consider allowing to customize this element (add/change props to nav element for a component composed using asNav)

2020-11-26 06:51 UTC, beliayeu commented on packages/bodiless-organisms/src/components/Menu/SimpleMenu.token.tsx
> +  Wrapper: flow(asNav, addProps({ role: 'menubar', 'aria-label': 'Navigation Menu' })),
per my understanding 'Navigation Menu' aria-label will be added to 2 elements, so I think we should not remove it from here since it is added in asNav to nav element

2020-11-26 13:32 UTC, wodenx commented on packages/bodiless-organisms/src/components/Menu/SimpleMenu.token.tsx
> +  Wrapper: flow(asNav, addProps({ role: 'menubar', 'aria-label': 'Navigation Menu' })),
per @VancheeZze  best practice is to have it on both.
> w3.org suggest we use aria-label on both: nav and ul
> Here -- https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-1/menubar-1.html
> If you scroll down to "HTML Source Code", you'll find a quick example

2020-11-26 13:37 UTC, wodenx commented on packages/bodiless-organisms/src/components/Menu/SimpleMenu.token.tsx
> +    <nav aria-label="Navigation Menu">
Yes- I discussed this with @VancheeZze and he suggested a solution which i forgot to implement.
{code}
const asNav = <P extends object>(Component: ComponentType<P>) => {
  const Nav = (props: P) => (
    <nav aria-label={props['aria-label'] || 'Navigation Menu'}>
      <Component {...props} />
    </nav>
  );
  return Nav;
};
{code}
We thought making the nav designable would be overkill for this and couldnt think of another use-case.lmk if you agree and i'll fix it in a few minutes.

2020-11-26 15:15 UTC, beliayeu approved these changes

2020-11-30 08:28 UTC, beliayeu approved these changes

2020-11-30 15:28 UTC, hvanyo commented on examples/test-site/src/components/Menu/SimpleMenu.token.tsx
> +const withTitleStyles = addClasses('hover:bg-teal-500 block w-full px-3');
Can we switch hover:bg-teal-500, bg-teal-500 into tokens and import from elements.token.ts?   While you are in there tokenize bg-teal-600 as well.  It would make it easier to reuse for sites.

2020-11-30 15:35 UTC, hvanyo commented on packages/bodiless-organisms/src/components/Menu/MenuTitles.tsx
> + * This hook is only accurate if
This feels like important information that should be in README for menu.

2020-11-30 19:16 UTC, hvanyo commented on examples/test-site/src/data/site/MainMenu$dc9b6772-2aab-433c-ad84-d12841ebc981$sublist$797fef2f-8546-49c8-8316-f529209290c1$title$link-toggle.json
> -  "component": "Link"
Why is this changing to null?  

FYI: also noticed if you got to https://ztvjm4ms5m-jvaff4bu65vgm.us-2.platformsh.site/ -> Components | Breadcrumb is not linked and working.

2020-11-30 19:34 UTC, hvanyo commented
Expectation of parent active with columns -- would we expect title to get parent styling?
I feel like this is yes but callling it.

![2020-11-30_13-31-07](https://user-images.githubusercontent.com/58534559/100655305-b5f29780-3310-11eb-9787-e60f8610de19.jpg)

2020-11-30 19:45 UTC, hvanyo commented
Edge case..

I was testing adding the same link to multiple different menus to verify behavior. 
I got one active parent which is what I expect as seeing two parents active seems odd, so calling this passed. 

My question:  
What breadcrumb/ & parent gets chosen seems arbitrary? Do we know what takes precedence -- is there a pattern?  (latest added, etc? )  @beliayeu  @wodenx

2020-11-30 19:55 UTC, hvanyo commented on examples/test-site/src/components/Menu/SimpleMenu.token.tsx
> +);
I think its safe to bring these 3 styles into starter kit (with the hover & backgrounds as tokens).   As underline is defined and asBold is there with noclass.

2020-11-30 21:34 UTC, hvanyo commented
Burger Menu 

STR:
1. resize static to mobile and open the burger menu 

AR:
Placeholder in BM header
![2020-11-30_15-33-00](https://user-images.githubusercontent.com/58534559/100668436-87c98380-3321-11eb-88e1-7a43af01f4a7.jpg)

ER:
Logo in BM header

2020-12-01 10:17 UTC, wodenx commented on packages/bodiless-organisms/src/components/Menu/MenuTitles.tsx
> + * This hook is only accurate if
Docs for menus need to be updated, and new docs need to be added for breadcrumbs - I'd say we should make this change in scope of adding those.

2020-12-01 10:24 UTC, wodenx commented
> Expectation of parent active with columns -- would we expect title to get parent styling?
I feel like this is yes but callling it.

You could do it either way. My interpretation was that the main menu should get different styling from all submenus, but that all levels fo submenu should get the same styling.  Doing it the other way would be a little more complex, so i'd propose we skip it until we have a use-case.

2020-12-01 11:42 UTC, wodenx commented on examples/test-site/src/components/Menu/SimpleMenu.token.tsx
> +);
will do when i propagate changes to starter

2020-12-01 11:46 UTC, wodenx commented
> STR:
>resize static to mobile and open the burger menu
> AR:
> Placeholder in BM header

Fixed.

2020-12-01 11:46 UTC, wodenx commented on examples/test-site/src/data/site/MainMenu$dc9b6772-2aab-433c-ad84-d12841ebc981$sublist$797fef2f-8546-49c8-8316-f529209290c1$title$link-toggle.json
> -  "component": "Link"
Fixed.

2020-12-01 11:47 UTC, wodenx commented on examples/test-site/src/components/Menu/SimpleMenu.token.tsx
> +const withTitleStyles = addClasses('hover:bg-teal-500 block w-full px-3');
Fixed.

2020-12-01 12:03 UTC, beliayeu commented
> What breadcrumb/ & parent gets chosen seems arbitrary? Do we know what takes precedence -- is there a pattern? (latest added, etc? ) @beliayeu @wodenx

@hvanyo, the left/top-most item will take precedence
tech note: the first that is added to the store will take precedence, so the first rendered item

cc: @wodenx

2020-12-01 13:00 UTC, beliayeu submitted a review, later dismissed

2020-12-01 17:03 UTC, hvanyo commented
Platform.sh failed to deploy static env.

Locally

@bodiless/gatsby-starter-bodiless: failed Building static HTML for pages - 30.310s
@bodiless/gatsby-starter-bodiless:  ERROR #95313
@bodiless/gatsby-starter-bodiless: Building static HTML failed
@bodiless/gatsby-starter-bodiless: See our docs page for more info on this error: https://gatsby.dev/debug-html
@bodiless/gatsby-starter-bodiless: 
@bodiless/gatsby-starter-bodiless:   TypeError: Object(...) is not a function
@bodiless/gatsby-starter-bodiless:   
@bodiless/gatsby-starter-bodiless:   - render-page.js:112874 Module../src/components/Breadcrumbs/MenuBreadcrumbs.ts    /Users/heidivanyo/slate/bj-chris/examples/starter/public/render-page.js:1128    74:235

2020-12-01 17:35 UTC, hvanyo commented
```
cd examples/test-site
npm run build
```

get errro
```
Building static HTML failed

See our docs page for more info on this error: https://gatsby.dev/debug-html


  87 | );
  88 | 
> 89 | const asBreadcrumbSource = asSimpleMenuBreadcrumbSource({
     |                                                         ^
  90 |   linkNodeKey: 'title$link',
  91 |   titleNodeKey: 'title$text',
  92 | });


  WebpackError: TypeError: Object(...) is not a function
```

2020-12-02 11:31 UTC, beliayeu requested changes

2020-12-02 11:31 UTC, beliayeu commented on examples/starter/src/components/Layout/footer.tsx
> +          &nbsp;2019-
should we have it?

2020-12-02 12:38 UTC, beliayeu approved these changes

2020-12-02 13:49 UTC, hvanyo commented
@wodenx  need env search vars & additional changes to build search in scripts in package.json -> https://github.com/johnsonandjohnson/Bodiless-JS/pull/592/files#diff-c2efccef740df6c8bbf86730c29da522d1cf86f39bdc97ab54af38d32460243f

2020-12-02 15:24 UTC, beliayeu approved these changes

2020-12-02 15:53 UTC, hvanyo approved these changes

2020-12-02 16:29 UTC, merged