feat(migration-tools): create json files for scraped images
johnsonandjohnson/Bodiless-JS pull request #726
Opened 2020-11-27 13:57 UTC by dewen

## Changes

## Test Instructions

## Related Issues

2020-11-28 20:29 UTC, dewen commented on packages/bodiless-migration-tool/src/downloader.ts
> +          return req.pipe(fs.createWriteStream(targetPath));
previous on events seem to be applied in wrong place, moved to outer function.

2020-11-30 08:21 UTC, beliayeu requested changes
1. reconsider downloadFile onEvents
2. include picture tag support
3. consider adjusting migration api

2020-11-30 08:21 UTC, beliayeu commented on packages/bodiless-migration-tool/src/downloader.ts
> +          return req.pipe(fs.createWriteStream(targetPath));
@dewen, I believe we need to resolve promise once the file is written to file system
so finish, error events were attached to the stream

2020-11-30 08:21 UTC, beliayeu commented on packages/bodiless-migration-tool/src/migrationApi.ts
> +  url: string,
I think we already have getPagePath that serves this purpose

2020-11-30 08:21 UTC, beliayeu commented on packages/bodiless-migration-tool/src/migrationApi.ts
> +  getStaticPath: () => string,
I think it would be nice to provide ability to pass a resource url and get corresponding fs path

2020-11-30 08:21 UTC, beliayeu commented on packages/bodiless-migration-tool/src/plugins/imagetags.ts
> +  document('img')
do we want to support picture tag?

2020-11-30 08:21 UTC, beliayeu commented on packages/bodiless-migration-tool/src/plugins/imagetags.ts
> +            src: targetPath.replace(api.getStaticPath(), ''),
considering encapsulating this logic into api object
DX would be
```
src: api.getResourcePath(resourceUrl);
```

2020-11-30 08:21 UTC, beliayeu commented on packages/bodiless-migration-tool/tests/downloader.test.ts
> +    try {
do we need to have try/catch in tests?

2020-11-30 13:20 UTC, dewen commented on packages/bodiless-migration-tool/src/downloader.ts
> +        { concurrency: 1 },
that was a debug change, good catch

2020-11-30 13:30 UTC, dewen commented on packages/bodiless-migration-tool/src/downloader.ts
> +      return [...result, ...precheck.EXISTS];
i think it depends on what we expect on returns from downloadFiles. I typed it as 

```
type Downloaded = {
  targetPath: string;
  url: string;
};
```

For external url, there will be no saved path, not sure if we need to return, or purpose of that return.

2020-11-30 13:36 UTC, dewen commented on packages/bodiless-migration-tool/src/migrationApi.ts
> +  url: string,
@beliayeu I set the get for original page url value (with protocol and host name), might be different from page path.

It's used in packages/bodiless-migration-tool/src/plugins/imagetags.ts

2020-11-30 13:41 UTC, dewen commented on packages/bodiless-migration-tool/tests/downloader.test.ts
> +    try {
i added the catch to manually fail the test if download promise rejected.

2020-11-30 20:27 UTC, dewen commented on packages/bodiless-migration-tool/src/downloader.ts
> +          return req.pipe(fs.createWriteStream(targetPath));
Agreed, onEvents restored

2020-11-30 20:43 UTC, dewen commented on packages/bodiless-migration-tool/src/plugins/imagetags.ts
> +  document('img')
per discuss in chat, picture tag is not in scope. Current implementation will process img tag inside picture.

2020-12-01 00:42 UTC, dewen commented on packages/bodiless-migration-tool/src/migrationApi.ts
> +  getStaticPath: () => string,
It might depend on downloader configuration. I don't see there can be a direct map between resource url and saved path in migration API with actual download the file.

2020-12-01 00:42 UTC, dewen commented on packages/bodiless-migration-tool/src/plugins/imagetags.ts
> +            src: targetPath.replace(api.getStaticPath(), ''),
added getStaticRelativePath in this case.

2020-12-01 06:06 UTC, beliayeu submitted a review, later dismissed

2020-12-01 12:33 UTC, dewen commented on packages/bodiless-migration-tool/src/migrationApi.ts
> +  url: string,
updated with migrationApi pagePath

2020-12-01 12:52 UTC, beliayeu submitted a review, later dismissed

2020-12-01 21:08 UTC, wodenx approved these changes
All tests passed.

2020-12-02 08:31 UTC, beliayeu approved these changes

2020-12-02 14:35 UTC, merged