Feat/flow container rtl
johnsonandjohnson/Bodiless-JS pull request #775
Opened 2020-12-21 17:07 UTC by awm086

## Changes

## Test Instructions

## Related Issues

2020-12-22 16:45 UTC, VancheeZze requested changes

2020-12-22 16:45 UTC, VancheeZze commented on packages/bodiless-ui/src/elements.tsx
> +
I think it is better to re-use `ResizeHandle`:

```js
export const ResizeHandleRTL = flow(
  addClasses('bl-left-rem-1'),
  removeClasses('bl-right-rem-1'),
)(ResizeHandle);
```

Also, I'm not sure if we need `bl-bg-red-600` for the handle, was that per design?

2020-12-22 16:53 UTC, awm086 commented on packages/bodiless-ui/src/elements.tsx
> +
good catch.

2020-12-22 17:03 UTC, VancheeZze approved these changes

2021-01-06 14:39 UTC, TatsianaMiraniuk approved these changes

2021-01-06 14:40 UTC, merged