doc(bodiless-documentation): Architecture Intro
johnsonandjohnson/Bodiless-JS pull request #835
Opened 2021-02-04 07:35 UTC by misterjones

## Changes
- Add introduction to Architecture section, explaining the reasons for
  the architectural decisions that were made, as well as the benefits
  that come with them.

## Related Issues
Fixes #834

2021-02-06 00:47 UTC, hvanyo approved these changes

2021-02-06 00:48 UTC, hvanyo requested changes
Jones I think this should be first in Development tree.
Connect with @malachye  and you can tell you how to force that:  https://edit.ghrw7u3ebm-jvaff4bu65vgm.us-2.platformsh.site/___docs/#/Development/Architecture/

2021-02-10 20:38 UTC, misterjones commented on packages/bodiless-documentation/doc/Development/Architecture/README.md
> +experienced with other site-building platforms. These difficulties include:
✅ Updated.

See: a719dc0

2021-03-22 08:39 UTC, closed without merging

2021-03-22 08:39 UTC, wodenx commented
Closing as docs were moved elsewehre.