[WIP] feat(navigation, organisms, components): Better DX for Menu, Breadcrumbs, BurgerMenu
johnsonandjohnson/Bodiless-JS pull request #841
Opened 2021-02-08 18:45 UTC by VancheeZze

## Changes

## Test Instructions

## Related Issues

2021-03-02 13:29 UTC, wodenx commented on packages/bodiless-navigation/src/Menu.token.tsx
> +  meta.term('Layout')('Display'),
This should be 'Attribute': 'Display'

2021-03-02 13:29 UTC, wodenx commented on packages/bodiless-navigation/src/Menu.token.tsx
> +  meta.term('Layout')('Display'),
and ''Component": 'Element', and 'Category': 'Layout'

2021-03-02 13:35 UTC, wodenx commented on packages/bodiless-navigation/src/Menu.token.tsx
> +const asRelativeNotActive = asToken(
So - let's move all these element level tokens to a separate file - and why not create an "asElementToken" helper - like
const asElementToken = (Category, Attribute) => {
  categories: {
     Category: Array.isArray(category) ? category : [category],
   Attribute: Array.isArray(attribute) ? attribute : [attribuge],
     Component: ['Element']
   "

2021-03-02 13:36 UTC, wodenx commented on packages/bodiless-navigation/src/Menu.token.tsx
> +const asRelativeNotActive = asToken(
probalby we need a '@canvasx/tokens' package with this kind of stuff...

2021-03-02 13:39 UTC, wodenx commented on packages/bodiless-navigation/src/Menu.token.tsx
> +const asRelativeNotActive = asToken(
actually make tha tmore generic like
const withCanvasXMeta = (component) => (category) => (attribute) => {
  categories:
    Component: ...,
    Category: ...,
     Elemet: ...
{
and then

withElementMeta = asCanvasxToken('Element')

2021-03-02 13:40 UTC, wodenx commented on packages/bodiless-navigation/src/Menu.token.tsx
> +const asRelativeNotActive = asToken(
then you can just swap out all these 'asToken.meta' for 'withElementMeta'

2021-03-02 13:40 UTC, wodenx commented on packages/bodiless-navigation/src/Menu.token.tsx
> +const asFullWidthSublist = withDesign({
these tokens should have "List" as their component.  Need to discuss category and attribute.

2021-03-02 13:40 UTC, wodenx commented on packages/bodiless-navigation/src/Menu.token.tsx
> +    addClasses('w-full'),
should use an asWidthFull token here.

2021-03-02 13:42 UTC, wodenx commented on packages/bodiless-navigation/src/Menu.token.tsx
> +  Item: asToken(
I'd say all the element level tokens applied here should be defined independently.

2021-03-03 13:19 UTC, VancheeZze commented on packages/bodiless-navigation/src/Menu.token.tsx
> +  meta.term('Layout')('Display'),
Done

2021-03-03 13:19 UTC, VancheeZze commented on packages/bodiless-navigation/src/Menu.token.tsx
> +const asRelativeNotActive = asToken(
Implemented

2021-03-03 13:19 UTC, VancheeZze commented on packages/bodiless-navigation/src/Menu.token.tsx
> +const asFullWidthSublist = withDesign({
Done

2021-03-03 13:19 UTC, VancheeZze commented on packages/bodiless-navigation/src/Menu.token.tsx
> +    addClasses('w-full'),
Updated

2021-03-03 13:19 UTC, VancheeZze commented on packages/bodiless-navigation/src/Menu.token.tsx
> +  Item: asToken(
Done

2021-03-12 12:51 UTC, wodenx requested changes

2021-03-12 12:51 UTC, wodenx commented on packages/bodiless-navigation/src/BurgerMenu/asBurgerMenu.tsx
> +const withOverviewLink = (OverviewLink: ComponentType<any>) => {
I think if we make the change i proposed in how we add static items to the list, then this can becomr somerthing iike:
```
const withOverviewLink = (content: any = { text: 'Overview' }) => {
  const useOverviewLinkContent = () => {
    const { node } = useNode();
    const parentNodePath = node.path.slice(0, node.path.length - 1);
    const linkNode = node.peer<{ href: string }>([...parentNodePath, 'title', 'link']);
    return {
      overview$title$title: content,
      overview$title$link: linkNode.data, 
    };
  };
  return flow(
    addProps({ insertItems: ['overview'] }),
    withDefaultContent(useOverviewLinkContent),
  );
};
```

2021-03-12 12:51 UTC, wodenx commented on packages/bodiless-navigation/src/BurgerMenu/asBurgerMenu.tsx
> +const asBurgerMenu = (...keys: string[]) => asToken(
we need to expose the content of the overview link somehow.  If we use the pattern above, maybe at site level they can just do 
```
  withMenuDesign()(withDefaultContent({ overview$title$text: 'обзор' ))
```

2021-03-12 12:51 UTC, wodenx commented on packages/bodiless-organisms/doc/MainMenu.md
> -const asBasicSubMenu = withDesign({
Shouldn't we remove this rile?

2021-03-12 12:51 UTC, wodenx commented on examples/test-site/src/components/Breadcrumbs/MenuBreadcrumbs.ts
> +  withMenuBreadcrumbSchema as withDefaultBreadcrumbSchema,
Rename to 'withMenuBreadcrumbEditors' - we are moving away from using "Schema" here bc of possible confusing sith schema.org

2021-03-12 12:51 UTC, wodenx commented on examples/test-site/src/components/Breadcrumbs/MenuBreadcrumbs.ts
>  const DEFAULT_STARTING_TRAIL_NODE_KEY = 'startingTrail';
Seems like there's no need toe xposer these at site level.  Let's put them in the packagd so site builders don't have to think about them.

2021-03-12 22:05 UTC, VancheeZze commented on packages/bodiless-organisms/doc/MainMenu.md
> -const asBasicSubMenu = withDesign({
Done

2021-03-12 22:05 UTC, VancheeZze commented on examples/test-site/src/components/Breadcrumbs/MenuBreadcrumbs.ts
> +  withMenuBreadcrumbSchema as withDefaultBreadcrumbSchema,
Done

2021-03-12 22:05 UTC, VancheeZze commented on examples/test-site/src/components/Breadcrumbs/MenuBreadcrumbs.ts
>  const DEFAULT_STARTING_TRAIL_NODE_KEY = 'startingTrail';
Done

2021-03-12 22:05 UTC, VancheeZze commented on examples/test-site/src/components/Breadcrumbs/MenuBreadcrumbs.ts
> +const withMenuBreadcrumbSchema = asToken(
Done

2021-03-12 22:05 UTC, VancheeZze commented on examples/test-site/src/components/Menu/BurgerMenu.token.tsx
> +const $asSiteToggler = asToken(
Done

2021-03-12 22:05 UTC, VancheeZze commented on examples/test-site/src/components/Menu/BurgerMenu.token.tsx
> +const withTogglerWrapper = asToken(
Updated

2021-03-12 22:05 UTC, VancheeZze commented on examples/test-site/src/components/Menu/BurgerMenu.token.tsx
> +const withBurgerMenuHeader = withDesign({
Done

2021-03-12 22:05 UTC, VancheeZze commented on examples/test-site/src/components/Menu/BurgerMenu.token.tsx
> +const $asSiteBurgerMenu = asToken(
Updated all site-level tokens

2021-03-12 22:05 UTC, VancheeZze commented on examples/test-site/src/components/Menu/Menu.tsx
> +const BodilessMenuBase = flow(
Updated

2021-03-12 22:05 UTC, VancheeZze commented on examples/test-site/src/components/Menu/Menu.tsx
> +  $asSiteNavStyles,
Done

2021-03-12 22:05 UTC, VancheeZze commented on examples/test-site/src/components/Menu/index.tsx
> +import BodilessMenu from './Menu';
Updated to Menu

2021-03-12 22:05 UTC, VancheeZze commented on examples/test-site/src/components/Menu/index.tsx
> +  ResponsiveBodilessMenu,
Done

2021-03-12 22:05 UTC, VancheeZze commented on examples/test-site/src/components/Menu/index.tsx
> +  BurgerMenuTogglerFullWidth,
Done

2021-03-12 22:05 UTC, VancheeZze commented on packages/bodiless-navigation/src/Breadcrumbs/Breadcrumbs.tsx
> +const Breadcrumbs = flowRight(
Done

2021-03-12 22:05 UTC, VancheeZze commented on packages/bodiless-navigation/src/BurgerMenu/BurgerMenuClean.tsx
>  type BurgerMenuProps = DesignableComponentsProps<BurgerMenuComponents>;
Done

2021-03-12 22:05 UTC, VancheeZze commented on packages/bodiless-navigation/src/Menu/Menu.token.tsx
> +export const withMenuDesign = <P extends object>(
Moved to its own module and updated unit tests

2021-03-15 17:32 UTC, VancheeZze commented on packages/bodiless-navigation/src/BurgerMenu/asBurgerMenu.tsx
> +const asBurgerMenu = (...keys: string[]) => asToken(
Updated: `withOverviewLink('Custom Overview Link')`

2021-03-15 17:33 UTC, VancheeZze commented on packages/bodiless-navigation/src/BurgerMenu/asBurgerMenu.tsx
> +const withOverviewLink = (OverviewLink: ComponentType<any>) => {
Overview link is refactored

2021-03-15 17:34 UTC, VancheeZze commented on packages/bodiless-components/src/List/List.tsx
> +  const childItems = React.Children.toArray(children).filter(Boolean).map(child => (
List static items have been refactored.

2021-03-15 17:35 UTC, VancheeZze commented on packages/bodiless-components/src/List/List.tsx
> +      addItem={() => undefined}
Static list items now have a disabled add item button.

2021-03-15 17:35 UTC, VancheeZze commented on packages/bodiless-components/src/List/List.tsx
> +    <Item
Refactored

2021-03-15 21:35 UTC, VancheeZze commented on examples/test-site/src/components/Menu/Menu.tsx
> +export const $asEditableMenuTout = flow(
Removed

2021-03-16 16:23 UTC, wodenx requested changes

2021-03-16 16:23 UTC, wodenx commented on examples/test-site/src/data/pages/megamenu/index.tsx
>  import { graphql } from 'gatsby';
can we rename this page to just "menu" ?

2021-03-16 17:44 UTC, dewen commented on packages/bodiless-navigation/bodiless.docs.json
> +  		"Menu.md": "./doc/Menu.md",
Expand tabs?

2021-03-17 01:38 UTC, wodenx requested changes

2021-03-17 01:38 UTC, wodenx commented on examples/test-site/src/components/Breadcrumbs/MenuBreadcrumbs.ts
>    withEditableStartingTrail({ nodeCollection: 'site' }),
So last thing to do is make these use the same editors?  So you can do
withEditableStartingTrail(withMyMenuTitleEditor)

2021-03-17 17:58 UTC, VancheeZze commented on packages/bodiless-navigation/bodiless.docs.json
> +  		"Menu.md": "./doc/Menu.md",
Fixed

2021-03-17 17:58 UTC, VancheeZze commented on examples/test-site/src/data/pages/megamenu/index.tsx
>  import { graphql } from 'gatsby';
Renamed

2021-03-17 17:58 UTC, VancheeZze commented on packages/bodiless-navigation/src/Menu/withSubMenu.tsx
> +const withListSubMenu = (titleDesign: HOC = asEditableMenuTitle) => withSubMenuDesign({
Removed defaults

2021-03-18 19:36 UTC, VancheeZze commented on examples/test-site/src/components/Breadcrumbs/MenuBreadcrumbs.ts
> +  withDefaultBreadcrumbEditors(),
Updated

2021-03-18 19:36 UTC, VancheeZze commented on examples/test-site/src/components/Menu/Menu.token.tsx
> +const $withTitleEditors = withDesign({
`withMenuEditors` is implemented.

2021-03-18 19:37 UTC, VancheeZze commented on packages/bodiless-navigation/src/Breadcrumbs/withEditableTrail.tsx
> +    Link: asToken(stylable, withoutLinkWhenLinkDataEmpty, asReadOnly),
Updated

2021-03-18 19:54 UTC, VancheeZze commented on packages/bodiless-navigation/src/Menu/withSubMenu.tsx
> +    withEditableMenuTitle,
Done

2021-03-18 20:57 UTC, VancheeZze commented on examples/test-site/src/components/Breadcrumbs/MenuBreadcrumbs.ts
>    withEditableStartingTrail({ nodeCollection: 'site' }),
Done

2021-03-19 14:44 UTC, VancheeZze commented on packages/bodiless-navigation/__tests__/MenuBreadcrumbs.test.tsx
> +const Breadcrumbs = asBreadcrumbs(BreadcrumbsClean);
Done

2021-03-23 16:51 UTC, TatsianaMiraniuk commented
Hi @VancheeZze ,

please see **issue_1**:

**Steps to reproduce:**
1. open Static env for Desktop breakpoints (1024+ px)
2. hover over any item with a sumbmenu

**Actual Results:**
Submenu doesn't show up

**Expected Results:**
Submenu shows up on hover

2021-03-23 16:55 UTC, TatsianaMiraniuk commented
Hi @VancheeZze ,

please see **issue_2**:

**Steps to reproduce:**
1. open Static env, any page for Tablet breakpoints (1023px and less)

**Actual Results:**
Burger Menu is visible
![Screen Shot 2021-03-23 at 12 52 52 PM](https://user-images.githubusercontent.com/3224040/112185788-ecf9fb00-8bd6-11eb-9182-e31c980c3c13.png)

**Expected Results:**
Burger menu is not visible after opening a page

2021-03-23 16:57 UTC, TatsianaMiraniuk commented
Hi @VancheeZze ,

please see **issue_3**:

**Steps to reproduce:**
1. in Static env for Desktop breakpoints (1024+ px),  open /menu/

**Actual Results:**
Burger Menu layout shows on load first

**Expected Results:**
Burger Menu layout is not visible when a page loads

2021-03-23 17:00 UTC, TatsianaMiraniuk commented
Hi @VancheeZze ,

please see **issue_4**:

**Steps to reproduce:**
1. in Static env for Tablet breakpoints (1023px and less),  open /menu/

**Actual Results:**
Burger Menu layout shows. The page itself can not be viewed 
![Screen Shot 2021-03-23 at 1 00 03 PM](https://user-images.githubusercontent.com/3224040/112186627-b7094680-8bd7-11eb-8f3e-069855f98dab.png)


**Expected Results:**
/menu/ page opens with its content

2021-03-23 17:16 UTC, TatsianaMiraniuk commented
Hi @VancheeZze ,

please see **issue_5**:

**Steps to reproduce:**
1. in Edit env for Desktop breakpoints (1024+px),  open any page
2. resize a browser width to Tablet breakpoint

**Actual Results:**
Burger Menu layout show for a moment when Desktop changes to Tablet breakpoint


**Expected Results:**
Burger Menu layout doesn't show until it's open by a user

_NOTE:_
not reproduced in Static env

2021-03-23 19:40 UTC, TatsianaMiraniuk commented
Hi @VancheeZze ,

please see **issue_6**:
Column title works as a link in Burger Menu

**Steps to reproduce:**
1. in Edit env for Desktop breakpoints (1024+px),  open any page
2. switch to Edit mode
3. in Menu, add a top level item and Columns submenu in it
4. fill in Column title
5. add a link in the Column title
6. add a submenu item in the column, fill it in
7. switch to Preview Mode
8. resize the browser to Burger Menu
9. open Burger Menu
10. click the top level item with the column submenu (to expand/open the submenu)
11. click the column title (the label)

**Actual Results:**
the column title works as a link 


**Expected Results:**
the submenu of the column opens as an accordion

2021-03-23 19:46 UTC, TatsianaMiraniuk commented
Hi @VancheeZze ,

please see **issue_7**:

**Steps to reproduce:**
1. in Edit env for Desktop breakpoints (1024+px),  open any page
2. switch to Edit Mode
3. add a new top level item
4. click the new added item to get Local Context Menu

**Actual Results:**
Menu Link: _Edit_ link shows
![Screen Shot 2021-03-23 at 3 43 34 PM](https://user-images.githubusercontent.com/3224040/112208529-d495da80-8bee-11eb-8a9f-cacce6f8775c.png)


**Expected Results:**
Menu Link: _Add_ link shows

2021-03-23 20:08 UTC, TatsianaMiraniuk commented
Hi @VancheeZze ,

please see **issue_8**:

**Steps to reproduce:**
1. in Edit env for Desktop breakpoints (1024+px),  open any page
2. switch to Edit Mode
3. add a new top level item
4. add Touts submenu
5. fill in title, body, cta label and cta url of the tout
6. switch to Preview Mode
7. resize the browser to Burger Menu
8. open Burger Menu
9. open Touts submenu
10. click the submenu item (Tout Title)

**Actual Results:**
the item is not linkable
![Screen Shot 2021-03-23 at 4 07 44 PM](https://user-images.githubusercontent.com/3224040/112211175-f5abfa80-8bf1-11eb-8a86-a0ff2deb5122.png)


**Expected Results:**
the item is linkable - it goes to the cta url

2021-03-23 20:24 UTC, TatsianaMiraniuk commented
Hi @VancheeZze ,

please see **issue_9**:

**Steps to reproduce:**
1. in Edit env for Desktop breakpoints (1024+px),  open any page
2. switch to Edit Mode
3. add a new top level item
4. fill in the top level item and add URL
5. switch to Preview Mode
6. resize the browser to Burger Menu
7. open Burger Menu
8. click the top menu item (or click Home)

**Actual Results:**
the top level items are not linkable
![Screen Shot 2021-03-23 at 4 20 44 PM](https://user-images.githubusercontent.com/3224040/112213123-24c36b80-8bf4-11eb-9589-1b9226d4b265.png)


**Expected Results:**
the top level item are not linkable if a url is set for them

2021-03-24 17:55 UTC, VancheeZze commented
Hi @TatsianaMiraniuk 

I fixed the following issues:

- issue_1
- issue_1
- issue_1
- issue_1
- issue_1
- issue_1

2021-03-24 21:08 UTC, TatsianaMiraniuk commented
Hi @VancheeZze ,

please see **issue_10**:
Burger Menu is not scrollable

**Steps to reproduce:**
1. in Static env, open any page on a mobile device (Samsung Galaxy S20; or iPhone 8 on simulator), e.g. /touts/
2. open Burger Menu
3. expand all top level items 
4. swipe to the bottom 


**Actual Results:**
Burger Menu is not scrollable. The bottom items are not visible

**Expected Results:**
Burger Menu is not scrollable.

2021-03-24 21:26 UTC, TatsianaMiraniuk commented
Hi @VancheeZze ,

please see **issue_11**:
Column title ins't pulled into Breadcrumbs

**Steps to reproduce:**
1. in Edit env, open any page in Desktop Breakpoint
2. switch to Edit mode
3. add a top menu item, fill it
4. add Column submenu
5. fill in Column Title
6. add a submenu in the Column
7. fill in the submenu and add url - a path to the existing page, e.g. /touts/
8. open /touts/


**Actual Results:**
there is Menu Item placeholder text instead of Column Title

![Screen Shot 2021-03-24 at 5 24 46 PM](https://user-images.githubusercontent.com/3224040/112385353-e72f1300-8cc5-11eb-963a-bb10dc245662.png)
![Screen Shot 2021-03-24 at 5 24 52 PM](https://user-images.githubusercontent.com/3224040/112385349-e5fde600-8cc5-11eb-9b93-13ef43967bfc.png)

**Expected Results:**
Column Title is pulled into Breadcrumbs

2021-03-25 16:18 UTC, VancheeZze commented
@TatsianaMiraniuk 

**Issue_10** and **issue_11** have been addressed. 

Thank you

2021-03-29 15:06 UTC, wodenx submitted a review, later dismissed

2021-03-30 18:36 UTC, TatsianaMiraniuk commented
@VancheeZze ,

please see issue_12:

Burger Menu: Long title isn't wrapped to next line:
![Screen Shot 2021-03-30 at 2 36 11 PM](https://user-images.githubusercontent.com/3224040/113039111-4e851100-9165-11eb-9ce0-d40002c9c4d0.png)

2021-03-30 20:42 UTC, TatsianaMiraniuk commented
TO DISCUSS

**issue_13**:
Simple RTE is replaced by Editable in all single menu items, in Title and CTA in Touts, so there is no ability to set a superscript in their text

2021-04-01 19:13 UTC, TatsianaMiraniuk commented
@VancheeZze ,

please see **issue_15:**

**Steps to Reproduce:**
1. open Edit env, /breadcrumb/ page
2. switch to Edit mode
3. in MegaMenu on the page, add an item with a link to /breadcrumb/
4. check 'Breadcrumbs with boldable final trail item'

**Actual Results:**
last trail item is not bold
![Screen Shot 2021-04-01 at 3 13 07 PM](https://user-images.githubusercontent.com/3224040/113342699-c89bce00-92fc-11eb-97e1-60829a080a10.png)
![Screen Shot 2021-04-01 at 3 12 35 PM](https://user-images.githubusercontent.com/3224040/113342701-c9346480-92fc-11eb-82a6-93e8776c6fc0.png)



**Expected Results:**
last trail item in  'Breadcrumbs with boldable final trail item' is bold

2021-04-01 20:44 UTC, VancheeZze commented
@TatsianaMiraniuk 

**Issue_15** has been fixed. 

Thank You!

2021-04-01 21:11 UTC, TatsianaMiraniuk commented
@VancheeZze ,

please see **issue_16:**

**Steps to Reproduce:**
1. open Edit env, /breadcrumb/ page
2. switch to Edit mode
3. in any editable first trail, open Link Form
4. set any URL different from / 
5. click 'v'
6. Reopen LInk Form
7.  click Remove Link

**Actual Results:**
the item still shows as a link (blue and underlined).

8. Reopen LInk Form
The URL is reset to /


**Expected Results:**
URL field is cleaned. The item shows as a reqular text

2021-04-01 21:34 UTC, TatsianaMiraniuk commented
@VancheeZze ,

please see **issue_17:**
Middle Trails show as a link even if they don't have URL value set (due to a new change to have the link toggle be on by default)

**Steps to Reproduce:**
1. open Edit env, /breadcrumb/ page
2. switch to Edit mode
3. in the sample Menu on the page, add a top level item (don't add a URL)
4. add a list submenu item
5. set /breadcrumb/ url for the submenu item

**Actual Results:**
the middle trail item (top item label) shows as a link
![Screen Shot 2021-04-01 at 5 27 26 PM](https://user-images.githubusercontent.com/3224040/113356525-5e8d2400-9310-11eb-9ace-5a0bc2f82b79.png)


**Expected Results:**
the middle trail item shows as a regular text if no URL is set

2021-04-02 13:01 UTC, VancheeZze commented
@TatsianaMiraniuk 

**Issue_16** has been fixed. As for **issue_17**, I would say this is an expected behavior now. If the link-toggle is ON then it is a link even if the URL field is empty. But let's discuss it with the team.

2021-04-02 18:49 UTC, TatsianaMiraniuk commented
> @VancheeZze ,
> 
> please see **issue_15:**
> 
> **Steps to Reproduce:**
> 
> 1. open Edit env, /breadcrumb/ page
> 2. switch to Edit mode
> 3. in MegaMenu on the page, add an item with a link to /breadcrumb/
> 4. check 'Breadcrumbs with boldable final trail item'
> 
> **Actual Results:**
> last trail item is not bold
> ![Screen Shot 2021-04-01 at 3 13 07 PM](https://user-images.githubusercontent.com/3224040/113342699-c89bce00-92fc-11eb-97e1-60829a080a10.png)
> ![Screen Shot 2021-04-01 at 3 12 35 PM](https://user-images.githubusercontent.com/3224040/113342701-c9346480-92fc-11eb-82a6-93e8776c6fc0.png)
> 
> **Expected Results:**
> last trail item in 'Breadcrumbs with boldable final trail item' is bold

HI @VancheeZze , the issue is fixed for a case when the label is pulled from Menu.  However, it became an issue for a case when last trail item is entered manually - it's not getting bold. Can you please recheck?
![Screen Shot 2021-04-02 at 2 46 56 PM](https://user-images.githubusercontent.com/3224040/113444761-8341d400-93c2-11eb-9a6c-f530505c9f29.png)

2021-04-02 19:54 UTC, TatsianaMiraniuk commented
@VancheeZze ,

please see **issue_18:**
Link Toggle is applied to Last trail item (the current page) when it's added manually

**Steps to Reproduce:**
1. open Edit env, /breadcrumb/ page
2. switch to Edit mode
3.  click last trail item in any Breadcrumbs editable example

**Actual Results:**
Local Context Menu with Link shows

4. in  last trail item, enter any label
5. switch to Preview mode
6. check last trail item

**Actual Results:**
Link toggle is on for last trail item
![Screen Shot 2021-04-02 at 3 52 31 PM](https://user-images.githubusercontent.com/3224040/113449277-7a093500-93cb-11eb-8f5c-2da9e66ff672.png)



**Expected Results:**
last trail item shows as a regular text and it's not linkable

2021-04-02 20:49 UTC, TatsianaMiraniuk commented
@VancheeZze ,

please see **issue_19:**
Top Menu Item is missed as a middle trail if URL field sets to empty field (#)

**Steps to Reproduce:**
1. open Edit env, /breadcrumb/ page
2. switch to Edit mode
3.  add a top menu item in Sample menu on the page
4. add any url value
5. add a submenu item (list)
6. add /breadcrumb/ as a URL in the submenu item  -> both top item and submenu item are shown in breadcrumbs
7. open Link form for the top menu item
8. clean URL field, click 'v'
9. reload the page


**Actual Results:**
a middle trail (the top menu item label) is missed
![Screen Shot 2021-04-02 at 4 48 27 PM](https://user-images.githubusercontent.com/3224040/113453090-4df1b200-93d3-11eb-96d2-1e55695099f2.png)


**Expected Results:**
the top menu item label is shown as a middle trail

2021-04-02 21:05 UTC, TatsianaMiraniuk commented
@VancheeZze ,

please see **issue_20:**


**Steps to Reproduce:**
1. open Edit env, /breadcrumb/ page
2. switch to Edit mode
3.  add a top menu item in Sample menu on the page
4. add a submenu item (any type, e.g. tout)
5. fill in a tout title
6. set CTA URL as /breadcrumb/  -> both top item and submenu item are shown in breadcrumbs. Submenu is last trail (current page) [correct behavior]
![Screen Shot 2021-04-02 at 5 02 07 PM](https://user-images.githubusercontent.com/3224040/113454117-78446f00-93d5-11eb-8b26-1997e5428306.png)
7. open CTA Link form
8. clean URL field and click 'v'

**Actual Results:**
top item and submenu item  are not deleted from the breadcrumbs, a new empty item as a Last trail is added
![Screen Shot 2021-04-02 at 5 02 38 PM](https://user-images.githubusercontent.com/3224040/113454102-711d6100-93d5-11eb-9d25-115532bc6ddf.png)


**Expected Results:**
top item and submenu item are deleted from the breadcrumbs

2021-04-02 22:40 UTC, TatsianaMiraniuk commented
@VancheeZze ,

please see **issue_21:**
Last trail item of a page that doesn't exist in Menu is not correct (Static env only)


**Steps to Reproduce:**
1. open Edit env, any page
2. switch to Edit mode
3.  create a page: /foo1/bar1
4. create the following in Menu
top level item: Foo1 (/foo1)
its submenu item: Bar1 (/foo1/bing1)
5. open /foo1/bar1  -> last trail is empty (as expected)
6. add some label in Last trail
7. push the content
8. in Static env, open /foo1/bar1
**Actual Results:**
Last trail item that's set manually shows on load, but then it's replaced by 'Foo1'
![Screen Shot 2021-04-02 at 6 37 59 PM](https://user-images.githubusercontent.com/3224040/113459169-995f8c80-93e2-11eb-97f7-c6f57c806ae7.png)



**Expected Results:**
Last trail item that's set manually shows correctly

2021-04-03 22:53 UTC, TatsianaMiraniuk commented
@VancheeZze ,

please see **issue_22:**
Images in Tout menu items lost the rounded corners


**Steps to Reproduce:**
1. open Edit env, any page
2. switch to Edit mode
3.  in Menu, add Tout submenu item
4. upload an image  -> the image shows with the rounded corners
5. reload the page

**Actual Results:**
Images in Tout menu items lost the rounded corner, and displayed with the regular rectangular corners
![Screen Shot 2021-04-03 at 6 52 46 PM](https://user-images.githubusercontent.com/3224040/113493508-d04ea480-94ad-11eb-8225-3dfef2d0b7ae.png)


**Expected Results:**
Images in Tout menu items are with the rounded corners

2021-04-05 21:07 UTC, VancheeZze commented
@TatsianaMiraniuk 

The following issues have been fixed:

- **issue_15**
- **issue_18**
- **issue_19**
- **issue_20**
- **issue_22**

Issue_21 has been partly fixed -- it now gets the right title but keeps the wrong link ( Still looking for a fix )

Thank you,
Ivan

2021-04-06 13:23 UTC, VancheeZze commented
@TatsianaMiraniuk 
**Issue_21** has also been fixed. All reported issues are now fixed.

Thank You

2021-04-07 08:05 UTC, wodenx commented on examples/test-site/src/components/Breadcrumbs/MenuBreadcrumbs.token.tsx
> +const withFinalTrailLinkStyles = withDesign({
So ... this is what you were unable to move to package level?  Seems to me you should be able to put it [here](https://github.com/johnsonandjohnson/Bodiless-JS/blob/54be825dc936bd764ec304aedb514daf92fd9a4e/packages/bodiless-navigation/src/Breadcrumbs/withEditableTrail.tsx#L94) with the same effect... is that what you tried?  I really don't think we should make people do this at site level... it would be easy to forget and has a very subtle failure mode.

2021-04-07 08:05 UTC, wodenx commented on examples/test-site/src/data/pages/breadcrumb/index.tsx
> +const DemoBreadcrumbs = asToken(
Why did you move all this to the page level?

2021-04-07 11:42 UTC, VancheeZze commented on examples/test-site/src/data/pages/breadcrumb/index.tsx
> +const DemoBreadcrumbs = asToken(
Moved it here so we can define a custom `withEditableFinalTrail` with unique node keys for each breadcrumb example on the page.

2021-04-07 11:44 UTC, VancheeZze commented on examples/test-site/src/components/Breadcrumbs/MenuBreadcrumbs.token.tsx
> +const withFinalTrailLinkStyles = withDesign({
Right, that is the exact place I tried, but when `withFinalTrailLinkStyles` is used on the package level, I get the wrong link back for the final trial on rehydration.

2021-04-07 13:42 UTC, VancheeZze commented on packages/bodiless-navigation/src/Breadcrumbs/BreadcrumbStore.ts
> +    if (this.link.data === '#' || itemURL.host !== thisURL.host || itemURL.hash !== thisURL.hash) return false;
Updated

2021-04-07 13:43 UTC, VancheeZze commented on packages/bodiless-navigation/src/Breadcrumbs/BreadcrumbStore.ts
> +    if (this.link.data === '#' || itemURL.host !== thisURL.host || itemURL.hash !== thisURL.hash) return false;
Updated. You right, `/^#/.test(this.link.data)` is enough and we do not need to compare hashes

2021-04-08 15:34 UTC, wodenx submitted a review, later dismissed

2021-04-09 17:01 UTC, TatsianaMiraniuk commented
@VancheeZze ,

please see **issue_23**:

**Steps to reproduce:**

1. in Edit env, open any page
2. switch to Edit mode
3. create the following top menu item:
Foo2-c with link /foo2-c
4.create a column submenu item
5. set:
Bar5-c as a title with /bing5-c link
6. create page with a path /bing5-c
7. open /bing5-c page

Breadcrumbs are correct:
![Screen Shot 2021-04-09 at 12 59 11 PM](https://user-images.githubusercontent.com/3224040/114215373-880f0680-9933-11eb-85c1-9ed27aa7f78f.png)

8. change browser width to Tablet view (with Burger Menu)

**Actuas Results:**
Menu Item as last trail item appears
![Screen Shot 2021-04-09 at 12 59 21 PM](https://user-images.githubusercontent.com/3224040/114215410-90ffd800-9933-11eb-9fbb-6d5ffdd050ad.png)

**Expected Results:**
/bing5-c: Home > Foo2-c > Bar5-c

2021-04-09 23:32 UTC, TatsianaMiraniuk commented
> @VancheeZze ,
> 
> please see **issue_17:**
> Middle Trails show as a link even if they don't have URL value set (due to a new change to have the link toggle be on by default)
> 
> **Steps to Reproduce:**
> 
> 1. open Edit env, /breadcrumb/ page
> 2. switch to Edit mode
> 3. in the sample Menu on the page, add a top level item (don't add a URL)
> 4. add a list submenu item
> 5. set /breadcrumb/ url for the submenu item
> 
> **Actual Results:**
> the middle trail item (top item label) shows as a link
> ![Screen Shot 2021-04-01 at 5 27 26 PM](https://user-images.githubusercontent.com/3224040/113356525-5e8d2400-9310-11eb-9ace-5a0bc2f82b79.png)
> 
> **Expected Results:**
> the middle trail item shows as a regular text if no URL is set

GAP #966 has been created

2021-04-10 01:28 UTC, TatsianaMiraniuk approved these changes

2021-04-10 18:13 UTC, wodenx approved these changes

2021-04-12 12:00 UTC, merged