feat(gatsby-theme-bodiless): Bodiless Image Refresh
johnsonandjohnson/Bodiless-JS pull request #860
Opened 2021-02-17 07:37 UTC by beliayeu

## Changes

## Test Instructions

## Related Issues

Closes #852

2021-02-25 11:32 UTC, wodenx commented on packages/bodiless-layouts/src/ContentLibrary/withContentLibrary.tsx
> +  Component: ComponentType | string,
again let's type it as ComponentOrTag

2021-02-25 11:32 UTC, wodenx commented on packages/bodiless-core/src/Contentful/ContentfulNode.ts
> +    if (typeof contentValue === 'function') return contentValue(this.proxy({}));
Why are we returning a proxy with no handlers?

2021-02-25 12:11 UTC, beliayeu commented on examples/test-site/gatsby-config.js
> +} = require('@bodiless/gatsby-theme-bodiless/dist/DefaultContent');
require from '@gatsby-theme-bodiless' fails because of require of assets made by gatsby-theme-bodiless. particularly, bodiless-ui/lib/Spinner.css.
require from '@gatsby-theme-bodiless' works from site components as far as the execution is made in webpack context which knows how to load them
here, we are not in webpack context and asset require will throw an error

2021-02-26 12:46 UTC, beliayeu commented on packages/gatsby-theme-bodiless/src/dist/DefaultContent/getSampleConfig.ts
> +  path.resolve(
I believe we can use require.resolve to find a path to @bodiless/gatsby-theme-bodiless
but I think we will still need doing path.resolve

```
const getConfig = () => [
  path.resolve(
    path.dirname(
      require.resolve('@bodiless/gatsby-theme-bodiless', { paths: [process.cwd()] }),
    ),
    'dist',
    'DefaultContent',
    'sample',
  ),
];
```

2021-02-26 12:50 UTC, beliayeu commented on examples/test-site/gatsby-config.js
> +    ...getSampleDefaultContentConfig(),
the problem here is that the options we pass in site's gatsby-config.js won't be available in a plugin gatsby-config.js, particularly, we can not pass configuration from site gatsby-config.js and make it available in @bodiless/gatsby-theme-bodiless gatsby-config

per discussion in skype, decided not to spend more time finding a way how to pass data from site to gatsby-theme-bodiless as far as mainly autodiscovery will be enabled on sites and this configuration won't be needed

2021-02-27 08:44 UTC, beliayeu commented on packages/bodiless-components/src/Image/withDefaultImageContent.ts
> +  asEditableImage.meta !== undefined ? asEditableImage.meta : identity,
makes sense, meta is added to hocs, while AsBodiless is not a hoc, it returns a hoc
updated in d21922b1935a3a48224f52806fd44be6bcaea55a
also, made asToken accept undefined and validated that asToken always attaches empty meta property

2021-02-27 08:45 UTC, beliayeu commented on packages/bodiless-components/src/Image/withImageLibrary.ts
> +  asEditableImage: AsBodilessImage & { meta?: TokenMeta },
fixed in d21922b

2021-02-27 09:09 UTC, beliayeu commented on packages/bodiless-core/src/Contentful/ContentfulNode.ts
> +  private content: object;
fixed in 6e2b015da42a9793abb10452f5eac71a95e6da7c

2021-02-27 09:10 UTC, beliayeu commented on packages/bodiless-core/src/Contentful/withDefaultContent.tsx
> +  (Component: CT<P> | string) => {
fixed in 6e2b015da42a9793abb10452f5eac71a95e6da7c

2021-02-27 09:11 UTC, beliayeu commented on packages/bodiless-core/src/asBodilessComponent.tsx
> +import type { HOC } from '@bodiless/fclasses/lib/Tokens';
agreed, the reason I did was that there was an existing HOC type imported from package root
tried to replace, made the new HOC type exported by fclasses, no ts errors found
the fix is made in 6e2b015da42a9793abb10452f5eac71a95e6da7c

2021-02-27 09:11 UTC, beliayeu commented on packages/bodiless-layouts/src/ContentLibrary/withContentLibrary.tsx
> +  Component: ComponentType | string,
fixed in 6e2b015da42a9793abb10452f5eac71a95e6da7c

2021-03-01 11:10 UTC, beliayeu commented on packages/gatsby-theme-bodiless/gatsby-config.js
> +      const fileContent = JSON.parse(fs.readFileSync(file));
made experiments with making the logic async
wip: https://github.com/beliayeu/Bodiless-JS/compare/feat/bodiless-image-refresh...beliayeu:feat/bodiless-image-refresh-async-discovery?expand=1

it looks there is a constraint that we can not use async/await in gatsby-config
on the option we can do is to prebuild the file containing configuration

related discussion in gatsby: https://github.com/gatsbyjs/gatsby/issues/11128 and https://github.com/gatsbyjs/gatsby/issues/19644

2021-03-01 11:16 UTC, beliayeu commented on packages/gatsby-theme-bodiless/gatsby-config.js
> +  let dir = path.resolve(process.cwd());
for get it working in a monorepo, there is an env variable `BODILESS_DEFAULT_CONTENT_AUTO_DISCOVERY_DEPTH` that allows to configure amount of dirs to navigate up

2021-03-01 11:52 UTC, beliayeu commented on packages/bodiless-core/src/Contentful/ContentfulNode.ts
> +    if (typeof contentValue === 'function') return contentValue(this.proxy({}));
I believe we do not need proxy here
removed in 51f9085cb7e8edb4b82ceb24d9bd06c40a289935

2021-03-01 17:06 UTC, beliayeu commented on packages/bodiless-core/src/asBodilessComponent.tsx
> +import type { HOC } from '@bodiless/fclasses/lib/Tokens';
the new HOC type introduces build issue on an existing site - discuss if we want to accept this breaking change

2021-03-02 06:52 UTC, beliayeu commented on packages/gatsby-theme-bodiless/src/dist/GatsbyImage/asGatsbyImage.tsx
> + */
I believe we can merge it, tried the new version on one of our sites, did not get any issues
merged asDesignableGatsbyImage into asGatsbyImage in bba137b42ff6fc0b9f33bbeba80bda24c11a131f

2021-03-02 12:40 UTC, wodenx requested changes

2021-03-02 12:40 UTC, wodenx commented on packages/bodiless-components/src/Image/Image.tsx
> +export type AsImageToken = ReturnType<AsBodilessImage> & TokenProps<ImageProps>;
I think this should be named just "ImageToken"

2021-03-02 12:40 UTC, wodenx commented on packages/bodiless-components/src/Image/withDefaultImageContent.ts
> +  const asImageHoc = asEditableImage(nodeKey, placeholder, useOverrides) as AsImageToken;
Why is this cast necessary?   AsEditableImage should return an ImageToken

2021-03-02 12:40 UTC, wodenx commented on packages/bodiless-components/src/Image/withDefaultImageContent.ts
> +    typeof nodeKey === 'string' ? withResetButton({ nodeKey }) : withResetButton(nodeKey),
Seems like we should move this overload to withResetButton...

2021-03-02 12:40 UTC, wodenx commented on packages/bodiless-layouts/src/ContentLibrary/withContentLibrary.tsx
> +  Component: ComponentOrTag<any>,
Should we make this generic?
```
const withContentLibrary = (options: ContentLIbraryOptions) => (
  <P extends object>(Component: ComponentOrTag<P>) => ...

2021-03-02 12:40 UTC, wodenx commented on packages/fclasses/src/Tokens.tsx
> +type TokenDef<P> = Token<P>|TokenMeta|undefined;
I have this change in my pr, but i think it also requires [dealing with undefined tokendefs in asToken](https://github.com/johnsonandjohnson/Bodiless-JS/pull/906/files#diff-c413d4b2772969b0166ede9ccc9c509e543323df95e6d9c6241f96a2a5057a6aR190-R192).  Do you need this "undefined" in this PR? or can we wait for it in mine?

2021-03-02 13:06 UTC, beliayeu commented on packages/bodiless-components/src/Image/withDefaultImageContent.ts
> +  const asImageHoc = asEditableImage(nodeKey, placeholder, useOverrides) as AsImageToken;
currently, AsEditableImage has a specific type of AsBodiless generic, so it returns HOC.
to my mind we have 2 options:
- either to include Token into AsBodiless ReturnType, or
- allow asEditableImage be HOC or Token. Then we will need a way how to determine whether a particular function is a hoc or token. As an option we can add a property to token.

2021-03-02 13:45 UTC, beliayeu commented on packages/fclasses/src/Tokens.tsx
> +type TokenDef<P> = Token<P>|TokenMeta|undefined;
yep, I need it, since there is an access to meta prop which can undefined in image hocs
for example, in withDefaultImageContent

2021-03-02 14:06 UTC, beliayeu commented on packages/bodiless-components/src/Image/Image.tsx
> +export type AsImageToken = ReturnType<AsBodilessImage> & TokenProps<ImageProps>;
since Token is included to AsBodiless
removed ImageToken in b74b8b0877779b76fa35b2d0627d8a24aa507fb8

2021-03-02 14:07 UTC, beliayeu commented on packages/bodiless-components/src/Image/withDefaultImageContent.ts
> +    typeof nodeKey === 'string' ? withResetButton({ nodeKey }) : withResetButton(nodeKey),
fixed in b74b8b0877779b76fa35b2d0627d8a24aa507fb8

2021-03-02 14:07 UTC, beliayeu commented on packages/bodiless-layouts/src/ContentLibrary/withContentLibrary.tsx
> +  Component: ComponentOrTag<any>,
fixed in b74b8b0877779b76fa35b2d0627d8a24aa507fb8

2021-03-02 15:09 UTC, wodenx submitted a review, later dismissed

2021-03-02 22:22 UTC, TatsianaMiraniuk commented
Hi @beliayeu ,

please see **issue_1**:

there are 2 warnings in a console in Test Site, on each page (related to Logo image) - Edit env only:
1) Warning: React does not recognize the `gatsbyImg` prop on a DOM element. ...
2) Warning: React does not recognize the `publicUrl` prop on a DOM element. ..

2021-03-02 22:45 UTC, TatsianaMiraniuk commented
@beliayeu ,

please see **issue_2:**

An uploaded image is in low quality, e.g. upload an image in Hero image on Home page or in a Tout on /touts/ page. 
Please see screenshot to compare with the current master behavior:
![Screen Shot 2021-03-02 at 5 40 38 PM](https://user-images.githubusercontent.com/3224040/109725348-ff0bef00-7b7e-11eb-97c2-5af332581044.png)

2021-03-02 22:57 UTC, TatsianaMiraniuk commented
@beliayeu ,

please see **issue_3:**
The images are not set for Contentful Touts that are chosen from Component Picker.

### Steps to reproduce:
1. open Edit env, /flow-container/ page
2. switch to Edit mode
3. click FC 
4. click 'Add'
5. select Contentful Tout in the filter
### Actual Result:
no image is set
![Screen Shot 2021-03-02 at 5 52 16 PM](https://user-images.githubusercontent.com/3224040/109726354-9b82c100-7b80-11eb-9c22-a32168f8758b.png)


6. select any Contentful Tout
### Actual Result:
no image is shown when the component is put on the page.

### Expected Results:
Contentful Tout has pre-set content (including an image)

2021-03-03 14:54 UTC, beliayeu commented
thanks, @TatsianaMiraniuk 

issue_1:
problem:
image data is extended during gatsby node creation phase with additional data required for default content case.
standard image hoc does not perform props stripping, so we ended up with invalid html attributes

fix:
provided a new hoc on site level that can used for rendering non-responsive image, this hoc performs props stripping
activated this new hoc for logo

fixed in 3272da60d2deba467aaada56f2fa67f3dcb6d4e2

issue_2: I think that is a trade-off between image quality and image size.
to discuss with team whether we want to adjust image quality on test-site
cc: @hvanyo 

issue3:
problem: default data is not available for this page
fix: added DefaultContentQuery graphql query so that default data is available

fixed in 3272da60d2deba467aaada56f2fa67f3dcb6d4e2

2021-03-03 20:01 UTC, TatsianaMiraniuk commented
@beliayeu ,

please see **issue_4:**:

there is design="[object Object]" for the placeholder images in Touts:
![Screen Shot 2021-03-03 at 3 00 16 PM](https://user-images.githubusercontent.com/3224040/109864790-494da880-7c31-11eb-8959-f0da4e0b88d8.png)

2021-03-03 22:03 UTC, TatsianaMiraniuk commented
@beliayeu ,

please see **issue_5**:
Image path from Content Library isn't pulled correctly in Src field of Image Upload form

### Steps to reproduce:
1. in Edit env, open /content-library/
2. switch to Edit mode
3. in Image with library, select any image from Library
4. open Image Upload form (click Image: Select)
### Actual Result:
Src value isn't showing the correct path
![Screen Shot 2021-03-03 at 3 26 36 PM](https://user-images.githubusercontent.com/3224040/109868090-3d63e580-7c35-11eb-9c78-afee5fec63b0.png)

4. click V

### Actual Result:
the image doesn't show (due to the incorrect path)
![Screen Shot 2021-03-03 at 3 30 55 PM](https://user-images.githubusercontent.com/3224040/109868315-78661900-7c35-11eb-9323-ff25e50613e6.png)

2021-03-03 22:51 UTC, TatsianaMiraniuk commented
@beliayeu ,

please see **issue_6:**
The issue is similar to **issue_5** but it causes the env to return 502 error

Image path isn't pulled correctly in Src field of Image Upload form

### Steps to reproduce:
1. in Edit env, open /images/
2. switch to Edit mode
3. in Contentful Image Components, open Image Upload Form
4. click V

### Actual Result:
the env returns 502 error

2021-03-11 13:30 UTC, wodenx approved these changes

2021-03-11 22:15 UTC, TatsianaMiraniuk commented
@beliayeu ,

please see **issue_7**:
Images in 'Gatsby Images' section on /images/ page are not Gatsby images.
![Screen Shot 2021-03-11 at 5 12 38 PM](https://user-images.githubusercontent.com/3224040/110862297-51d75c00-828d-11eb-9e4a-dc6ca5996389.png)

2021-03-15 13:28 UTC, TatsianaMiraniuk commented
**issue_8:**
Gatsby images show incorrectly, no padding  in /images/ page for <1024px
![Screen Shot 2021-03-12 at 5 20 28 PM](https://user-images.githubusercontent.com/3224040/111160579-9b1afa80-8570-11eb-81a4-750ea024a83e.png)
![Screen Shot 2021-03-12 at 5 20 55 PM](https://user-images.githubusercontent.com/3224040/111160587-9e15eb00-8570-11eb-8f96-7701af26cb90.png)

2021-03-16 20:15 UTC, TatsianaMiraniuk commented
Hi @beliayeu ,

please see issue_9, specific for Starter Site:

**Steps to reproduce:**
1. open Home page in Edit env for 1024+ px
2. upload Hero image
3. upload images in Touts
4. refresh the page
5. resize the browser to less than 1024px

**Actual Results:**
Hero image, Touts get much smaller:
![Screen Shot 2021-03-16 at 1 51 11 PM](https://user-images.githubusercontent.com/3224040/111373584-73ac5680-8672-11eb-9a9c-88aebe6c00d4.png)

6. switch to Preview Mode

**Actual Results:**
Hero image is missing, Touts are small
![Screen Shot 2021-03-16 at 1 49 36 PM](https://user-images.githubusercontent.com/3224040/111373648-8d4d9e00-8672-11eb-8001-e514cadcad43.png)
Same in Static:
![Screen Shot 2021-03-16 at 4 05 21 PM](https://user-images.githubusercontent.com/3224040/111373717-a6564f00-8672-11eb-9be9-14735fa436cf.png)

2021-03-18 15:34 UTC, TatsianaMiraniuk approved these changes

2021-03-18 15:37 UTC, wodenx approved these changes

2021-03-18 15:44 UTC, merged