[DO NOT MERGE] #889 - Fix Placeholder Overlay
johnsonandjohnson/Bodiless-JS pull request #934
Opened 2021-03-22 11:25 UTC by Guilherme-Almeida-Zeni

2021-03-23 11:05 UTC, marcopagliarulo requested changes

2021-03-23 11:55 UTC, marcopagliarulo commented on examples/test-site/src/data/pages/cards/index.jsx
> + */
Can you explain better the issue, sorry I didn't get the point. Additionally I don't see cypress tests for card in the source code

2021-03-23 11:55 UTC, marcopagliarulo commented on packages/bodiless-card/src/components/Cards.tokens.tsx
> +/**
The basic tokens have not metadata

2021-03-23 12:07 UTC, marcopagliarulo commented on packages/bodiless-card/doc/api/globals.md
> +*Defined in [packages/bodiless-card/src/components/Cards.tsx:31](https://github.com/Guilherme-Almeida-Zeni/Bodiless-JS/blob/f2eace99/packages/bodiless-card/src/components/Cards.tsx#L31)*
please fix the reference link

2021-03-23 12:07 UTC, marcopagliarulo commented on packages/bodiless-card/doc/api/globals.md
> +*Defined in [packages/bodiless-card/src/components/Cards.tsx:52](https://github.com/Guilherme-Almeida-Zeni/Bodiless-JS/blob/f2eace99/packages/bodiless-card/src/components/Cards.tsx#L52)*
please fix the reference link, applied to the links below

2021-03-23 12:44 UTC, Guilherme-Almeida-Zeni commented on packages/bodiless-card/tailwind.config.js
> +/**
Removed. Please, review it again. Thanks!

2021-03-23 12:44 UTC, Guilherme-Almeida-Zeni commented on examples/starter/src/components/Card/index.tsx
> +} from '@bodiless/organisms';
Updated to @bodiless/card. Please, review it again. Thanks!

2021-03-23 12:45 UTC, Guilherme-Almeida-Zeni commented on examples/starter/src/components/FlowContainer/withCardVariations.tsx
> +    withDesc('A way to card a call to Action.\n'),
Replaced 'card' with 'promote'. Please, confirm if that is better. Thanks!

2021-03-23 13:35 UTC, Guilherme-Almeida-Zeni commented on examples/test-site/src/components/Contentful/Card/index.ts
> + * Copyright © 2019 Johnson & Johnson
Updated to 2021. Please, review it again. Thanks!

2021-03-23 13:37 UTC, Guilherme-Almeida-Zeni commented on examples/test-site/src/data/pages/cards/test/index.json
> +{
Wrongly commited, it was just for test purposes, the main page "/cards" was already created in the "cards/index.json" file. Removed this test page. Please, review it again. Thanks!

2021-03-23 13:38 UTC, Guilherme-Almeida-Zeni commented on packages/bodiless-card/README.md
> +      </ImageWrapper> <ContentWrapper>
Updated. Please, review it again. Thanks!

2021-03-23 13:38 UTC, Guilherme-Almeida-Zeni commented on packages/bodiless-card/package.json
> +    "mobx": "^5.8.0",
Removed them. Please, review it again. Thanks!

2021-03-24 23:16 UTC, hvanyo commented on examples/test-site/src/data/pages/cards/index.jsx
> +
Can u fix the extra t in the names

2021-03-24 23:19 UTC, hvanyo commented on packages/bodiless-card/package.json
> +  "author": "Guilherme Zeni <gzeni@its.jnj.com>",
Who hoo, first pr and u get a package

2021-03-24 23:21 UTC, hvanyo commented on packages/bodiless-card/package.json
> +    "uuid": "^3.3.2"
We are going to have to add tailwind here as we do lot of styling here.  See another package for example or connect with @beliayeu

2021-03-24 23:22 UTC, hvanyo commented on packages/bodiless-card/src/components/Cards.tokens.tsx
> +/**
If we can add type doc comments here as well

2021-03-24 23:26 UTC, hvanyo commented on packages/bodiless-card/tailwind.config.js
> +/**
I see you had it..  because tokens file has styling you need tailwind..  let’s do quick confirmation at standup

2021-03-24 23:27 UTC, hvanyo commented on examples/test-site/src/data/pages/cards/index.jsx
> + */
Would like to fix test if possible and do u see I cypress test failure above to fix.

2021-03-25 14:15 UTC, hvanyo commented on packages/bodiless-card/package.json
> +    "uuid": "^3.3.2"
Clarified at standup - we do NOT want to add tailwind as dependency here...

2021-03-25 14:40 UTC, hvanyo commented
@Guilherme-Almeida-Zeni  
Summarizing the discussion to correctly include tailwind in the card package:
* Do not add tailwind as dependency in package.json (not needed)
* Do add tailwind.config.js in packages/bodiless-card package
* Whitelist it in https://github.com/johnsonandjohnson/Bodiless-JS/blob/master/packages/gatsby-theme-bodiless/src/dist/tailwindcss/getBodilessConfigs.ts#L19-L22
* Add card package to https://github.com/johnsonandjohnson/Bodiless-JS/blob/master/packages/gatsby-theme-bodiless/package.json#L55

2021-03-26 02:44 UTC, Guilherme-Almeida-Zeni commented on packages/bodiless-backend/src/git.js
>   * limitations under the License.
I'm not sure what happened here but already reverted this file. Please, check it again, thanks!

2021-03-26 02:47 UTC, Guilherme-Almeida-Zeni commented on packages/bodiless-card/tailwind.config.js
> +/**
By standup confirmation, we would need to have this file in the bodiless package, even without declaring dependency. Added it back. Please, review it. Thanks!

2021-03-26 02:49 UTC, Guilherme-Almeida-Zeni commented on examples/test-site/src/data/pages/cards/index.jsx
> + */
In fact, this was something I inherited from touts on organisms package, really sorry to have missed it. Added cypress tests and also fixed the existing one, so by now it seems to be approved by cypress. Please, check it again. Thanks!

2021-03-26 02:50 UTC, Guilherme-Almeida-Zeni commented on examples/test-site/src/data/pages/cards/index.jsx
> +
Removed the extra t's. Please, check it again. Thanks!

2021-03-26 02:50 UTC, Guilherme-Almeida-Zeni commented on packages/bodiless-card/package.json
> +  "author": "Guilherme Zeni <gzeni@its.jnj.com>",
LOL, I hope to be the first of many. Thanks!!

2021-03-26 02:51 UTC, Guilherme-Almeida-Zeni commented on packages/bodiless-card/package.json
> +    "uuid": "^3.3.2"
Okay, confirmed we will keep without tailwind as dependency in the card package.

2021-03-26 02:52 UTC, Guilherme-Almeida-Zeni commented
> @Guilherme-Almeida-Zeni
> Summarizing the discussion to correctly include tailwind in the card package:
> 
> * Do not add tailwind as dependency in package.json (not needed)
> * Do add tailwind.config.js in packages/bodiless-card package
> * Whitelist it in https://github.com/johnsonandjohnson/Bodiless-JS/blob/master/packages/gatsby-theme-bodiless/src/dist/tailwindcss/getBodilessConfigs.ts#L19-L22
> * Add card package to https://github.com/johnsonandjohnson/Bodiless-JS/blob/master/packages/gatsby-theme-bodiless/package.json#L55

''

2021-03-26 17:43 UTC, Guilherme-Almeida-Zeni commented on packages/bodiless-card/doc/api/globals.md
> +*Defined in [packages/bodiless-card/src/components/Cards.tsx:52](https://github.com/Guilherme-Almeida-Zeni/Bodiless-JS/blob/f2eace99/packages/bodiless-card/src/components/Cards.tsx#L52)*
This file is auto-generated and commited has been done by mistake. I've just removed it. Please, check it again. Thanks!

2021-03-26 17:43 UTC, Guilherme-Almeida-Zeni commented on packages/bodiless-card/doc/api/globals.md
> +*Defined in [packages/bodiless-card/src/components/Cards.tsx:31](https://github.com/Guilherme-Almeida-Zeni/Bodiless-JS/blob/f2eace99/packages/bodiless-card/src/components/Cards.tsx#L31)*
This file is auto-generated and commited has been done by mistake. I've just removed it. Please, check it again. Thanks!

2021-03-26 17:45 UTC, Guilherme-Almeida-Zeni commented on packages/bodiless-card/src/components/Cards.tokens.tsx
> +/**
Skipping this since by discussions after standup, token metadatas will be populated in CanvasX.

2021-03-29 11:43 UTC, marcopagliarulo commented on examples/test-site/src/components/Card/withCardDemoVariation.tsx
> +import { ToutComponents, ToutClean } from '@bodiless/card';
Please change ToutComponents to CardComponents and ToutClean to CardClean

2021-03-29 11:43 UTC, marcopagliarulo commented on examples/test-site/src/components/Card/withCardDemoVariation.tsx
> +import { asEditableTout } from '.';
Please use asEditableCard

2021-03-29 11:43 UTC, marcopagliarulo commented on examples/test-site/src/components/Card/withCardDemoVariation.tsx
> +  asEditableTout,
Please use asEditableCard

2021-03-29 11:43 UTC, marcopagliarulo commented on examples/test-site/src/components/Card/withCardDemoVariation.tsx
> +const withDemoContent = withDesign<ToutComponents>({
Please change ToutComponents to CardComponents

2021-03-29 11:43 UTC, marcopagliarulo commented on examples/test-site/src/components/Card/withCardDemoVariation.tsx
> +const Component = withDemoContent(ToutClean);
Please change ToutClean to CardClean

2021-03-29 11:43 UTC, marcopagliarulo commented on examples/test-site/src/components/Card/withCardDemoVariation.tsx
> +  name: 'Tout',
Please rename to 'Card'

2021-03-29 11:43 UTC, marcopagliarulo commented on examples/test-site/src/components/Card/withCardDemoVariation.tsx
> +    Tout: withTokenEditorStyles,
Please rename to Card

2021-03-29 11:43 UTC, marcopagliarulo commented on packages/bodiless-card/package.json
> +    "uuid": "^3.3.2"
does uuid dependency is required? I didn't see a direct usage in the package files

2021-03-29 11:44 UTC, marcopagliarulo commented
Hi @Guilherme-Almeida-Zeni,

since we are going to deprecate Tout component from Organisms, I'd remove at all the touts usage from starter and test-site.

cc @hvanyo

2021-03-29 12:14 UTC, Guilherme-Almeida-Zeni commented
> Hi @Guilherme-Almeida-Zeni,
> 
> since we are going to deprecate Tout component from Organisms, I'd remove at all the touts usage from starter and test-site.
> 
> cc @hvanyo

@marcopagliarulo , @hvanyo , Just a note about this, removing tout page on test-site makes Cypress test break, so in order to do that, it's needed to remove Cypress existing tests. Is it something we would like to do right now since we have some sites using this component?

2021-03-29 12:15 UTC, Guilherme-Almeida-Zeni commented on examples/test-site/src/components/Card/withCardDemoVariation.tsx
> +import { ToutComponents, ToutClean } from '@bodiless/card';
Fixed. Please, check it again. Thanks!

2021-03-29 12:15 UTC, Guilherme-Almeida-Zeni commented on examples/test-site/src/components/Card/withCardDemoVariation.tsx
> +  asEditableTout,
Fixed. Please, check it again. Thanks!

2021-03-29 12:15 UTC, Guilherme-Almeida-Zeni commented on examples/test-site/src/components/Card/withCardDemoVariation.tsx
> +const withDemoContent = withDesign<ToutComponents>({
Fixed. Please, check it again. Thanks!

2021-03-29 12:16 UTC, Guilherme-Almeida-Zeni commented on examples/test-site/src/components/Card/withCardDemoVariation.tsx
> +const Component = withDemoContent(ToutClean);
Fixed. Please, check it again. Thanks!

2021-03-29 12:16 UTC, Guilherme-Almeida-Zeni commented on examples/test-site/src/components/Card/withCardDemoVariation.tsx
> +  name: 'Tout',
Fixed. Please, check it again. Thanks!

2021-03-29 12:16 UTC, Guilherme-Almeida-Zeni commented on examples/test-site/src/components/Card/withCardDemoVariation.tsx
> +    Tout: withTokenEditorStyles,
Fixed. Please, check it again. Thanks!

2021-03-29 12:17 UTC, Guilherme-Almeida-Zeni commented
@marcopagliarulo , regarding this [comment](https://github.com/johnsonandjohnson/Bodiless-JS/pull/934?#discussion_r603219790) (somehow, I couldn't answer there so I'm referencing it here), uuid is required otherwise setup breaks.

2021-03-29 12:19 UTC, Guilherme-Almeida-Zeni commented on examples/test-site/src/components/Card/withCardDemoVariation.tsx
> +import { asEditableTout } from '.';
Fixed. Please, check it again. Thanks!

2021-03-29 12:20 UTC, Guilherme-Almeida-Zeni commented on packages/bodiless-card/package.json
> +    "uuid": "^3.3.2"
uuid is required otherwise setup breaks.

2021-03-30 11:52 UTC, marcopagliarulo commented on examples/starter/src/components/Tout/index.tsx
> +  CardClean,
Hi @Guilherme-Almeida-Zeni,
I think the renaming withing the Tout component is a mistake. Can you please confirm?

2021-03-30 13:01 UTC, Guilherme-Almeida-Zeni commented on examples/starter/src/components/Tout/index.tsx
> +  CardClean,
Hi @marcopagliarulo ,

You are perfeclty right. This was done by mistake. I've just updated a new commit reverting this. Please, check it again. Really thank you!

2021-03-30 14:57 UTC, marcopagliarulo submitted a review, later dismissed

2021-04-01 11:41 UTC, marcopagliarulo submitted a review, later dismissed

2021-04-06 15:39 UTC, hvanyo approved these changes

2021-04-07 12:18 UTC, hvanyo approved these changes

2021-04-07 12:52 UTC, marcopagliarulo commented on packages/bodiless-documentation/doc/Design/DesignSystem.md
> +![](./CardHorizontalDefaultFlow.svg)
I think you should rename the file as well

2021-04-07 13:26 UTC, Guilherme-Almeida-Zeni commented on packages/bodiless-documentation/doc/Design/DesignSystem.md
> +![](./CardHorizontalDefaultFlow.svg)
@marcopagliarulo ,

Renamed and updated the SVG to reflect card. Thanks!

2021-04-07 21:00 UTC, TatsianaMiraniuk approved these changes

2021-04-07 21:09 UTC, hvanyo approved these changes

2021-04-07 21:41 UTC, merged