feat(components): Link to Downloadable Files
johnsonandjohnson/Bodiless-JS pull request #985
Opened 2021-05-03 08:48 UTC by beliayeu

## Changes

## Test Instructions

## Related Issues

2021-05-03 17:35 UTC, Guilherme-Almeida-Zeni requested changes
Hi @beliayeu ,

Please, check the PR comments above.

2021-05-03 17:35 UTC, Guilherme-Almeida-Zeni commented on packages/bodiless-components/src/Link/asBodilessLink.tsx
> +      // eslint-disable-next-line max-len
Hi @beliayeu ,

Instead of disabling next line max length rule, why not formatting like this?
```
      renderForm: ({
        componentProps: {
          unwrap,
          ui: { fileUpload: fileUploadUI } = {},
        },
        closeForm,
      }) => {
```

2021-05-03 17:35 UTC, Guilherme-Almeida-Zeni commented on examples/test-site/src/data/pages/files/index.tsx
> +/**
Hi @beliayeu ,

You added the page "/files" but it seems there is no menu entry for this page. Shouldn't be better to have it inside the menus?

2021-05-03 17:35 UTC, Guilherme-Almeida-Zeni commented on packages/bodiless-components-ui/src/FileUpload.tsx
> +  <div className="bl-text-red">File type not accepted or too many, try again!</div>
Hi @beliayeu , 

This string "File type not accepted or too many, try again!" is also used in line 87. Please, consider using a constant to save this string instead of repeating it. Also, despite it mentions in line 68 for content editors to "Drag a file", they might be tempted to drag more. In this case, "too many" seems to be prone to misunderstanding. Do you think it is worthy to rephrase it and make it clear that only one file is allowed?

2021-05-03 17:35 UTC, Guilherme-Almeida-Zeni commented on packages/bodiless-components/src/FileUpload/FileUpload.tsx
> +      statusText = 'File type not accepted or too many, try again!';
Hi @beliayeu , 

This string "File type not accepted or too many, try again!" is also used in line 85. Please, consider using a constant to save this string instead of repeating it. Also, I think I had seen somewhere that we can only upload one file, and since content editors might be tempted to drag more, in this case, "too many" seems to be prone to misunderstanding. Do you think it is worthy to rephrase it and make it clear that only one file is allowed?

2021-05-04 07:58 UTC, beliayeu commented on packages/bodiless-components-ui/src/FileUpload.tsx
> +      'bl-min-h-grid-16 bl-border bl-border-dashed bl-border-gray-800 bl-bg-gray-100 bl-p-grid-3 bl-mb-grid-3 bl-text-black',
hi @Guilherme-Almeida-Zeni,
1. this hoc is used only for admin, not sure there is a big value to split it
2. this hoc was not introduced as part of this pr, it exists in master, as part of this pr the hoc was moved to a new location
3. since this hoc is already used in other places, I would keep it as is to reduce risk to get regression issues

so I would recommend do not make the separation

2021-05-04 08:11 UTC, beliayeu commented on examples/test-site/src/data/pages/files/index.tsx
> +/**
fixed in 51c7afe81d4fd3429976f039840ed825e165e136

2021-05-04 08:11 UTC, beliayeu commented on examples/test-site/src/data/pages/files/index.tsx
> + * Copyright © 2019 Johnson & Johnson
fixed in 51c7afe81d4fd3429976f039840ed825e165e136

2021-05-04 08:11 UTC, beliayeu commented on packages/bodiless-components-ui/src/FileUpload.tsx
> + * Copyright © 2020 Johnson & Johnson
fixed in 51c7afe81d4fd3429976f039840ed825e165e136

2021-05-04 08:13 UTC, beliayeu commented on packages/bodiless-components-ui/src/FileUpload.tsx
> +  <div className="bl-text-red">File type not accepted or too many, try again!</div>
made the enhancement regarding string duplication in 51c7afe81d4fd3429976f039840ed825e165e136

>Do you think it is worthy to rephrase it and make it clear that only one file is allowed?

as part of this pr I reused the strings from the image upload form, I think UX was confirmed
but I agree it makes sense to raise this question to POBA to check whether they want to rephrase

2021-05-04 08:14 UTC, beliayeu commented on packages/bodiless-components-ui/src/Link.tsx
> + * Copyright © 2020 Johnson & Johnson
fixed in 51c7afe81d4fd3429976f039840ed825e165e136

2021-05-04 08:15 UTC, beliayeu commented on packages/bodiless-components/src/FileUpload/FileUpload.tsx
> +      statusText = 'File type not accepted or too many, try again!';
fixed in 51c7afe81d4fd3429976f039840ed825e165e136
re string rephrase - see above

2021-05-04 08:15 UTC, beliayeu commented on packages/bodiless-components/src/Link/asBodilessLink.tsx
> +      // eslint-disable-next-line max-len
fixed in 51c7afe81d4fd3429976f039840ed825e165e136

2021-05-04 11:06 UTC, Guilherme-Almeida-Zeni submitted a review, later dismissed

2021-05-06 18:19 UTC, irkhodzka commented
Dear @beliayeu,
Please find issues found below.
**issue1**:
Docx files can not be uploaded to the link "Custom allowed file types link"

**STR**:
1. Go to /files/ edit env, edit mode
2. Click on "Custom allowed file types link" -> Edit
3. Try to upload docx file using drag&drop or file manager.

**Expected Result:**
pdf, doc, docx can be uploaded

**Actual Result:**
pdf, doc can be uploaded. Docx file not accepted.

2021-05-06 18:34 UTC, irkhodzka commented
**issue2**:
Different dropzone region UI in different components.

**STR**:
1. In edit env, edit mode
2. Go to local context menu of Main Menu, Breadcrumb, Linkable image, cameleon **linkable** carousel, breadcrumb and observe dropzone region
3. Go to any of the links  local context menu in different places (e.g. - Link toggle, Cards, Rich text Editor, carousel as HorizontalCard, etc) and observe dropzone region
4. Compare dropzone regions

**Expected result**: Dropzone for uploading files is the same across the site - with white region.
<img width="298" alt="accordion-link-regionn" src="https://user-images.githubusercontent.com/81805756/117347553-ecc96c80-aeb1-11eb-8f40-7b658e3d28ad.png">
**Actual Result**: Dropzones are different
<img width="248" alt="carosuel-linkble" src="https://user-images.githubusercontent.com/81805756/117347576-f18e2080-aeb1-11eb-9e63-cea898eb7200.png">


_Note_:
**List of links with correct dropzone**:
Basic, Full Rich Text editors, Product accordions, anchor links, Cards (image, cta, rich text in body), card carousel, contentful, list2, link toggle, logo link.
**List of links with incorrect dropzone**:
Linkable carousel, linkable image, Breadcrumbs on (/breadcrumbs page), Main menu

2021-05-06 18:44 UTC, irkhodzka commented
**issue3:**
Clicking on component with file uploaded to it leads to 404 error page in preview/static mode.

**STR**
1. In edit env, edit mode
1. Upload valid file (pdf) to any component with "link upload" functionality (_except linkable image, linkable carousel, breadcrumbs_): e.g. -  Cards (Cards page, flow-container); Carousel as Horizontal Card (carousel, flow-container); Rich Text editor (basic, full in all components); Home page; link in /list2/; 
2. Switch to Preview mode

**Expected Result:** Uploaded document opens in browser or downloads according to browser settings

**Actual result:** Component with uploaded file leads to 404 error page.

2021-05-06 18:48 UTC, irkhodzka commented
**issue 4:**
There is no validation message when trying to upload 2 files: 1 of them is valid, 1 invalid

**STR**:
1. Edit env, edit mode
2. Go to any component with file upload functionality (e.g. - "Default Link" in /files/ page)
3. Using drag&drop upload 2 files, 1 of them is valid (e.g. txt+pdf)
4. Obsrve  dropzone region

**Expected Result:** Validation message appears.

**Actual Result**: 1 of the files (valid) uploaded.

2021-05-06 18:53 UTC, irkhodzka commented
**issue 5:**
Custom validation message is shown on all link examples

**STR**:
1. Go to /files/ edit env, edit mode
2. Try to upload any invalid file type to any links except "Custom validation message link" (e.g. - txt)
3. Observe error message

**Expected Result:** Standard validation message appears "File type not accepted or too many, try again!"
**Actual Result**: "File type is not accepted, the acceptable file types are Word and PDFs"

_Suggested improvement_: to change "Word" to file extension (doc/docx)

2021-05-06 18:56 UTC, irkhodzka commented
**issue 6**
Text in file upload local context region is not aligned to the full width

**STR:**
1. Go to /files/ edit env, edit mode
2. Click on any link to call the local context menu
3. Observe hint text above dropzone

**Expected Result:** Text takes the full width of context menu

**Actual Result:** Text is shifted left
<img width="328" alt="local-context-region" src="https://user-images.githubusercontent.com/81805756/117351001-dd4c2280-aeb5-11eb-9a7e-e2735ecc6b79.png">

2021-05-06 19:05 UTC, irkhodzka commented
**issue7**
Calling a file manager through dropzone in **Rich Text** triggered only from the second click

**STR:**
1. Go to any component where Rich Text Editor can be added (e.g. - Card with body)
2. Add any text to body text -> Add a link to any text
3. Click on Edit a link to upload a file
4. Click on a white dropzone 
5. Notice file manager does not open from the first click

**Expected Result:** File manager called from the first click

**Actual Result:** File manager called after 2nd click

2021-05-06 19:19 UTC, irkhodzka commented
**issue9**
File can not be drag& dropped to upload region of linkable carousel (carousel page)

**STR:**
1. Go to /carousel/ page edit env, edit mode
2. Scroll to the cameleon carousel -> swap it to linkable
3. Click on linkable carousel to upload a file
4. Drag a file and try to drop to upload region

**Expected result:** File is dropped and uploaded. Success message shown

**Actual Result:** File is not recognizable by dropzone

2021-05-20 03:32 UTC, Guilherme-Almeida-Zeni approved these changes

2021-05-24 12:33 UTC, irkhodzka commented
**issue 10:**
There are two file types (docx, pdf) allowed for default links instead of one.
**STR:** 
1. Go to any page with possibility to add link to downloadable files (e.g. - /files/)
2. Switch to edit mode
3. Click on any of the links except "custom allowed file types." (e.g. - Default)
4. Click Edit -> Dropzone to add files
5. Try to upload docx (not doc) file
**Actual Result**: Docx file successfully uploaded. (Note: doc file is not accepted)
**Expected Result**: Only pdf is acceptable by default

2021-05-26 12:53 UTC, irkhodzka commented
**issue 11:**
Inconsistency in Dropzone UI in Demo site
**STR**: 
1. Go to the Demo site edit env https://edit.feat-downloadable-files-mz537iq-gc5fzrr5cpumq.us-2.platformsh.site
2. In edit mode observe Dropzone UI of linkable image, linked list, logo, main menu, breadcrumbs (e.g. - /components/image/) 
3. In edit mode observe Dropzone UI of any component with file upload functionality except mentioned in the previous step (e.g. /components/richtexteditor/)
4. Compare Dropzones

**Actual Result**: There is no White zone in the components from step 2 vs. white zone exists in components from step 3
**Expected Result:** Dropzone is consistent across all components with link to downloadable files functionality

2021-05-31 13:33 UTC, irkhodzka approved these changes

2021-05-31 14:30 UTC, SW999 commented on packages/bodiless-components/src/FileUpload/FileUpload.tsx
> +  });
Could you add [isUploading] here as a second parameter?

2021-05-31 14:44 UTC, SW999 commented on packages/bodiless-components/src/FileUpload/FileUpload.tsx
> +        {isDragReject && <DragRejected />}
Could we use only one component and one state here? For example: {uploadPartName && <div>{uploadPartName}</div>}

2021-05-31 14:58 UTC, SW999 approved these changes

2021-06-01 08:44 UTC, beliayeu commented on packages/bodiless-components/src/FileUpload/FileUpload.tsx
> +  });
per discussion in skype, the comment is not a merge blocker

2021-06-01 08:44 UTC, beliayeu commented on packages/bodiless-components/src/FileUpload/FileUpload.tsx
> +        {isDragReject && <DragRejected />}
per discussion in skype, the comment is not a merge blocker

2021-06-01 08:44 UTC, merged

2021-06-08 09:20 UTC, irkhodzka commented
**issue 1**
Long file name goes out of dropzone region when adding it to "Custom validation message link"
**STR:**
1. Go to /files/ edit mode,edit env
2. Click on "Custom validation message link" -> Edit to add a file
3. Select a file with >73 characters file name
4. Observe region with file added.
**Actual Result**: File name goes out of dropzone region
<img width="605" alt="long_name" src="https://user-images.githubusercontent.com/81805756/121159407-d701eb00-c853-11eb-95ce-ea115cd4638a.png">
**Expected result**: A part of long file name replaced by suspension points. As it is done on other links example.