feat(gatsby-theme-bodiless): Inject canonical preset to gatsby image node.
johnsonandjohnson/Bodiless-JS pull request #998
Opened 2021-05-17 17:38 UTC by wodenx

## Changes

Inject the image preset as defined in code to the gatsby image node, making it available
to the image logger for comparison with atual data.

This makes it unnecessary to pass the preset explicitly to `withGatsbyImageLogger`.

2021-05-18 13:16 UTC, marcopagliarulo approved these changes

2021-05-18 13:29 UTC, marcopagliarulo requested changes

2021-05-18 13:29 UTC, marcopagliarulo commented on packages/gatsby-theme-bodiless/src/dist/GatsbyImage/withGatsbyImageLogger.tsx
>  const withGatsbyImageLogger = (preset: GatsbyImagePresets): Token => Component => {
preset should be optional to allow the usage of canonicalPreset

2021-05-18 15:34 UTC, wodenx commented on packages/gatsby-theme-bodiless/src/dist/GatsbyImage/withGatsbyImageLogger.tsx
>  const withGatsbyImageLogger = (preset: GatsbyImagePresets): Token => Component => {
yes - please update.

2021-05-19 08:31 UTC, marcopagliarulo commented on packages/gatsby-theme-bodiless/src/dist/GatsbyImage/withGatsbyImageLogger.tsx
>  const withGatsbyImageLogger = (preset: GatsbyImagePresets): Token => Component => {
I cannot update, the branch is on your fork, I am not allowed to push

2021-06-04 13:40 UTC, wodenx commented on packages/gatsby-theme-bodiless/src/dist/GatsbyImage/withGatsbyImageLogger.tsx
>  const withGatsbyImageLogger = (preset: GatsbyImagePresets): Token => Component => {
```suggestion
const withGatsbyImageLogger = (preset?: GatsbyImagePresets): Token => Component => {
```

2021-06-04 13:43 UTC, marcopagliarulo approved these changes

2021-06-11 11:18 UTC, beliayeu approved these changes

2021-06-11 13:08 UTC, merged